from models import get_db, init_db


# 48 teams in 12 groups (A-L), 4 per group
# Actual 2026 FIFA World Cup qualified teams
TEAMS = [
    ('墨西哥', 'A', '🇲🇽'),
    ('捷克', 'A', '🇨🇿'),
    ('南非', 'A', '🇿🇦'),
    ('韩国', 'A', '🇰🇷'),
    ('加拿大', 'B', '🇨🇦'),
    ('波黑', 'B', '🇧🇦'),
    ('卡塔尔', 'B', '🇶🇦'),
    ('瑞士', 'B', '🇨🇭'),
    ('巴西', 'C', '🇧🇷'),
    ('海地', 'C', '🇭🇹'),
    ('摩洛哥', 'C', '🇲🇦'),
    ('苏格兰', 'C', '🏴󠁧󠁢󠁳󠁣󠁴󠁿'),
    ('美国', 'D', '🇺🇸'),
    ('澳大利亚', 'D', '🇦🇺'),
    ('巴拉圭', 'D', '🇵🇾'),
    ('土耳其', 'D', '🇹🇷'),
    ('库拉索', 'E', '🇨🇼'),
    ('厄瓜多尔', 'E', '🇪🇨'),
    ('德国', 'E', '🇩🇪'),
    ('科特迪瓦', 'E', '🇨🇮'),
    ('荷兰', 'F', '🇳🇱'),
    ('日本', 'F', '🇯🇵'),
    ('瑞典', 'F', '🇸🇪'),
    ('突尼斯', 'F', '🇹🇳'),
    ('比利时', 'G', '🇧🇪'),
    ('埃及', 'G', '🇪🇬'),
    ('伊朗', 'G', '🇮🇷'),
    ('新西兰', 'G', '🇳🇿'),
    ('佛得角', 'H', '🇨🇻'),
    ('沙特', 'H', '🇸🇦'),
    ('西班牙', 'H', '🇪🇸'),
    ('乌拉圭', 'H', '🇺🇾'),
    ('法国', 'I', '🇫🇷'),
    ('挪威', 'I', '🇳🇴'),
    ('塞内加尔', 'I', '🇸🇳'),
    ('伊拉克', 'I', '🇮🇶'),
    ('阿尔及利亚', 'J', '🇩🇿'),
    ('阿根廷', 'J', '🇦🇷'),
    ('奥地利', 'J', '🇦🇹'),
    ('约旦', 'J', '🇯🇴'),
    ('哥伦比亚', 'K', '🇨🇴'),
    ('刚果（金）', 'K', '🇨🇩'),
    ('葡萄牙', 'K', '🇵🇹'),
    ('乌兹别克斯坦', 'K', '🇺🇿'),
    ('克罗地亚', 'L', '🇭🇷'),
    ('英格兰', 'L', '🏴󠁧󠁢󠁥󠁮󠁧󠁿'),
    ('加纳', 'L', '🇬🇭'),
    ('巴拿马', 'L', '🇵🇦'),
]


# 26-man squad for each team: (name, name_cn, jersey_number, position)
# position: GK/DF/MF/FW
# name_cn: Chinese display name (empty string = use English)
PLAYERS_DATA = {
    '墨西哥': [
        ('Carlos Acevedo', '卡洛斯·阿塞韦多', 1, 'GK'),
        ('Guillermo Ochoa', '吉列尔莫·奥乔亚', 2, 'GK'),
        ('Raul Rangel', '劳尔·兰赫尔', 3, 'GK'),
        ('Edson Alvarez', '埃德松·阿尔瓦雷斯', 4, 'DF'),
        ('Israel Reyes', '伊斯雷尔·雷耶斯', 5, 'DF'),
        ('Jesus Gallardo', '赫苏斯·加利亚多', 6, 'DF'),
        ('Johan Vasquez', '约翰·巴斯克斯', 7, 'DF'),
        ('Jorge Sanchez', '豪尔赫·桑切斯', 8, 'DF'),
        ('Mateo Chavez', '马特奥·查韦斯', 9, 'DF'),
        ('Alvaro Fidalgo', '阿尔瓦罗·菲达尔戈', 10, 'MF'),
        ('Brian Gutierrez', '布里安·古铁雷斯', 11, 'MF'),
        ('Erik Lira', '埃里克·利拉', 12, 'MF'),
        ('Gilberto Mora', '希尔韦托·莫拉', 13, 'MF'),
        ('Luis Romo', '路易斯·罗莫', 14, 'MF'),
        ('Obed Vargas', '奥贝德·巴尔加斯', 15, 'MF'),
        ('Orbelin Pineda', '奥韦林·皮内达', 16, 'MF'),
        ('Alexis Vega', '亚历克西斯·贝加', 17, 'FW'),
        ('Armando Gonzalez', '阿曼多·冈萨雷斯', 18, 'FW'),
        ('Cesar Huerta', '塞萨尔·韦尔塔', 19, 'FW'),
        ('Guillermo Martinez', '吉列尔莫·马丁内斯', 20, 'FW'),
        ('Julian Quinones', '胡利安·基尼奥内斯', 21, 'FW'),
        ('Raul Jimenez', '劳尔·希门尼斯', 22, 'FW'),
        ('Santiago Gimenez', '圣地亚哥·希门尼斯', 23, 'FW'),
    ],
    '捷克': [
        ('Lukas Hornicek', '卢卡斯·霍尼切克', 1, 'GK'),
        ('Matej Kovar', '马捷·科瓦日', 2, 'GK'),
        ('Jindrich Stanek', '英德日赫·斯塔涅克', 3, 'GK'),
        ('Vladimir Coufal', '弗拉基米尔·曹法尔', 4, 'DF'),
        ('David Doudera', '大卫·杜德拉', 5, 'DF'),
        ('Tomas Holes', '托马什·霍莱什', 6, 'DF'),
        ('Robin Hranac', '罗宾·赫拉纳奇', 7, 'DF'),
        ('Stepan Chaloupek', '斯捷潘·查卢佩克', 8, 'DF'),
        ('David Jurasek', '大卫·尤拉塞克', 9, 'DF'),
        ('Ladislav Krejci', '拉吉斯拉夫·克雷伊奇', 10, 'DF'),
        ('Jaroslav Zeleny', '雅罗斯拉夫·泽莱尼', 11, 'DF'),
        ('David Zima', '大卫·齐马', 12, 'DF'),
        ('Lukas Cerv', '卢卡斯·切尔夫', 13, 'MF'),
        ('Vladimir Darida', '弗拉迪米尔·达里达', 14, 'MF'),
        ('Lukas Provod', '卢卡斯·普罗沃德', 15, 'MF'),
        ('Michal Sadilek', '米哈尔·萨迪莱克', 16, 'MF'),
        ('Hugo Sochurek', '胡戈·索楚雷克', 17, 'MF'),
        ('Alexandr Sojka', '亚历山大·索伊卡', 18, 'MF'),
        ('Tomas Soucek', '托马什·绍切克', 19, 'MF'),
        ('Pavel Sulc', '帕维尔·舒尔茨', 20, 'MF'),
        ('Denis Visinsky', '丹尼斯·维辛斯基', 21, 'MF'),
        ('Adam Hlozek', '亚当·赫洛热克', 22, 'FW'),
        ('Tomas Chory', '托马斯·乔里', 23, 'FW'),
        ('Mojmir Chytil', '莫伊米尔·希季尔', 24, 'FW'),
        ('Jan Kuchta', '扬·库赫塔', 25, 'FW'),
        ('Patrik Schick', '帕特里克·希克', 26, 'FW'),
    ],
    '南非': [
        ('Sipho Chaine', '西波·钱恩', 1, 'GK'),
        ('Ricardo Goss', '里卡多·戈斯', 2, 'GK'),
        ('Ronwen Williams', '罗恩文·威廉姆斯', 3, 'GK'),
        ('Aubrey Modiba', '奥布雷·莫迪巴', 4, 'DF'),
        ('Khuliso Mudau', '库利索·穆达乌', 5, 'DF'),
        ('Nkosinathi Sibisi', '恩科西纳蒂·西比西', 6, 'DF'),
        ('Mbekezeli Mbokazi', '姆贝凯泽利·姆博卡齐', 7, 'DF'),
        ('Ime Okon', '伊梅·奥孔', 8, 'DF'),
        ('Samukele Kabini', '萨穆凯洛·卡比尼', 9, 'DF'),
        ('Khulumani Ndamane', '库卢马尼·恩达马内', 10, 'DF'),
        ('Thabang Matuludi', '塔邦·马图鲁迪', 11, 'DF'),
        ('Kamogelo Sebelebele', '卡莫盖洛·塞贝莱贝莱', 12, 'DF'),
        ('Bradley Cross', '布拉德利·克罗斯', 13, 'DF'),
        ('Olwethy Makhanya', '奥尔韦图·马卡尼亚', 14, 'DF'),
        ('Teboho Mokoena', '泰博霍·莫库纳', 15, 'MF'),
        ('Sphephelo Sithole', '斯菲佩洛·西索莱', 16, 'MF'),
        ('Thalente Mbatha', '塔伦特·姆巴塔', 17, 'MF'),
        ('Jayden Adams', '杰登·亚当斯', 18, 'MF'),
        ('Themba Zwane', '滕巴·兹瓦内', 19, 'FW'),
        ('Lyle Foster', '莱尔·福斯特', 20, 'FW'),
        ('Evidence Makgopa', '埃维登斯·马科戈帕', 21, 'FW'),
        ('Oswin Appollis', '奥斯温·阿波利斯', 22, 'FW'),
        ('Iqraam Rayners', '伊克拉姆·雷纳斯', 23, 'FW'),
        ('Relebohile Mofokeng', '雷莱博希莱·莫福肯', 24, 'FW'),
        ('Thapelo Maseko', '塔佩洛·马塞科', 25, 'FW'),
        ('Tshepang Moremi', '切潘·莫雷米', 26, 'FW'),
    ],
    '韩国': [
        ('Hyeon-Woo Jo', '赵贤祐', 1, 'GK'),
        ('Seung-Gyu Kim', '金承奎', 2, 'GK'),
        ('Bum-Keun Song', '宋范根', 3, 'GK'),
        ('Moon-Hwan Kim', '金纹奂', 4, 'DF'),
        ('Min-Jae Kim', '金玟哉', 5, 'DF'),
        ('Tae-Hyun Kim', '金太炫', 6, 'DF'),
        ('Jin-Seob Park', '朴镇燮', 7, 'DF'),
        ('Young-Woo Seol', '薛英佑', 8, 'DF'),
        ('Jens Castrop', '延斯·卡斯特罗普', 9, 'DF'),
        ('Ki-Hyuk Lee', '李期奕', 10, 'DF'),
        ('Tae-Seok Lee', '李太锡', 11, 'DF'),
        ('Han-Beom Lee', '李韩汎', 12, 'DF'),
        ('Yu-Min Cho', '曹侑珉', 13, 'DF'),
        ('Jin-Gyu Kim', '金镇圭', 14, 'MF'),
        ('Jun-Ho Bae', '裴峻浩', 15, 'MF'),
        ('Seung-Ho Paik', '白昇浩', 16, 'MF'),
        ('Hyun-Jun Yang', '杨贤俊', 17, 'MF'),
        ('Ji-Sung Eom', '严智星', 18, 'MF'),
        ('Kang-In Lee', '李刚仁', 19, 'MF'),
        ('Dong-Gyeong Lee', '李东炅', 20, 'MF'),
        ('Jae-Sung Lee', '李在城', 21, 'MF'),
        ('In-Beom Hwang', '黄仁范', 22, 'MF'),
        ('Hee-Chan Hwang', '黄喜灿', 23, 'MF'),
        ('Heung-Min Son', '孙兴慜', 24, 'FW'),
        ('Hyeon-Gyu Oh', '吴贤揆', 25, 'FW'),
        ('Gue-Sung Cho', '曹圭成', 26, 'FW'),
    ],
    '加拿大': [
        ('Maxime Crepeau', '马克西姆·克雷波', 1, 'GK'),
        ('Owen Goodman', '欧文·古德曼', 2, 'GK'),
        ('Dayne St. Clair', '达尼·圣克莱尔', 3, 'GK'),
        ('Moise Bombito', '莫伊斯·波姆比托', 4, 'DF'),
        ('Derek Cornelius', '德雷克·科内柳斯', 5, 'DF'),
        ('Alphonso Davies', '阿方索·戴维斯', 6, 'DF'),
        ('Luc de Fougerolles', '吕克·德富格罗莱斯', 7, 'DF'),
        ('Alistair Johnston', '阿里斯特尔·约翰斯顿', 8, 'DF'),
        ('Alfie Jones', '阿尔菲·琼斯', 9, 'DF'),
        ('Richie Laryea', '里奇·拉耶', 10, 'DF'),
        ('Niko Sigur', '尼科·西古尔', 11, 'DF'),
        ('Joel Waterman', '乔尔·沃特曼', 12, 'DF'),
        ('Ali Ahmed', '阿里·艾哈迈德', 13, 'MF'),
        ('Tajon Buchanan', '塔容·布坎南', 14, 'MF'),
        ('Mathieu Choiniere', '马修·舒瓦尼埃', 15, 'MF'),
        ('Stephen Eustaquio', '史蒂芬·欧斯塔基奥', 16, 'MF'),
        ('Marcelo Flores', '马塞洛·弗洛雷斯', 17, 'MF'),
        ('Ismael Kone', '伊斯梅尔·科内', 18, 'MF'),
        ('Liam Millar', '利亚姆·米拉尔', 19, 'MF'),
        ('Jonathan Osorio', '乔纳森·奥索里奥', 20, 'MF'),
        ('Nathan-Dylan Saliba', '内森·萨利巴', 21, 'MF'),
        ('Jacob Shaffelburg', '雅各布·沙菲尔伯格', 22, 'MF'),
        ('Jonathan David', '乔纳森·戴维', 23, 'FW'),
        ('Promise David', '普罗米斯·戴维', 24, 'FW'),
        ('Cyle Larin', '凯尔·拉林', 25, 'FW'),
        ('Tani Oluwaseyi', '塔尼·奥卢瓦塞伊', 26, 'FW'),
    ],
    '波黑': [
        ('Nikola Vasilj', '尼古拉·瓦西里', 1, 'GK'),
        ('Martin Zlomislic', '马丁·兹洛米斯利奇', 2, 'GK'),
        ('Osman Hadzikic', '奥斯曼·哈季基奇', 3, 'GK'),
        ('Sead Kolasinac', '塞亚德·科拉希纳茨', 4, 'DF'),
        ('Amar Dedic', '阿马尔·德蒂奇', 5, 'DF'),
        ('Nihad Mujakic', '尼哈德·穆亚基奇', 6, 'DF'),
        ('Nikola Katic', '尼克拉·卡蒂奇', 7, 'DF'),
        ('Tarik Muharemovic', '塔里克·穆哈雷莫维奇', 8, 'DF'),
        ('Stjepan Radeljic', '斯捷潘·拉德里季奇', 9, 'DF'),
        ('Dennis Hadzikadunic', '丹尼斯·哈迪卡杜尼克', 10, 'DF'),
        ('Nidal Celik', '尼达尔·切利克', 11, 'DF'),
        ('Amir Hadziahmetovic', '阿米尔·哈吉艾哈迈托维奇', 12, 'MF'),
        ('Ivan Sunjic', '伊万·舒尼奇', 13, 'MF'),
        ('Ivan Basic', '伊万·巴希奇', 14, 'MF'),
        ('Dzenis Burnic', '泽尼斯·布尔尼奇', 15, 'MF'),
        ('Ermin Mahmic', '埃尔明·马赫米奇', 16, 'MF'),
        ('Benjamin Tahirovic', '本亚明·塔希罗维奇', 17, 'MF'),
        ('Amar Memic', '阿马尔·梅米奇', 18, 'MF'),
        ('Armin Gigovic', '阿尔明·吉戈维奇', 19, 'MF'),
        ('Kerim Alajbegovic', '克里姆·阿拉伊贝戈维奇', 20, 'MF'),
        ('Esmir Bajraktarevic', '埃斯米尔·巴里亚克塔雷维奇', 21, 'MF'),
        ('Ermedin Demirovic', '埃尔梅丁·德米罗维奇', 22, 'FW'),
        ('Jovo Lukic', '约沃·卢基奇', 23, 'FW'),
        ('Samed Bazdar', '萨梅德·巴日达尔', 24, 'FW'),
        ('Haris Tabakovic', '哈里斯·塔巴科维奇', 25, 'FW'),
        ('Edin Dzeko', '埃丁·哲科', 26, 'FW'),
    ],
    '卡塔尔': [
        ('Salah Zakaria', '萨拉赫·扎卡里亚', 1, 'GK'),
        ('Mahmoud Abunada', '马穆德·阿布纳德', 2, 'GK'),
        ('Meshaal Barsham', '梅萨尔·巴沙姆', 3, 'GK'),
        ('Hashmi Hussein', '阿尔·哈希米·阿尔·侯赛因', 4, 'DF'),
        ('Ayoub Alawi', '阿尤布·阿莱维', 5, 'DF'),
        ('Boualem Khoukhi', '布阿莱姆·胡希', 6, 'DF'),
        ('Pedro Miguel', '佩德罗·米格尔', 7, 'DF'),
        ('Issa Laaye', '伊萨·拉耶', 8, 'DF'),
        ('Lucas Mendes', '卢卡斯·门德斯', 9, 'DF'),
        ('Sultan Al-Brake', '苏丹·布雷克', 10, 'DF'),
        ('Homam Al-Amin', '霍曼·艾哈迈德', 11, 'DF'),
        ('Mohammed Al-Manai', '穆罕默德·马奈', 12, 'MF'),
        ('Jassem Jaber', '贾西姆·阿卜杜勒萨拉姆', 13, 'MF'),
        ('Karim Boudiaf', '卡里姆·布迪亚夫', 14, 'MF'),
        ('Ahmed Fathi', '艾哈迈德·法特希', 15, 'MF'),
        ('Abdulaziz Hatem', '阿卜杜勒阿齐兹·哈特姆', 16, 'MF'),
        ('Assim Madibo', '阿西姆·马迪博', 17, 'MF'),
        ('Tahseen Mohammed', '塔辛·穆罕默德·贾姆希德', 18, 'FW'),
        ('Edmilson Junior', '埃迪米森', 19, 'FW'),
        ('Almoez Ali', '埃莫兹·阿里', 20, 'FW'),
        ('Akram Afif', '阿克拉姆·阿菲夫', 21, 'FW'),
        ('Mohammed Muntari', '穆罕默德·蒙塔里', 22, 'FW'),
        ('Youssef Abdulrazzaq', '优素福·阿卜杜里萨格', 23, 'FW'),
        ('Ahmed Alaa', '艾哈迈德·阿拉丁', 24, 'FW'),
        ('Hassan Al-Haydos', '哈桑·艾尔·海多斯', 25, 'FW'),
        ('Ahmed Al-Janahi', '艾哈迈德·贾内希', 26, 'FW'),
    ],
    '瑞士': [
        ('Marvin Keller', '凯勒', 1, 'GK'),
        ('Gregor Kobel', '格雷戈尔·科贝尔', 2, 'GK'),
        ('Yvon Mvogo', '姆沃戈', 3, 'GK'),
        ('Manuel Akanji', '曼努埃尔·阿坎吉', 4, 'DF'),
        ('Aurele Amenda', '阿曼达', 5, 'DF'),
        ('Eray Comert', '科默特', 6, 'DF'),
        ('Nico Elvedi', '埃尔维迪', 7, 'DF'),
        ('Luca Jaquez', '雅克', 8, 'DF'),
        ('Miro Muheim', '穆海姆', 9, 'DF'),
        ('Ricardo Rodriguez', '里卡多·罗德里格斯', 10, 'DF'),
        ('Silvan Widmer', '威德默', 11, 'DF'),
        ('Michel Aebischer', '埃比舍尔', 12, 'MF'),
        ('Christian Fassnacht', '法斯纳赫特', 13, 'MF'),
        ('Remo Freuler', '弗鲁勒', 14, 'MF'),
        ('Ardon Jashari', '亚沙里', 15, 'MF'),
        ('Johan Manzambi', '曼赞比', 16, 'MF'),
        ('Fabian Rieder', '法比安·里德', 17, 'MF'),
        ('Djibril Sow', '索乌', 18, 'MF'),
        ('Ruben Vargas', '鲁本·巴尔加斯', 19, 'MF'),
        ('Granit Xhaka', '格拉尼特·扎卡', 20, 'MF'),
        ('Denis Zakaria', '德尼斯·扎卡里亚', 21, 'MF'),
        ('Zeki Amdouni', '阿姆杜尼', 22, 'FW'),
        ('Breel Embolo', '布里尔·恩博洛', 23, 'FW'),
        ('Cedric Itten', '塞德里克·埃滕', 24, 'FW'),
        ('Dan Ndoye', '恩多耶', 25, 'FW'),
        ('Noah Okafor', '诺亚·奥卡福', 26, 'FW'),
    ],
    '巴西': [
        ('Alisson', '阿利松', 1, 'GK'),
        ('Ederson', '埃德森', 2, 'GK'),
        ('Weverton', '维弗顿', 3, 'GK'),
        ('Marquinhos', '马尔基尼奥斯', 4, 'DF'),
        ('Gabriel', '加布里埃尔', 5, 'DF'),
        ('Bremer', '布雷默', 6, 'DF'),
        ('Ibanez', '伊巴涅斯', 7, 'DF'),
        ('Leo Pereira', '莱奥·佩雷拉', 8, 'DF'),
        ('Wesley', '韦斯利', 9, 'DF'),
        ('Alex Sandro', '亚历克斯·桑德罗', 10, 'DF'),
        ('Douglas Santos', '道格拉斯·桑托斯', 11, 'DF'),
        ('Danilo', '达尼洛', 12, 'MF'),
        ('Casemiro', '卡塞米罗', 13, 'MF'),
        ('Bruno Guimaraes', '布鲁诺·吉马良斯', 14, 'MF'),
        ('Fabinho', '法比尼奥', 15, 'MF'),
        ('Lucas Paqueta', '卢卡斯·帕克塔', 16, 'MF'),
        ('Vinicius Junior', '维尼修斯', 17, 'FW'),
        ('Raphinha', '拉菲尼亚', 18, 'FW'),
        ('Matheus Cunha', '马特乌斯·库尼亚', 19, 'FW'),
        ('Luiz Henrique', '路易斯·恩里克', 20, 'FW'),
        ('Igor Thiago', '伊戈尔·蒂亚戈', 21, 'FW'),
        ('Endrick', '恩德里克', 22, 'FW'),
        ('Gabriel Martinelli', '马丁内利', 23, 'FW'),
        ('Rayan', '拉扬', 24, 'FW'),
        ('Neymar', '内马尔', 25, 'FW'),
    ],
    '海地': [
        ('Johnny Placide', '普拉西德', 1, 'GK'),
        ('Alexandre Pierre', '亚历山大·皮埃尔', 2, 'GK'),
        ('Josue Duverger', '杜弗格', 3, 'GK'),
        ('Carlens Arcus', '阿库斯', 4, 'DF'),
        ('Wilguens Pauguain', '波甘', 5, 'DF'),
        ('Duke Lacroix', '杜克·拉克鲁瓦', 6, 'DF'),
        ('Martin Experience', '埃克斯派瑞斯', 7, 'DF'),
        ('Jean-Kevin Duverne', '杜维内', 8, 'DF'),
        ('Ricardo Ade', '里卡多·阿德', 9, 'DF'),
        ('Hannes Delcroix', '德克鲁瓦', 10, 'DF'),
        ('Keeto Thermoncy', '泰尔蒙西', 11, 'DF'),
        ('Leverton Pierre', '莱弗顿·皮埃尔', 12, 'MF'),
        ('Carl-Fred Sainthe', '桑泰', 13, 'MF'),
        ('Jean-Jacques Danley', '丹利', 14, 'MF'),
        ('Jean-Ricner Bellegarde', '贝莱加德', 15, 'MF'),
        ('Pierre Woodenski', '伍登斯基', 16, 'MF'),
        ('Dominique Simon', '多米尼克·西蒙', 17, 'MF'),
        ('Louicius Deedson', '迪德森', 18, 'FW'),
        ('Ruben Providence', '普罗维登斯', 19, 'FW'),
        ('Josue Casimir', '卡西米尔', 20, 'FW'),
        ('Derrick Etienne', '艾蒂安', 21, 'FW'),
        ('Wilson Isidor', '伊西多', 22, 'FW'),
        ('Duckens Nazon', '纳宗', 23, 'FW'),
        ('Frantzdy Pierrot', '皮埃罗', 24, 'FW'),
        ('Yassin Fortune', '福尔蒂内', 25, 'FW'),
        ('Lenny Joseph', '约瑟夫', 26, 'FW'),
    ],
    '摩洛哥': [
        ('Yassine Bounou', '亚辛·布努', 1, 'GK'),
        ('Munir Mohamedi', '穆尼尔·穆罕默德', 2, 'GK'),
        ('Ahmed Tagnaouti', '塔格诺提', 3, 'GK'),
        ('Noussair Mazraoui', '努赛尔·马兹拉维', 4, 'DF'),
        ('Anass Salah-Eddine', '萨拉赫·埃丁', 5, 'DF'),
        ('Youssef Belammari', '贝拉马里', 6, 'DF'),
        ('Nayef Aguerd', '纳耶夫·阿格尔德', 7, 'DF'),
        ('Chadi Riad', '里亚德', 8, 'DF'),
        ('Issa Diop', '迪奥普', 9, 'DF'),
        ('Redouane Halhal', '哈尔哈尔', 10, 'DF'),
        ('Achraf Hakimi', '阿什拉夫·哈基米', 11, 'DF'),
        ('Zakaria El Ouahdi', '埃尔瓦赫迪', 12, 'DF'),
        ('Samir El Mourabet', '穆拉贝特', 13, 'MF'),
        ('Ayyoub Bouaddi', '布阿迪', 14, 'MF'),
        ('Neil El Aynaoui', '艾纳维', 15, 'MF'),
        ('Sofyan Amrabat', '索菲扬·阿姆拉巴特', 16, 'MF'),
        ('Azzedine Ounahi', '奥纳西', 17, 'MF'),
        ('Bilal El Khannouss', '埃尔哈努斯', 18, 'MF'),
        ('Ismael Saibari', '塞巴里', 19, 'MF'),
        ('Abdessamad Ezzalzouli', '埃扎卢利', 20, 'FW'),
        ('Chemsdine Talbi', '塔尔比', 21, 'FW'),
        ('Soufiane Rahimi', '拉希米', 22, 'FW'),
        ('Ayoub El Kaabi', '卡埃比', 23, 'FW'),
        ('Brahim Diaz', '卜拉欣·迪亚斯', 24, 'FW'),
        ('Yassine Gessime', '亚辛', 25, 'FW'),
        ('Ayoub Amaimouni-Echghouyabe', '阿迈穆尼-埃奇古亚布', 26, 'FW'),
    ],
    '苏格兰': [
        ('Craig Gordon', '克雷格·戈登', 1, 'GK'),
        ('Angus Gunn', '安格斯·冈恩', 2, 'GK'),
        ('Liam Kelly', '利亚姆·凯利', 3, 'GK'),
        ('Grant Hanley', '格兰特·汉利', 4, 'DF'),
        ('Jack Hendry', '杰克·亨德利', 5, 'DF'),
        ('Aaron Hickey', '亚伦·希基', 6, 'DF'),
        ('Dom Hyam', '多米尼克·海厄姆', 7, 'DF'),
        ('Scott McKenna', '斯科特·麦肯纳', 8, 'DF'),
        ('Nathan Patterson', '内森·帕特森', 9, 'DF'),
        ('Anthony Ralston', '安东尼·拉尔斯顿', 10, 'DF'),
        ('Andy Robertson', '安迪·罗伯逊', 11, 'DF'),
        ('John Souttar', '约翰·苏塔尔', 12, 'DF'),
        ('Kieran Tierney', '基兰·蒂尔尼', 13, 'DF'),
        ('Ryan Christie', '瑞安·克里斯蒂', 14, 'MF'),
        ('Findlay Curtis', '芬德利·库蒂斯', 15, 'MF'),
        ('Lewis Ferguson', '刘易斯·弗格森', 16, 'MF'),
        ('Ben Gannon-Doak', '本·多克', 17, 'MF'),
        ('Tyler Fletcher', '泰勒·弗莱彻', 18, 'MF'),
        ('John McGinn', '约翰·麦金', 19, 'MF'),
        ('Kenny McLean', '肯尼·麦克莱恩', 20, 'MF'),
        ('Scott McTominay', '斯科特·麦克托米奈', 21, 'MF'),
        ('Che Adams', '切·亚当斯', 22, 'FW'),
        ('Lyndon Dykes', '林顿·戴克斯', 23, 'FW'),
        ('George Hirst', '乔治·赫斯特', 24, 'FW'),
        ('Lawrence Shankland', '劳伦斯·尚克兰', 25, 'FW'),
        ('Ross Stewart', '罗斯·斯图尔特', 26, 'FW'),
    ],
    '美国': [
        ('Chris Brady', '克里斯·布雷迪', 1, 'GK'),
        ('Matt Freese', '马特·弗里兹', 2, 'GK'),
        ('Matt Turner', '马特·特纳', 3, 'GK'),
        ('Max Arfsten', '马克斯·阿夫斯滕', 4, 'DF'),
        ('Sergino Dest', '塞吉诺·德斯特', 5, 'DF'),
        ('Alex Freeman', '亚历克斯·弗里曼', 6, 'DF'),
        ('Mark McKenzie', '马克·麦肯齐', 7, 'DF'),
        ('Tim Ream', '蒂姆·里姆', 8, 'DF'),
        ('Chris Richards', '克里斯·理查兹', 9, 'DF'),
        ('Antonee Robinson', '安东尼·罗宾逊', 10, 'DF'),
        ('Miles Robinson', '米尔斯·罗宾森', 11, 'DF'),
        ('Joe Scally', '乔·斯卡利', 12, 'DF'),
        ('Auston Trusty', '奥斯顿·托斯蒂', 13, 'DF'),
        ('Tyler Adams', '泰勒·亚当斯', 14, 'MF'),
        ('Sebastian Berhalter', '塞巴斯蒂安·贝哈尔特', 15, 'MF'),
        ('Weston McKennie', '韦斯顿·麦肯尼', 16, 'MF'),
        ('Gio Reyna', '乔·雷纳', 17, 'MF'),
        ('Cristian Roldan', '克里斯蒂安·罗尔丹', 18, 'MF'),
        ('Malik Tillman', '马利克·蒂尔曼', 19, 'MF'),
        ('Brenden Aaronson', '布伦登·阿隆森', 20, 'FW'),
        ('Folarin Balogun', '福拉林·巴洛贡', 21, 'FW'),
        ('Ricardo Pepi', '里卡多·佩皮', 22, 'FW'),
        ('Christian Pulisic', '克里斯蒂安·普利西奇', 23, 'FW'),
        ('Tim Weah', '蒂莫西·维亚', 24, 'FW'),
        ('Haji Wright', '哈吉·赖特', 25, 'FW'),
        ('Alejandro Zendejas', '亚历杭德罗·赞德哈斯', 26, 'FW'),
    ],
    '澳大利亚': [
        ('Ryan', '瑞安', 1, 'GK'),
        ('Izzo', '保罗·伊佐', 2, 'GK'),
        ('Beach', '帕特里克·比奇', 3, 'GK'),
        ('Behich', '阿齐兹·贝希奇', 4, 'DF'),
        ('Bos', '乔丹·博斯', 5, 'DF'),
        ('Burgess', '卡梅隆·伯吉斯', 6, 'DF'),
        ('Circati', '亚历山德罗·西卡蒂', 7, 'DF'),
        ('Degenek', '米洛斯·迪基尼克', 8, 'DF'),
        ('Geria', '杰森·杰里亚', 9, 'DF'),
        ('Herrington', '卢卡斯·赫林顿', 10, 'DF'),
        ('Italiano', '伊塔利亚诺', 11, 'DF'),
        ('Souttar', '哈利·苏塔尔', 12, 'DF'),
        ('Trewin', '凯·特里温', 13, 'DF'),
        ('Devlin', '卡梅隆·德夫林', 14, 'MF'),
        ('Hrustic', '阿伊丁·赫鲁斯蒂奇', 15, 'MF'),
        ('Irvine', '杰克逊·欧文', 16, 'MF'),
        ('Metcalfe', '康纳·梅特卡夫', 17, 'MF'),
        ('Okon-Englster', '保罗·奥康-恩斯特勒', 18, 'MF'),
        ('O\'Neill', '奥尼尔', 19, 'MF'),
        ('Irankunda', '伊兰昆达', 20, 'FW'),
        ('Leckie', '马修·莱基', 21, 'FW'),
        ('Mabil', '奥尔·马比尔', 22, 'FW'),
        ('Toure', '穆罕默德·图雷', 23, 'FW'),
        ('Velupilly', '尼山·韦卢皮莱', 24, 'FW'),
        ('Volpato', '克里斯蒂安·沃尔帕托', 25, 'FW'),
        ('Tete Yengi', '特特·延吉', 26, 'FW'),
    ],
    '巴拉圭': [
        ('Roberto Junior Fernandez', '罗伯托·费尔南德斯', 1, 'GK'),
        ('Orlando Gill', '奥兰多·希尔', 2, 'GK'),
        ('Gaston Olveira', '加斯顿·奥尔维拉', 3, 'GK'),
        ('Omar Alderete', '奥马尔·阿尔德雷特', 4, 'DF'),
        ('Junior Alonso', '朱尼尔·阿隆索', 5, 'DF'),
        ('Fabian Balbuena', '法比安·巴尔武埃纳', 6, 'DF'),
        ('Juan Jose Caceres', '胡安·何塞·卡塞雷斯', 7, 'DF'),
        ('Jose Canale', '何塞·卡纳莱', 8, 'DF'),
        ('Gustavo Gomez', '古斯塔沃·戈麦斯', 9, 'DF'),
        ('Alexandro Maidana', '亚历山德罗·迈达纳', 10, 'DF'),
        ('Gustavo Velazquez', '古斯塔沃·贝拉斯克斯', 11, 'DF'),
        ('Damian Bobadilla', '达米安·博瓦迪利亚', 12, 'MF'),
        ('Gustavo Caballero', '古斯塔沃·卡瓦列罗', 13, 'MF'),
        ('Andres Cubas', '安德烈斯·库瓦斯', 14, 'MF'),
        ('Matias Galarza', '马蒂亚斯·加拉尔萨', 15, 'MF'),
        ('Diego Gomez', '迭戈·戈麦斯', 16, 'MF'),
        ('Mauricio Magalhaes', '毛里西奥·马加良斯', 17, 'MF'),
        ('Briaian Ojeda', '布里安·奥赫达', 18, 'MF'),
        ('Alejandro Romero', '亚历杭德罗·罗梅罗', 19, 'MF'),
        ('Miguel Almiron', '米格尔·阿尔米隆', 20, 'FW'),
        ('Gabriel Avalos', '加布里埃尔·阿瓦洛斯', 21, 'FW'),
        ('Alex Arce', '亚历克斯·阿尔塞', 22, 'FW'),
        ('Julio Enciso', '胡利奥·恩西索', 23, 'FW'),
        ('Isidro Pitta', '伊西德罗·皮塔', 24, 'FW'),
        ('Antonio Sanabria', '安东尼奥·萨纳夫里亚', 25, 'FW'),
        ('Ramon Sosa', '拉蒙·索萨', 26, 'FW'),
    ],
    '土耳其': [
        ('Ugurcan Cakir', '乌古尔詹·查基尔', 1, 'GK'),
        ('Altay Bayindir', '阿尔泰·巴因迪尔', 2, 'GK'),
        ('Mert Gunok', '梅尔特·居诺克', 3, 'GK'),
        ('Ferdi Kadioglu', '费尔迪·卡迪奥卢', 4, 'DF'),
        ('Merih Demiral', '梅里赫·德米拉尔', 5, 'DF'),
        ('Zeki Celik', '泽基·切利克', 6, 'DF'),
        ('Ozan Kabak', '奥赞·卡巴克', 7, 'DF'),
        ('Mert Muldur', '梅尔特·米尔德尔', 8, 'DF'),
        ('Abdulkerim Bardakci', '阿卜杜勒克里姆·巴尔达克奇', 9, 'DF'),
        ('Eren Elmali', '埃伦·埃尔马勒', 10, 'DF'),
        ('Caglar Soyuncu', '恰拉尔·瑟因居', 11, 'DF'),
        ('Samet Akaydin', '萨梅特·阿卡伊登', 12, 'DF'),
        ('Arda Guler', '阿尔达·居莱尔', 13, 'MF'),
        ('Can Uzun', '詹·乌尊', 14, 'MF'),
        ('Orkun Kokcu', '奥尔昆·科克曲', 15, 'MF'),
        ('Hakan Calhanoglu', '哈坎·恰尔汗奥卢', 16, 'MF'),
        ('Ismail Yuksek', '伊斯梅尔·于克塞克', 17, 'MF'),
        ('Kaan Ayhan', '卡安·艾汉', 18, 'MF'),
        ('Salih Ozcan', '萨利赫·厄兹詹', 19, 'MF'),
        ('Kenan Yildiz', '凯南·伊尔迪兹', 20, 'FW'),
        ('Baris Alper Yilmaz', '巴里什·阿尔珀·伊尔马兹', 21, 'FW'),
        ('Kerem Akturkoglu', '凯雷姆·阿克蒂尔科格卢', 22, 'FW'),
        ('Yunus Akgun', '尤努斯·阿克金', 23, 'FW'),
        ('Oguz Aydin', '奥乌兹·艾登', 24, 'FW'),
        ('Deniz Gul', '德尼兹·居尔', 25, 'FW'),
        ('Irfan Can Kahveci', '伊尔凡·詹·卡赫韦奇', 26, 'FW'),
    ],
    '库拉索': [
        ('Tyrick Bodak', '泰里克·波达克', 1, 'GK'),
        ('Trevor Doornbusch', '特雷弗·杜恩布什', 2, 'GK'),
        ('Eloy Room', '埃洛伊·罗姆', 3, 'GK'),
        ('Riechedly Bazoer', '里奇德利·巴佐尔', 4, 'DF'),
        ('Joshua Brenet', '乔舒亚·布勒内', 5, 'DF'),
        ('Roshon van Eijma', '罗申·范艾玛', 6, 'DF'),
        ('Sherel Floranus', '谢雷尔·弗洛拉努斯', 7, 'DF'),
        ('Deveron Fonville', '德韦伦·丰维尔', 8, 'DF'),
        ('Jurien Gaari', '朱利安·加里', 9, 'DF'),
        ('Armando Obispo', '阿曼多·奥比斯波', 10, 'DF'),
        ('Shurandy Sambo', '舒兰迪·桑博', 11, 'DF'),
        ('Juninho Bacuna', '儒尼尼奥·巴库纳', 12, 'MF'),
        ('Leandro Bacuna', '莱安多·巴库纳', 13, 'MF'),
        ('Livano Comenencia', '利瓦诺·科梅内西亚', 14, 'MF'),
        ('Kevin Felida', '凯文·费利达', 15, 'MF'),
        ('Ar\'Jany Martha', '阿亚尼·马尔塔', 16, 'MF'),
        ('Tyrese Noslin', '泰瑞斯·诺斯林', 17, 'MF'),
        ('Godfried Roemeratoe', '戈德弗里德·罗默拉托', 18, 'MF'),
        ('Jeremy Antonisse', '杰里米·安东尼斯', 19, 'FW'),
        ('Tahith Chong', '陈达毅', 20, 'FW'),
        ('Kenji Gorre', '肯吉·戈雷', 21, 'FW'),
        ('Sontje Hansen', '松切·汉森', 22, 'FW'),
        ('Gervane Kastaneer', '赫尔瓦内·卡斯塔内尔', 23, 'FW'),
        ('Brandley Kuwas', '库沃斯', 24, 'FW'),
        ('Jurgen Locadia', '于尔根·洛卡迪亚', 25, 'FW'),
        ('Jearl Margaritha', '马格里沙', 26, 'FW'),
    ],
    '厄瓜多尔': [
        ('Hernan Galindez', '埃尔南·加林德斯', 1, 'GK'),
        ('Moises Ramirez', '莫伊塞斯·拉米雷斯', 2, 'GK'),
        ('Gonzalo Valle', '贡萨洛·巴列', 3, 'GK'),
        ('Piero Hincapie', '皮耶罗·因卡皮耶', 4, 'DF'),
        ('Willian Pacho', '威廉·帕乔', 5, 'DF'),
        ('Pervis Estupinan', '佩维斯·埃斯图皮南', 6, 'DF'),
        ('Felix Torres', '费利克斯·托雷斯', 7, 'DF'),
        ('Joel Ordonez', '霍埃尔·奥多涅斯', 8, 'DF'),
        ('Jackson Porozo', '杰克逊·波罗佐', 9, 'DF'),
        ('Angelo Preciado', '安赫洛·普雷西亚多', 10, 'DF'),
        ('Moises Caicedo', '莫伊塞斯·凯塞多', 11, 'MF'),
        ('Alan Franco', '阿兰·弗兰科', 12, 'MF'),
        ('Kendry Paez', '肯德里·派斯', 13, 'MF'),
        ('Pedro Vite', '佩德罗·维特', 14, 'MF'),
        ('Jordy Alcivar', '霍尔迪·阿尔西瓦尔', 15, 'MF'),
        ('Denil Castillo', '德尼尔·卡斯蒂略', 16, 'MF'),
        ('Yaimar Medina', '亚伊马尔·梅迪纳', 17, 'MF'),
        ('Enner Valencia', '恩纳·瓦伦西亚', 18, 'FW'),
        ('Kevin Rodriguez', '凯文·罗德里格斯', 19, 'FW'),
        ('Jordy Caicedo', '霍尔迪·凯塞多', 20, 'FW'),
        ('Nilson Angulo', '尼尔松·安古洛', 21, 'FW'),
        ('Anthony Valencia', '安东尼·巴伦西亚', 22, 'FW'),
        ('Jeremy Arevalo', '杰雷米·阿雷瓦洛', 23, 'FW'),
    ],
    '德国': [
        ('Oliver Baumann', '奥利弗·鲍曼', 1, 'GK'),
        ('Manuel Neuer', '曼努埃尔·诺伊尔', 2, 'GK'),
        ('Alexander Nubel', '亚历山大·努贝尔', 3, 'GK'),
        ('Waldemar Anton', '瓦尔德马·安东', 4, 'DF'),
        ('Nathaniel Brown', '纳撒尼尔·布朗', 5, 'DF'),
        ('David Raum', '大卫·劳姆', 6, 'DF'),
        ('Antonio Rudiger', '安东尼奥·吕迪格', 7, 'DF'),
        ('Nico Schlotterbeck', '尼科·施洛特贝克', 8, 'DF'),
        ('Jonathan Tah', '约纳坦·塔', 9, 'DF'),
        ('Malick Thiaw', '马利克·蒂亚夫', 10, 'DF'),
        ('Pascal Gross', '帕斯卡尔·格罗斯', 11, 'MF'),
        ('Joshua Kimmich', '约书亚·基米希', 12, 'MF'),
        ('Felix Nmecha', '费利克斯·恩梅查', 13, 'MF'),
        ('Aleksandar Pavlovic', '亚历山大·帕夫洛维奇', 14, 'MF'),
        ('Angelo Stiller', '安杰洛·施蒂勒', 15, 'MF'),
        ('Leon Goretzka', '莱昂·格雷茨卡', 16, 'MF'),
        ('Florian Wirtz', '弗洛里安·维尔茨', 17, 'MF'),
        ('Jamie Leweling', '杰米·勒韦林', 18, 'MF'),
        ('Maximilian Beier', '马克西米利安·拜尔', 19, 'FW'),
        ('Kai Havertz', '凯·哈弗茨', 20, 'FW'),
        ('Lennart Karl', '伦纳特·卡尔', 21, 'FW'),
        ('Jamal Musiala', '贾马尔·穆西亚拉', 22, 'FW'),
        ('Leroy Sane', '勒鲁瓦·萨内', 23, 'FW'),
        ('Deniz Undav', '德尼兹·翁达夫', 24, 'FW'),
        ('Nick Woltemade', '尼克·沃尔特马德', 25, 'FW'),
    ],
    '科特迪瓦': [
        ('Yahia Fofana', '叶海亚·福法纳', 1, 'GK'),
        ('Mohamed Kone', '穆罕默德·科内', 2, 'GK'),
        ('Alban Lafont', '阿尔邦·拉丰', 3, 'GK'),
        ('Emmanuel Agbadou', '埃马纽埃尔·阿格巴杜', 4, 'DF'),
        ('Clement Akpa', '克莱门特·阿克帕', 5, 'DF'),
        ('Ousmane Diomande', '奥斯曼·迪奥曼德', 6, 'DF'),
        ('Guela Doue', '盖拉·杜埃', 7, 'DF'),
        ('Ghislain Konan', '吉兰·科南', 8, 'DF'),
        ('Odilon Kossounou', '奥迪隆·科索努', 9, 'DF'),
        ('Evan Ndicka', '埃万·恩迪卡', 10, 'DF'),
        ('Wilfried Singo', '威尔弗里德·辛戈', 11, 'DF'),
        ('Seko Fofana', '塞科·福法纳', 12, 'MF'),
        ('Parfait Guiagon', '帕尔费·吉亚贡', 13, 'MF'),
        ('Christ Inao Oulai', '克里斯特·乌拉伊', 14, 'MF'),
        ('Franck Kessie', '凯西', 15, 'MF'),
        ('Ibrahim Sangare', '易卜拉欣·桑加雷', 16, 'MF'),
        ('Jean-Michael Seri', '塞里', 17, 'MF'),
        ('Simon Adingra', '西蒙·阿丁格拉', 18, 'FW'),
        ('Ange-Yoan Bonny', '博尼', 19, 'FW'),
        ('Amad Diallo', '阿玛德·迪亚洛', 20, 'FW'),
        ('Oumar Diakite', '奥马尔·迪亚基特', 21, 'FW'),
        ('Yan Diomande', '扬·迪奥曼德', 22, 'FW'),
        ('Evann Guessand', '埃万·盖桑', 23, 'FW'),
        ('Nicolas Pepe', '尼古拉·佩佩', 24, 'FW'),
        ('Bazoumana Toure', '巴祖马纳·图雷', 25, 'FW'),
        ('Elye Wahi', '瓦希', 26, 'FW'),
    ],
    '荷兰': [
        ('Bart Verbruggen', '巴尔特·费布鲁亨', 1, 'GK'),
        ('Mark Flekken', '马克·弗莱肯', 2, 'GK'),
        ('Robin Roefs', '罗宾·鲁夫斯', 3, 'GK'),
        ('Virgil van Dijk', '菲尔吉尔·范戴克', 4, 'DF'),
        ('Jan Paul van Hecke', '扬·保尔·范赫克', 5, 'DF'),
        ('Nathan Ake', '内森·阿克', 6, 'DF'),
        ('Micky van de Ven', '米基·范德文', 7, 'DF'),
        ('Denzel Dumfries', '丹泽尔·邓弗里斯', 8, 'DF'),
        ('Jorrel Hato', '乔雷尔·哈托', 9, 'DF'),
        ('Jurrien Timber', '尤里恩·廷贝尔', 10, 'DF'),
        ('Frenkie de Jong', '弗朗基·德容', 11, 'MF'),
        ('Tijjani Reijnders', '泰贾尼·赖因德斯', 12, 'MF'),
        ('Justin Kluivert', '贾斯汀·克鲁伊维特', 13, 'MF'),
        ('Quinten Timber', '昆滕·廷贝尔', 14, 'MF'),
        ('Teun Koopmeiners', '特恩·库普梅纳斯', 15, 'MF'),
        ('Ryan Gravenberch', '瑞安·赫拉芬贝赫', 16, 'MF'),
        ('Marten de Roon', '马滕·德鲁恩', 17, 'MF'),
        ('Guus Til', '赫斯·蒂尔', 18, 'MF'),
        ('Mats Weiffer', '马茨·维弗', 19, 'MF'),
        ('Cody Gakpo', '科迪·加克波', 20, 'FW'),
        ('Donyell Malen', '唐耶尔·马伦', 21, 'FW'),
        ('Brian Brobbey', '布里安·布罗比', 22, 'FW'),
        ('Noa Lang', '诺阿·朗', 23, 'FW'),
        ('Memphis Depay', '孟菲斯·德佩', 24, 'FW'),
        ('Wout Weghorst', '沃特·韦格霍斯特', 25, 'FW'),
        ('Crysencio Summerville', '克里森西奥·萨默维尔', 26, 'FW'),
    ],
    '日本': [
        ('Tomoki Hayakawa', '早川友基', 1, 'GK'),
        ('Keisuke Osako', '大迫敬介', 2, 'GK'),
        ('Zion Suzuki', '铃木彩艳', 3, 'GK'),
        ('Yuto Nagatomo', '长友佑都', 4, 'DF'),
        ('Shogo Taniguchi', '谷口彰悟', 5, 'DF'),
        ('Ko Itakura', '板仓滉', 6, 'DF'),
        ('Tsuyoshi Watanabe', '渡边刚', 7, 'DF'),
        ('Takehiro Tomiyasu', '富安健洋', 8, 'DF'),
        ('Hiroki Ito', '伊藤洋辉', 9, 'DF'),
        ('Ayumu Seko', '濑古步梦', 10, 'DF'),
        ('Yukinari Sugawara', '菅原由势', 11, 'DF'),
        ('Junosuke Suzuki', '铃木淳之介', 12, 'DF'),
        ('Wataru Endo', '远藤航', 13, 'MF'),
        ('Junya Ito', '伊东纯也', 14, 'MF'),
        ('Daichi Kamada', '镰田大地', 15, 'MF'),
        ('Koki Ogawa', '小川航基', 16, 'MF'),
        ('Daizen Maeda', '前田大然', 17, 'MF'),
        ('Ritsu Doan', '堂安律', 18, 'MF'),
        ('Ao Tanaka', '田中碧', 19, 'MF'),
        ('Kaishu Sano', '佐野海舟', 20, 'MF'),
        ('Takefusa Kubo', '久保建英', 21, 'MF'),
        ('Ayase Ueda', '上田绮世', 22, 'FW'),
        ('Keito Nakamura', '中村敬斗', 23, 'FW'),
        ('Ito Suzuki', '铃木唯人', 24, 'FW'),
        ('Kento Shiode', '盐贝健人', 25, 'FW'),
        ('Keisuke Goto', '后藤启介', 26, 'FW'),
    ],
    '瑞典': [
        ('Viktor Johansson', '维克托·约翰松', 1, 'GK'),
        ('Kristoffer Nordfeldt', '克里斯托弗·诺德费尔特', 2, 'GK'),
        ('Jacob Widell Zetterstrom', '雅各布·维德尔·塞特斯特伦', 3, 'GK'),
        ('Hjalmar Ekdal', '亚尔马·埃克达尔', 4, 'DF'),
        ('Gabriel Gudmundsson', '加布里埃尔·古德蒙德松', 5, 'DF'),
        ('Isak Hien', '伊萨克·希恩', 6, 'DF'),
        ('Emil Holm', '埃米尔·霍尔姆', 7, 'DF'),
        ('Gustaf Lagerbielke', '古斯塔夫·拉格比尔克', 8, 'DF'),
        ('Victor Lindelof', '维克托·林德洛夫', 9, 'DF'),
        ('Erik Smith', '埃里克·史密斯', 10, 'DF'),
        ('Carl Starfelt', '卡尔·斯塔费尔特', 11, 'DF'),
        ('Elliot Stroud', '埃利奥特·斯特劳德', 12, 'DF'),
        ('Daniel Svensson', '丹尼尔·斯文松', 13, 'DF'),
        ('Taha Ali', '塔哈·阿里', 14, 'MF'),
        ('Yasin Ayari', '亚辛·阿亚里', 15, 'MF'),
        ('Lucas Bergvall', '卢卡斯·贝里瓦尔', 16, 'MF'),
        ('Jesper Karlstrom', '耶斯佩尔·卡尔斯特伦', 17, 'MF'),
        ('Ken Sema', '肯·塞马', 18, 'MF'),
        ('Mattias Svanberg', '马蒂亚斯·斯万贝里', 19, 'MF'),
        ('Besfort Zeneli', '贝斯福特·泽内利', 20, 'MF'),
        ('Alexander Bernhardsson', '亚历山大·伯恩哈德松', 21, 'FW'),
        ('Anthony Elanga', '安东尼·埃兰加', 22, 'FW'),
        ('Viktor Gyokeres', '维克托·约克雷斯', 23, 'FW'),
        ('Alexander Isak', '亚历山大·伊萨克', 24, 'FW'),
        ('Gustaf Nilsson', '古斯塔夫·尼尔松', 25, 'FW'),
        ('Benjamin Nygren', '本亚明·尼格伦', 26, 'FW'),
    ],
    '突尼斯': [
        ('Sabri Ben Hessen', '萨布里·本·黑森', 1, 'GK'),
        ('Abdelmouhib Chamakh', '阿卜杜勒穆希布·沙马克', 2, 'GK'),
        ('Aymen Dahman', '艾曼·达门', 3, 'GK'),
        ('Ali Abdi', '阿里·阿布迪', 4, 'DF'),
        ('Adem Arous', '阿代姆·阿鲁斯', 5, 'DF'),
        ('Mohamed Amine Ben Hamida', '穆罕默德·阿明·本·哈米达', 6, 'DF'),
        ('Dylan Bronn', '迪兰·布隆', 7, 'DF'),
        ('Raed Chikhaoui', '拉埃德·奇卡维', 8, 'DF'),
        ('Moutaz Neffati', '穆塔兹·内法蒂', 9, 'DF'),
        ('Omar Rekik', '奥马尔·雷基克', 10, 'DF'),
        ('Montassar Talbi', '蒙塔萨尔·塔尔比', 11, 'DF'),
        ('Yan Valery', '扬·瓦莱里', 12, 'DF'),
        ('Mortadha Ben Ouanes', '穆尔塔达·本·瓦尼斯', 13, 'MF'),
        ('Anis Ben Slimane', '阿尼斯·本·斯利曼', 14, 'MF'),
        ('Ismael Gharbi', '伊斯梅尔·加尔比', 15, 'MF'),
        ('Rani Khedira', '拉尼·赫迪拉', 16, 'MF'),
        ('Mohamed Hadj Mahmoud', '穆罕默德·哈吉·马穆德', 17, 'MF'),
        ('Hannibal Mejbri', '汉尼拔·梅布里', 18, 'MF'),
        ('Ellyes Skhiri', '埃利亚斯·斯希里', 19, 'MF'),
        ('Elias Achouri', '埃利亚斯·阿乔里', 20, 'FW'),
        ('Khalil Ayari', '哈利勒·阿亚里', 21, 'FW'),
        ('Firas Chaouat', '菲拉斯·沙瓦特', 22, 'FW'),
        ('Rayan Elloumi', '拉扬·埃卢米', 23, 'FW'),
        ('Hazem Mastouri', '哈齐姆·马斯图里', 24, 'FW'),
        ('Elias Saad', '埃利亚斯·萨德', 25, 'FW'),
        ('Sebastian Tounekti', '塞巴斯蒂安·图内克蒂', 26, 'FW'),
    ],
    '比利时': [
        ('Thibaut Courtois', '蒂博·库尔图瓦', 1, 'GK'),
        ('Senne Lammens', '森内·拉门斯', 2, 'GK'),
        ('Mike Penders', '迈克·彭德斯', 3, 'GK'),
        ('Timothy Castagne', '蒂莫西·卡斯塔涅', 4, 'DF'),
        ('Zeno Debast', '泽诺·德巴斯特', 5, 'DF'),
        ('Maxim De Cuyper', '马克西姆·德克伊珀', 6, 'DF'),
        ('Koni De Winter', '科尼·德温特', 7, 'DF'),
        ('Brandon Mechele', '布兰登·梅赫莱', 8, 'DF'),
        ('Thomas Meunier', '托马斯·默尼耶', 9, 'DF'),
        ('Nathan Ngoy', '内森·恩戈伊', 10, 'DF'),
        ('Joaquin Seys', '华金·塞斯', 11, 'DF'),
        ('Arthur Theate', '阿蒂尔·蒂特', 12, 'DF'),
        ('Kevin De Bruyne', '凯文·德布劳内', 13, 'MF'),
        ('Amadou Onana', '阿马杜·奥纳纳', 14, 'MF'),
        ('Nicolas Raskin', '尼古拉·拉斯金', 15, 'MF'),
        ('Youri Tielemans', '尤里·蒂勒曼斯', 16, 'MF'),
        ('Hans Vanaken', '汉斯·瓦纳肯', 17, 'MF'),
        ('Axel Witsel', '阿克塞尔·维采尔', 18, 'MF'),
        ('Charles De Ketelaere', '查尔斯·德凯特拉雷', 19, 'FW'),
        ('Jeremy Doku', '杰雷米·多库', 20, 'FW'),
        ('Matias Fernandez-Pardo', '马蒂亚斯·费尔南德斯-帕尔多', 21, 'FW'),
        ('Romelu Lukaku', '罗梅卢·卢卡库', 22, 'FW'),
        ('Dodi Lukebakio', '多迪·卢克巴吉奥', 23, 'FW'),
        ('Diego Moreira', '迭戈·莫雷拉', 24, 'FW'),
        ('Alexis Saelemaekers', '亚历克西斯·萨勒马克尔斯', 25, 'FW'),
        ('Leandro Trossard', '莱安德罗·特罗萨德', 26, 'FW'),
    ],
    '埃及': [
        ('Mohamed El Shenawy', '穆罕默德·埃尔-舍纳维', 1, 'GK'),
        ('Mostafa Shobeir', '穆斯塔法·舒贝尔', 2, 'GK'),
        ('El Mahdi Soliman', '埃尔-马赫迪·苏莱曼', 3, 'GK'),
        ('Mohamed Alaa', '穆罕默德·阿拉', 4, 'GK'),
        ('Mohamed Hany', '穆罕默德·哈尼', 5, 'DF'),
        ('Tarek Alaa', '塔里克·阿拉', 6, 'DF'),
        ('Hamdy Fathy', '哈姆迪·法特希', 7, 'DF'),
        ('Rami Rabia', '拉米·拉比亚', 8, 'DF'),
        ('Yasser Ibrahim', '亚西尔·易卜拉欣', 9, 'DF'),
        ('Hossam Abdelmaguid', '侯赛姆·阿卜杜勒马吉德', 10, 'DF'),
        ('Mohamed Abdelmonemn', '穆罕默德·阿卜杜勒莫奈姆', 11, 'DF'),
        ('Ahmed Fatouh', '艾哈迈德·法图赫', 12, 'DF'),
        ('Karim Hafez', '卡里姆·哈菲兹', 13, 'DF'),
        ('Marwan Ateya', '马尔万·阿提亚', 14, 'MF'),
        ('Mohanad Lasheen', '莫哈纳德·拉欣', 15, 'MF'),
        ('Nabil Emad', '纳比勒·埃马德', 16, 'MF'),
        ('Mahmoud Saber', '马哈茂德·萨比尔', 17, 'MF'),
        ('Ahmed Zizo', '艾哈迈德·齐佐', 18, 'MF'),
        ('Emam Ashour', '伊马姆·阿舒尔', 19, 'MF'),
        ('Mostafa Ziko', '穆斯塔法·齐科', 20, 'MF'),
        ('Mahmoud Trezeguet', '马哈茂德·特雷泽盖', 21, 'MF'),
        ('Ibrahim Adel', '易卜拉欣·阿德尔', 22, 'MF'),
        ('Haissem Hassan', '海瑟姆·哈桑', 23, 'MF'),
        ('Omar Marmoush', '奥马尔·马尔穆什', 24, 'FW'),
        ('Mohamed Salah', '穆罕默德·萨拉赫', 25, 'FW'),
        ('Aqtay Abdallah', '阿卜杜拉·阿卜杜拉', 26, 'FW'),
        ('Hamza Abdelkarim', '哈姆扎·阿卜杜勒卡里姆', 27, 'FW'),
    ],
    '伊朗': [
        ('Alireza Beiranvand', '阿里雷扎·贝兰万德', 1, 'GK'),
        ('Seyed Hossein Hosseini', '赛义德·侯赛因·侯赛尼', 2, 'GK'),
        ('Payam Niazmand', '帕亚姆·尼亚兹曼德', 3, 'GK'),
        ('Danial Eiri', '丹尼尔·埃里', 4, 'DF'),
        ('Ehsan Hajsafi', '埃赫桑·哈吉萨菲', 5, 'DF'),
        ('Saleh Hardani', '萨利赫·哈达尼', 6, 'DF'),
        ('Hossein Kanaani', '侯赛因·卡纳尼', 7, 'DF'),
        ('Shoja Khalilzadeh', '舒贾·哈利勒扎德', 8, 'DF'),
        ('Milad Mohammadi', '米拉德·穆罕默迪', 9, 'DF'),
        ('Ali Nemati', '阿里·内马蒂', 10, 'DF'),
        ('Ramin Rezaeian', '拉明·雷扎伊安', 11, 'DF'),
        ('Rouzbeh Cheshmi', '鲁兹贝·切什米', 12, 'MF'),
        ('Saeid Ezatolahi', '赛义德·埃扎托拉希', 13, 'MF'),
        ('Mehdi Ghaedi', '迈赫迪·加埃迪', 14, 'MF'),
        ('Saman Ghoddos', '萨曼·戈多斯', 15, 'MF'),
        ('Mohammad Ghorbani', '穆罕默德·古尔巴尼', 16, 'MF'),
        ('Alireza Jahanbakhsh', '阿里雷扎·贾汉巴赫什', 17, 'MF'),
        ('Mohammad Mohebi', '穆罕默德·莫赫比', 18, 'MF'),
        ('Amir Mohammad Razzaghinia', '阿米尔·穆罕默德·拉扎吉尼亚', 19, 'MF'),
        ('Mehdi Torabi', '迈赫迪·托拉比', 20, 'MF'),
        ('Aria Yousefi', '阿里亚·尤塞菲', 21, 'MF'),
        ('Ali Alipour', '阿里·阿利普尔', 22, 'FW'),
        ('Dennis Dargahi', '丹尼斯·达尔加希', 23, 'FW'),
        ('Amirhossein Hosseinzadeh', '阿米尔侯赛因·侯赛因扎德', 24, 'FW'),
        ('Mehdi Taremi', '迈赫迪·塔雷米', 25, 'FW'),
        ('Shahriar Moghanlou', '沙赫里亚尔·莫汉卢', 26, 'FW'),
    ],
    '新西兰': [
        ('Max Crocombe', '马克斯·克罗库姆', 1, 'GK'),
        ('Alex Paulsen', '亚历克斯·保尔森', 2, 'GK'),
        ('Michael Woud', '迈克尔·沃德', 3, 'GK'),
        ('Tim Payne', '蒂姆·佩恩', 4, 'DF'),
        ('Francis De Vries', '弗朗西斯·德弗里斯', 5, 'DF'),
        ('Tyler Bindon', '泰勒·宾登', 6, 'DF'),
        ('Michael Boxall', '迈克尔·博克索尔', 7, 'DF'),
        ('Liberato Cacace', '利贝拉托·卡卡切', 8, 'DF'),
        ('Nando Pijnaker', '南多·皮纳克', 9, 'DF'),
        ('Finn Surman', '芬·瑟曼', 10, 'DF'),
        ('Callan Elliot', '卡兰·埃利奥特', 11, 'DF'),
        ('Tommy Smith', '汤米·史密斯', 12, 'DF'),
        ('Joe Bell', '乔·贝尔', 13, 'MF'),
        ('Matt Garbett', '马特·加贝特', 14, 'MF'),
        ('Marko Stamenic', '马尔科·斯塔梅尼奇', 15, 'MF'),
        ('Sarpreet Singh', '萨尔普雷特·辛格', 16, 'MF'),
        ('Alex Rufer', '亚历克斯·鲁费尔', 17, 'MF'),
        ('Ryan Thomas', '瑞安·托马斯', 18, 'MF'),
        ('Chris Wood', '克里斯·伍德', 19, 'FW'),
        ('Eli Just', '伊莱·贾斯特', 20, 'FW'),
        ('Kosta Barbarouses', '科斯塔·巴巴鲁塞斯', 21, 'FW'),
        ('Ben Waine', '本·韦恩', 22, 'FW'),
        ('Ben Old', '本·奥尔德', 23, 'FW'),
        ('Callum McCowatt', '卡勒姆·麦科瓦特', 24, 'FW'),
        ('Jesse Randall', '杰西·兰德尔', 25, 'FW'),
        ('Lachlan Bayliss', '拉克伦·贝利斯', 26, 'FW'),
    ],
    '佛得角': [
        ('Vozinha', '沃津哈', 1, 'GK'),
        ('Marcio Rosa', '马西奥·罗萨', 2, 'GK'),
        ('CJ dos Santos', '卡洛斯·多斯·桑托斯', 3, 'GK'),
        ('Stopira', '托皮拉', 4, 'DF'),
        ('Roberto Lopes', '罗拔图·洛佩兹', 5, 'DF'),
        ('Joao Paulo', '若昂·保罗', 6, 'DF'),
        ('Diney', '迪内', 7, 'DF'),
        ('Logan Costa', '洛根·科斯塔', 8, 'DF'),
        ('Steven Moreira', '史蒂芬·莫雷拉', 9, 'DF'),
        ('Wagner Pina', '瓦格纳·皮纳', 10, 'DF'),
        ('Sidny Lopes Cabral', '西德尼·洛佩斯·卡布拉尔', 11, 'DF'),
        ('Kelvin Pires', '凯尔文·皮雷斯', 12, 'DF'),
        ('Jamiro Monteiro', '杰米罗·蒙特罗', 13, 'MF'),
        ('Kevin Pina', '凯文·皮纳', 14, 'MF'),
        ('Deroy Duarte', '德罗伊·杜亚特', 15, 'MF'),
        ('Telmo Arcanjo', '特尔莫·阿尔坎若', 16, 'MF'),
        ('Laros Duarte', '拉罗斯·杜亚特', 17, 'MF'),
        ('Yannick Semedo', '亚尼克·塞梅多', 18, 'MF'),
        ('Ryan Mendes', '瑞安·门德斯', 19, 'FW'),
        ('Garry Rodrigues', '加里·罗德里格斯', 20, 'FW'),
        ('Willy Semedo', '威利·塞梅多', 21, 'FW'),
        ('Jovane Cabral', '久瓦尼·卡布拉尔', 22, 'FW'),
        ('Gilson Tavares', '吉尔森·塔瓦雷斯', 23, 'FW'),
        ('Dailon Livramento', '戴隆·利夫拉门托', 24, 'FW'),
        ('Helio Varela', '海里奥·瓦雷拉', 25, 'FW'),
        ('Nuno da Costa', '努诺·达科斯塔', 26, 'FW'),
    ],
    '沙特': [
        ('Mohammed Al Owais', '阿洛瓦伊斯', 1, 'GK'),
        ('Nawaf Al Aqidi', '阿奇迪', 2, 'GK'),
        ('Ahmed Al Kassar', '卡萨尔', 3, 'GK'),
        ('Abdulelah Al Amri', '阿姆里', 4, 'DF'),
        ('Hassan Tambakti', '坦巴克蒂', 5, 'DF'),
        ('Jehad Thikri', '塔克里', 6, 'DF'),
        ('Ali Lajami', '拉贾米', 7, 'DF'),
        ('Hassan Kadesh', '卡迪什', 8, 'DF'),
        ('Saud Abdulhamid', '阿卜杜勒哈米德', 9, 'DF'),
        ('Mohammed Abu Al Shamat', '阿布沙马特', 10, 'DF'),
        ('Ali Majrashi', '阿里·马杰拉希', 11, 'DF'),
        ('Moteb Al Harbi', '哈尔比', 12, 'DF'),
        ('Nawaf Boushal', '布沙尔', 13, 'DF'),
        ('Sultan Al-Ghannam', '加纳姆', 14, 'DF'),
        ('Mohammed Kanno', '卡努', 15, 'MF'),
        ('Abdullah Al Khaibari', '哈巴利', 16, 'MF'),
        ('Ziyad Al Johani', '阿尔乔汉尼', 17, 'MF'),
        ('Nasser Al Dawsari', '纳赛尔·多萨里', 18, 'MF'),
        ('Musab Al Juwayr', '朱瓦伊尔', 19, 'MF'),
        ('Alaa Al Hajji', '赫吉', 20, 'MF'),
        ('Salem Al Dawsari', '萨利姆·多萨里', 21, 'MF'),
        ('Khalid Al Ghannam', '哈立德·加纳姆', 22, 'MF'),
        ('Ayman Yahya', '叶海亚', 23, 'MF'),
        ('Firas Al Buraikan', '布赖坎', 24, 'FW'),
        ('Saleh Al Shehri', '谢赫里', 25, 'FW'),
        ('Abdullah Al Hamdan', '哈姆丹', 26, 'FW'),
    ],
    '西班牙': [
        ('Unai Simon', '乌奈·西蒙', 1, 'GK'),
        ('David Raya', '拉亚', 2, 'GK'),
        ('Joan Garcia', '霍安·加西亚', 3, 'GK'),
        ('Aymeric Laporte', '拉波尔特', 4, 'DF'),
        ('Marc Cucurella', '库库雷利亚', 5, 'DF'),
        ('Marcos Llorente', '马科斯·略伦特', 6, 'DF'),
        ('Eric Garcia', '埃里克·加西亚', 7, 'DF'),
        ('Pedro Porro', '波罗', 8, 'DF'),
        ('Alex Grimaldo', '格里马尔多', 9, 'DF'),
        ('Pau Cubarsi', '库巴西', 10, 'DF'),
        ('Marc Pubill', '普维尔', 11, 'DF'),
        ('Rodri', '罗德里', 12, 'MF'),
        ('Fabian Ruiz', '法比安·鲁伊斯', 13, 'MF'),
        ('Mikel Merino', '梅里诺', 14, 'MF'),
        ('Pedri', '佩德里', 15, 'MF'),
        ('Gavi', '加维', 16, 'MF'),
        ('Martin Zubimendi', '苏比门迪', 17, 'MF'),
        ('Alex Baena', '巴埃纳', 18, 'MF'),
        ('Ferran Torres', '费兰·托雷斯', 19, 'FW'),
        ('Mikel Oyarzabal', '奥亚萨瓦尔', 20, 'FW'),
        ('Dani Olmo', '达尼·奥尔莫', 21, 'FW'),
        ('Nico Williams', '尼科·威廉姆斯', 22, 'FW'),
        ('Lamine Yamal', '亚马尔', 23, 'FW'),
        ('Yeremy Pino', '皮诺', 24, 'FW'),
        ('Borja Iglesias', '伊格莱西亚斯', 25, 'FW'),
        ('Victor Munoz', '穆尼奥斯', 26, 'FW'),
    ],
    '乌拉圭': [
        ('Sergio Rochet', '塞尔吉奥·罗切特', 1, 'GK'),
        ('Fernando Muslera', '费尔南多·穆斯莱拉', 2, 'GK'),
        ('Santiago Mele', '圣地亚哥·梅莱', 3, 'GK'),
        ('Guillermo Varela', '吉列尔莫·巴雷拉', 4, 'DF'),
        ('Ronald Araujo', '罗纳德·阿劳霍', 5, 'DF'),
        ('Jose Maria Gimenez', '何塞·马里亚·希门尼斯', 6, 'DF'),
        ('Santiago Bueno', '圣地亚哥·布埃诺', 7, 'DF'),
        ('Sebastian Caceres', '塞巴斯蒂安·卡塞雷斯', 8, 'DF'),
        ('Mathias Olivera', '马蒂亚斯·奥利韦拉', 9, 'DF'),
        ('Joaquin Piquerez', '华金·皮克雷斯', 10, 'DF'),
        ('Matias Vina', '马蒂亚斯·比尼亚', 11, 'DF'),
        ('Juan Manuel Sanabria', '胡安·曼努埃尔·萨纳夫里亚', 12, 'DF'),
        ('Manuel Ugarte', '曼努埃尔·乌加特', 13, 'MF'),
        ('Emiliano Martinez', '埃米利亚诺·马丁内斯', 14, 'MF'),
        ('Rodrigo Bentancur', '罗德里戈·本坦库尔', 15, 'MF'),
        ('Federico Valverde', '费德里科·巴尔韦德', 16, 'MF'),
        ('Agustin Canobbio', '阿古斯丁·卡诺比奥', 17, 'MF'),
        ('Giorgian de Arrascaeta', '乔治安·德阿拉斯卡埃塔', 18, 'MF'),
        ('Nicolas de la Cruz', '尼古拉斯·德拉克鲁斯', 19, 'MF'),
        ('Facundo Pellistri', '法昆多·佩利斯特里', 20, 'MF'),
        ('Rodrigo Zalazar', '罗德里戈·萨拉查', 21, 'MF'),
        ('Maxi Araujo', '马克西·阿劳霍', 22, 'MF'),
        ('Brian Rodriguez', '布里安·罗德里格斯', 23, 'MF'),
        ('Rodrigo Aguirre', '罗德里戈·阿吉雷', 24, 'FW'),
        ('Federico Vinas', '费德里科·比尼亚斯', 25, 'FW'),
        ('Darwin Nunez', '达尔文·努涅斯', 26, 'FW'),
    ],
    '法国': [
        ('Mike Maignan', '迈尼昂', 1, 'GK'),
        ('Robin Risser', '里塞', 2, 'GK'),
        ('Brice Samba', '桑巴', 3, 'GK'),
        ('Lucas Digne', '迪涅', 4, 'DF'),
        ('Malo Gusto', '古斯托', 5, 'DF'),
        ('Lucas Hernandez', '卢卡斯·埃尔南德斯', 6, 'DF'),
        ('Theo Hernandez', '特奥', 7, 'DF'),
        ('Ibrahima Konate', '科纳特', 8, 'DF'),
        ('Jules Kounde', '孔德', 9, 'DF'),
        ('Maxence Lacroix', '拉克鲁瓦', 10, 'DF'),
        ('William Saliba', '萨利巴', 11, 'DF'),
        ('Dayot Upamecano', '于帕梅卡诺', 12, 'DF'),
        ('N\'Golo Kante', '恩戈洛·坎特', 13, 'MF'),
        ('Manu Kone', '科内', 14, 'MF'),
        ('Adrien Rabiot', '拉比奥', 15, 'MF'),
        ('Aurelien Tchouameni', '琼阿梅尼', 16, 'MF'),
        ('Warren Zaire-Emery', '扎伊尔·埃梅里', 17, 'MF'),
        ('Maghnes Akliouche', '阿克利乌舍', 18, 'FW'),
        ('Bradley Barcola', '巴尔科拉', 19, 'FW'),
        ('Rayan Cherki', '谢尔基', 20, 'FW'),
        ('Ousmane Dembele', '登贝莱', 21, 'FW'),
        ('Desire Doue', '杜埃', 22, 'FW'),
        ('Jean-Philippe Mateta', '马特塔', 23, 'FW'),
        ('Kylian Mbappe', '姆巴佩', 24, 'FW'),
        ('Michael Olise', '奥利塞', 25, 'FW'),
        ('Marcus Thuram', '图拉姆', 26, 'FW'),
    ],
    '挪威': [
        ('Orjan Haskjold Nyland', '厄尔扬·尼兰', 1, 'GK'),
        ('Egil Selvik', '埃吉尔·塞尔维克', 2, 'GK'),
        ('Sander Tangvik', '桑德尔·唐维克', 3, 'GK'),
        ('Julian Ryerson', '尤利安·吕尔松', 4, 'DF'),
        ('Marcus Holmgren Pedersen', '马库斯·霍尔姆格伦·彼得森', 5, 'DF'),
        ('David Moller Wolfe', '大卫·莫勒·沃尔夫', 6, 'DF'),
        ('Fredrik Bjorkan', '弗雷德里克·比约坎', 7, 'DF'),
        ('Kristoffer Ajer', '克里斯托弗·阿耶尔', 8, 'DF'),
        ('Torbjorn Heggem', '托尔比约恩·赫格姆', 9, 'DF'),
        ('Leo Skiri Ostigard', '莱奥·厄斯蒂高', 10, 'DF'),
        ('Sondre Langas', '松德雷·兰加斯', 11, 'DF'),
        ('Henrik Falchener', '亨里克·法尔希纳', 12, 'DF'),
        ('Martin Odegaard', '马丁·厄德高', 13, 'MF'),
        ('Sander Berge', '桑德尔·贝格', 14, 'MF'),
        ('Fredrik Aursnes', '弗雷德里克·奥尔斯内斯', 15, 'MF'),
        ('Patrick Berg', '帕特里克·贝格', 16, 'MF'),
        ('Kristian Thorstvedt', '克里斯蒂安·索尔斯维特', 17, 'MF'),
        ('Morten Thorsby', '莫滕·索尔比', 18, 'MF'),
        ('Thelo Aasgaard', '塞洛·奥斯加德', 19, 'MF'),
        ('Erling Haaland', '埃尔林·哈兰德', 20, 'FW'),
        ('Alexander Sorloth', '亚历山大·瑟尔洛特', 21, 'FW'),
        ('Jorgen Strand Larsen', '约尔根·斯特兰德·拉森', 22, 'FW'),
        ('Antonio Nusa', '安东尼奥·努萨', 23, 'FW'),
        ('Oscar Bobb', '奥斯卡·鲍勃', 24, 'FW'),
        ('Andreas Schjelderup', '安德烈亚斯·谢尔德鲁普', 25, 'FW'),
        ('Jens Petter Hauge', '延斯·彼得·豪格', 26, 'FW'),
    ],
    '塞内加尔': [
        ('Edouard Mendy', '爱德华·门迪', 1, 'GK'),
        ('Mory Diaw', '莫里·迪亚乌', 2, 'GK'),
        ('Yehvann Diouf', '耶万·迪乌夫', 3, 'GK'),
        ('Krepin Diatta', '克雷平·迪亚塔', 4, 'DF'),
        ('Antoine Mendy', '安托万·门迪', 5, 'DF'),
        ('Kalidou Koulibaly', '卡利杜·库利巴利', 6, 'DF'),
        ('El Hadji Malick Diouf', '埃尔-哈吉·马利克·迪乌夫', 7, 'DF'),
        ('Mamadou Sarr', '马马杜·萨尔', 8, 'DF'),
        ('Moussa Niakhate', '穆萨·尼亚卡特', 9, 'DF'),
        ('Moustapha Mbow', '穆斯塔法·姆博乌', 10, 'DF'),
        ('Abdoulaye Seck', '阿卜杜拉耶·塞克', 11, 'DF'),
        ('Ismail Jakobs', '伊斯梅尔·雅各布斯', 12, 'DF'),
        ('Ilay Camara', '伊莱·卡马拉', 13, 'DF'),
        ('Idrissa Gana Gueye', '伊德里萨·盖耶', 14, 'MF'),
        ('Pape Gueye', '帕普·盖耶', 15, 'MF'),
        ('Lamine Camara', '拉明·卡马拉', 16, 'MF'),
        ('Habib Diarra', '哈比卜·迪亚拉', 17, 'MF'),
        ('Pathe Ciss', '帕特·西斯', 18, 'MF'),
        ('Pape Matar Sarr', '帕普·马塔尔·萨尔', 19, 'MF'),
        ('Bara Sapoko Ndiaye', '巴拉·恩迪亚耶', 20, 'MF'),
        ('Sadio Mane', '萨迪奥·马内', 21, 'FW'),
        ('Ismaila Sarr', '伊斯梅拉·萨尔', 22, 'FW'),
        ('Iliman Ndiaye', '伊利曼·恩迪亚耶', 23, 'FW'),
        ('Assane Diao', '阿桑·迪奥', 24, 'FW'),
        ('Ibrahim Mbaye', '易卜拉欣·姆巴耶', 25, 'FW'),
        ('Nicolas Jackson', '尼古拉斯·杰克逊', 26, 'FW'),
        ('Bamba Dieng', '班巴·迪昂', 27, 'FW'),
        ('Cherif Ndiaye', '谢里夫·恩迪亚耶', 28, 'FW'),
    ],
    '伊拉克': [
        ('Fahad Talib', '法哈德·塔利卜', 1, 'GK'),
        ('Jalal Hassan', '贾拉尔·哈桑', 2, 'GK'),
        ('Ahmed Basil', '艾哈迈德·巴西勒', 3, 'GK'),
        ('Hussein Ali', '侯赛因·阿里', 4, 'DF'),
        ('Mustafa Saadoon', '穆斯塔法·萨登', 5, 'DF'),
        ('Zaid Tahseen', '扎伊德·塔辛', 6, 'DF'),
        ('Rebin Sulaka', '雷宾·苏拉卡', 7, 'DF'),
        ('Akam Hashim', '阿卡姆·哈希姆', 8, 'DF'),
        ('Merchas Doski', '梅赫加斯·多斯基', 9, 'DF'),
        ('Zaid Ismail', '扎伊德·伊斯梅尔', 10, 'DF'),
        ('Frans Putros', '弗兰斯·普特罗斯', 11, 'DF'),
        ('Amir Al-Ammari', '阿米尔·阿玛里', 12, 'MF'),
        ('Kevin Yakob', '凯文·雅各布', 13, 'MF'),
        ('Zidane Iqbal', '齐达内·伊克巴尔', 14, 'MF'),
        ('Aimar Sher', '艾马尔·谢尔', 15, 'MF'),
        ('Ibrahim Bayesh', '易卜拉欣·拜阿什', 16, 'MF'),
        ('Ahmed Qasem', '艾哈迈德·卡塞姆', 17, 'MF'),
        ('Youssef Amyn', '优素福·阿明', 18, 'MF'),
        ('Marko Farji', '马科·法吉', 19, 'MF'),
        ('Ali Jassim', '阿里·贾西姆', 20, 'FW'),
        ('Ali Al-Hamadi', '阿里·阿尔哈马迪', 21, 'FW'),
        ('Ali Yousef', '阿里·优素福', 22, 'FW'),
        ('Aymen Hussein', '埃曼·侯赛因', 23, 'FW'),
        ('Mohanad Ali', '莫哈纳德·阿里', 24, 'FW'),
    ],
    '阿尔及利亚': [
        ('Luca Zidane', '卢卡·齐达内', 1, 'GK'),
        ('Oussama Benbot', '乌萨马·本博特', 2, 'GK'),
        ('Melvin Mastil', '梅尔文·马斯蒂尔', 3, 'GK'),
        ('Aissa Mandi', '艾萨·曼迪', 4, 'DF'),
        ('Ramy Bensebaini', '拉米·本塞拜尼', 5, 'DF'),
        ('Mohamed Amine Tougai', '穆罕默德·阿明·图盖', 6, 'DF'),
        ('Rayan Ait-Nouri', '拉扬·艾特-努里', 7, 'DF'),
        ('Jaouen Hadjam', '贾温·哈贾姆', 8, 'DF'),
        ('Rafik Belghali', '拉菲克·贝尔加利', 9, 'DF'),
        ('Zineddine Belaid', '齐内丁·贝莱德', 10, 'DF'),
        ('Achref Abada', '阿什拉夫·阿巴达', 11, 'DF'),
        ('Samir Chergui', '萨米尔·谢尔吉', 12, 'DF'),
        ('Nabil Bentaleb', '纳比勒·本塔莱卜', 13, 'MF'),
        ('Ramiz Zerrouki', '拉米兹·泽鲁基', 14, 'MF'),
        ('Hicham Boudaoui', '希沙姆·布达维', 15, 'MF'),
        ('Fares Chaibi', '法雷斯·沙伊比', 16, 'MF'),
        ('Houssem Aouar', '侯塞姆·奥瓦尔', 17, 'MF'),
        ('Ibrahim Maza', '易卜拉欣·马扎', 18, 'MF'),
        ('Yacine Titraoui', '亚辛·蒂特拉维', 19, 'MF'),
        ('Riyad Mahrez', '里亚德·马赫雷斯', 20, 'FW'),
        ('Mohamed Amoura', '穆罕默德·阿穆拉', 21, 'FW'),
        ('Amine Gouiri', '阿明·古伊里', 22, 'FW'),
        ('Anis Hadj Moussa', '阿尼斯·哈吉·穆萨', 23, 'FW'),
        ('Adil Boulbina', '阿迪勒·布尔比纳', 24, 'FW'),
        ('Nadhir Benbouali', '纳迪尔·本布阿利', 25, 'FW'),
        ('Fares Ghedjemis', '法雷斯·盖杰米斯', 26, 'FW'),
    ],
    '阿根廷': [
        ('Emiliano Martinez', '埃米利亚诺·马丁内斯', 1, 'GK'),
        ('Juan Musso', '胡安·穆索', 2, 'GK'),
        ('Geronimo Rulli', '赫罗尼莫·鲁利', 3, 'GK'),
        ('Leonardo Balerdi', '莱昂纳多·巴莱尔迪', 4, 'DF'),
        ('Lisandro Martinez', '利桑德罗·马丁内斯', 5, 'DF'),
        ('Facundo Medina', '法昆多·梅迪纳', 6, 'DF'),
        ('Nahuel Molina', '纳韦尔·莫利纳', 7, 'DF'),
        ('Gonzalo Montiel', '冈萨洛·蒙铁尔', 8, 'DF'),
        ('Nicolas Otamendi', '尼古拉斯·奥塔门迪', 9, 'DF'),
        ('Cristian Romero', '克里斯蒂安·罗梅罗', 10, 'DF'),
        ('Nicolas Tagliafico', '尼古拉斯·塔利亚菲科', 11, 'DF'),
        ('Valentin Barco', '巴伦廷·巴尔科', 12, 'MF'),
        ('Rodrigo De Paul', '罗德里戈·德保罗', 13, 'MF'),
        ('Enzo Fernandez', '恩佐·费尔南德斯', 14, 'MF'),
        ('Giovani Lo Celso', '乔瓦尼·洛塞尔索', 15, 'MF'),
        ('Alexis Mac Allister', '亚历克西斯·麦卡利斯特', 16, 'MF'),
        ('Exequiel Palacios', '埃塞基耶尔·帕拉西奥斯', 17, 'MF'),
        ('Leandro Paredes', '莱安德罗·帕雷德斯', 18, 'MF'),
        ('Thiago Almada', '蒂亚戈·阿尔马达', 19, 'FW'),
        ('Julian Alvarez', '胡利安·阿尔瓦雷斯', 20, 'FW'),
        ('Nicolas Gonzalez', '尼古拉斯·冈萨雷斯', 21, 'FW'),
        ('Jose Manuel Lopez', '何塞·曼努埃尔·洛佩斯', 22, 'FW'),
        ('Lautaro Martinez', '劳塔罗·马丁内斯', 23, 'FW'),
        ('Lionel Messi', '利昂内尔·梅西', 24, 'FW'),
        ('Nicolas Paz', '尼科·帕斯', 25, 'FW'),
        ('Giuliano Simeone', '朱利亚诺·西蒙尼', 26, 'FW'),
    ],
    '奥地利': [
        ('Alexander Schlager', '亚历山大·施拉格', 1, 'GK'),
        ('Florian Wiegele', '弗洛里安·维格勒', 2, 'GK'),
        ('Patrick Pentz', '帕特里克·彭茨', 3, 'GK'),
        ('David Affengruber', '大卫·阿芬格鲁伯', 4, 'DF'),
        ('Kevin Danso', '凯文·丹索', 5, 'DF'),
        ('Stefan Posch', '斯蒂芬·波施', 6, 'DF'),
        ('David Alaba', '大卫·阿拉巴', 7, 'DF'),
        ('Philipp Lienhart', '菲利普·林哈特', 8, 'DF'),
        ('Phillipp Mwene', '菲利普·姆维尼', 9, 'DF'),
        ('Alexander Prass', '亚历山大·普拉斯', 10, 'DF'),
        ('Marco Friedl', '马尔科·弗里德尔', 11, 'DF'),
        ('Michael Svoboda', '米夏埃尔·斯沃博达', 12, 'DF'),
        ('Xaver Schlager', '泽弗尔·施拉格', 13, 'MF'),
        ('Nicolas Seiwald', '尼古拉斯·塞沃尔德', 14, 'MF'),
        ('Marcel Sabitzer', '萨比策', 15, 'MF'),
        ('Florian Grillitsch', '弗洛里安·格里利奇', 16, 'MF'),
        ('Carney Chukwuemeka', '卡尔尼·丘库埃梅卡', 17, 'MF'),
        ('Romano Schmid', '罗马诺·施密德', 18, 'MF'),
        ('Christoph Baumgartner', '克里斯托弗·鲍姆加特纳', 19, 'MF'),
        ('Konrad Laimer', '康拉德·莱默', 20, 'MF'),
        ('Patrick Wimmer', '帕特里克·维默尔', 21, 'MF'),
        ('Paul Wanner', '保尔·万纳尔', 22, 'MF'),
        ('Alessandro Schopf', '阿里桑德罗·舍普夫', 23, 'MF'),
        ('Marko Arnautovic', '马尔科·阿瑙托维奇', 24, 'FW'),
        ('Michael Gregoritsch', '米歇尔·格雷戈里施', 25, 'FW'),
        ('Sasa Kalajdzic', '萨萨·卡拉季奇', 26, 'FW'),
    ],
    '约旦': [
        ('Yazeed Abulaila', '亚奇德', 1, 'GK'),
        ('Abdallah Al-Fakhouri', '法霍里', 2, 'GK'),
        ('Nour Bani Attiah', '努雷丁·扎伊德', 3, 'GK'),
        ('Ihsan Haddad', '伊赫桑·哈达德', 4, 'DF'),
        ('Yazan Al-Arab', '亚赞·阿拉伯', 5, 'DF'),
        ('Abdallah Nasib', '纳西布', 6, 'DF'),
        ('Mohammad Abu Hashish', '阿布·哈西什', 7, 'DF'),
        ('Saed Al-Rosan', '赛义德·罗桑', 8, 'DF'),
        ('Husam Abu Dahab', '胡萨姆·阿布·达哈布', 9, 'DF'),
        ('Mo Abualnadi', '阿布拉纳迪', 10, 'DF'),
        ('Salim Obaid', '萨利姆·奥贝德', 11, 'DF'),
        ('Anas Badawi', '巴达维', 12, 'DF'),
        ('Rajaei Ayed', '拉杰伊·阿耶德', 13, 'MF'),
        ('Noor Al-Rawabdeh', '拉瓦德赫', 14, 'MF'),
        ('Ibrahim Sadeh', '易卜拉欣·萨德', 15, 'MF'),
        ('Nizar Al-Rashdan', '尼扎尔', 16, 'MF'),
        ('Mohannad Abu Taha', '阿布·塔哈', 17, 'MF'),
        ('Amer Jamous', '阿米尔·贾穆斯', 18, 'MF'),
        ('Mohammad Al-Dawoud', '穆罕默德·达伍德', 19, 'MF'),
        ('Musa Al-Taamari', '塔马里', 20, 'FW'),
        ('Mahmoud Al-Mardi', '马哈穆德·马尔迪', 21, 'FW'),
        ('Ali Olwan', '阿里·奥尔万', 22, 'FW'),
        ('Mohammad Abu Zrayq', '阿布·兹雷克', 23, 'FW'),
        ('Odeh Al-Fakhouri', '法胡里', 24, 'FW'),
        ('Ibrahim Sabra', '易卜拉欣·萨布拉', 25, 'FW'),
        ('Ali Azaizeh', '阿扎伊泽', 26, 'FW'),
    ],
    '哥伦比亚': [
        ('Camilo Vargas', '卡米洛·巴尔加斯', 1, 'GK'),
        ('Alvaro Montero', '阿尔瓦罗·蒙特罗', 2, 'GK'),
        ('David Ospina', '大卫·奥斯皮纳', 3, 'GK'),
        ('Davinson Sanchez', '达温松·桑切斯', 4, 'DF'),
        ('Jhon Lucumi', '约翰·卢库米', 5, 'DF'),
        ('Yerry Mina', '耶里·米纳', 6, 'DF'),
        ('Willer Ditta', '维勒·迪塔', 7, 'DF'),
        ('Daniel Munoz', '丹尼尔·穆尼奥斯', 8, 'DF'),
        ('Santiago Arias', '圣地亚哥·阿里亚斯', 9, 'DF'),
        ('Johan Mojica', '约翰·莫希卡', 10, 'DF'),
        ('Deiver Machado', '德伊弗·马查多', 11, 'DF'),
        ('Richard Rios', '里查德·里奥斯', 12, 'MF'),
        ('Jefferson Lerma', '杰弗森·莱尔马', 13, 'MF'),
        ('Kevin Castano', '凯文·卡斯塔尼奥', 14, 'MF'),
        ('Juan Camilo Portilla', '胡安·卡米洛·波蒂利亚', 15, 'MF'),
        ('Gustavo Puerta', '古斯塔沃·普埃尔塔', 16, 'MF'),
        ('Jhon Arias', '约翰·阿里亚斯', 17, 'MF'),
        ('Jorge Carrascal', '豪尔赫·卡拉斯卡尔', 18, 'MF'),
        ('Juan Fernando Quintero', '胡安·费尔南多·金特罗', 19, 'MF'),
        ('James Rodriguez', '哈梅斯·罗德里格斯', 20, 'MF'),
        ('Jaminton Campaz', '哈明顿·坎帕斯', 21, 'MF'),
        ('Juan Camilo Hernandez', '胡安·卡米洛·埃尔南德斯', 22, 'FW'),
        ('Luis Diaz', '路易斯·迪亚斯', 23, 'FW'),
        ('Luis Suarez', '路易斯·苏亚雷斯', 24, 'FW'),
        ('Carlos Andres Gomez', '卡洛斯·安德烈斯·戈麦斯', 25, 'FW'),
        ('Jhon Cordoba', '约翰·科尔多瓦', 26, 'FW'),
    ],
    '刚果（金）': [
        ('Matthieu Epolo', '马修·恩波洛', 1, 'GK'),
        ('Timothy Fayulu', '蒂莫西·法尤鲁', 2, 'GK'),
        ('Lionel Mpasi', '莱昂内尔·姆帕西', 3, 'GK'),
        ('Dylan Batubinsika', '迪朗·巴蒂班西卡', 4, 'DF'),
        ('Rocky Bushiri', '洛基·布希里', 5, 'DF'),
        ('Gedeon Kalulu', '热迪翁·卡卢卢', 6, 'DF'),
        ('Steve Kapuadi', '史蒂夫·卡普阿迪', 7, 'DF'),
        ('Joris Kayembe', '乔里斯·卡耶姆贝', 8, 'DF'),
        ('Arthur Masuaku', '亚瑟·马苏亚库', 9, 'DF'),
        ('Chancel Mbemba', '查塞尔·姆本巴', 10, 'DF'),
        ('Axel Tuanzebe', '阿克塞尔·图安泽贝', 11, 'DF'),
        ('Aaron Wan-Bissaka', '万-比萨卡', 12, 'DF'),
        ('Theo Bongonda', '蒂奥·博格纳达', 13, 'MF'),
        ('Brian Cipenga', '布莱恩·齐蓬加', 14, 'MF'),
        ('Meshack Elia', '梅沙克·埃利亚', 15, 'MF'),
        ('Gael Kakuta', '盖尔·卡库塔', 16, 'MF'),
        ('Edo Kayembe', '埃多·卡耶姆贝', 17, 'MF'),
        ('Nathanael Mbuku', '纳撒尼尔·姆布库', 18, 'MF'),
        ('Samuel Moutoussamy', '萨穆埃尔·穆图萨米', 19, 'MF'),
        ('Ngal\'ayel Mukau', '恩加拉耶尔·穆考', 20, 'MF'),
        ('Charles Pickel', '查尔斯·皮克尔', 21, 'MF'),
        ('Noah Sadiki', '诺亚·萨迪基', 22, 'MF'),
        ('Cedric Bakambu', '巴坎布', 23, 'FW'),
        ('Simon Banza', '西蒙·班扎', 24, 'FW'),
        ('Fiston Mayele', '菲斯顿·马耶勒', 25, 'FW'),
        ('Yoane Wissa', '约阿纳·维萨', 26, 'FW'),
    ],
    '葡萄牙': [
        ('Diogo Costa', '迪奥戈·科斯塔', 1, 'GK'),
        ('Jose Sa', '若泽·萨', 2, 'GK'),
        ('Rui Silva', '鲁伊·席尔瓦', 3, 'GK'),
        ('Ricardo Velho', '里卡多·韦略', 4, 'GK'),
        ('Diogo Dalot', '达洛特', 5, 'DF'),
        ('Matheus Nunes', '努内斯', 6, 'DF'),
        ('Nelson Semedo', '塞梅多', 7, 'DF'),
        ('Joao Cancelo', '坎塞洛', 8, 'DF'),
        ('Nuno Mendes', '门德斯', 9, 'DF'),
        ('Goncalo Inacio', '伊纳西奥', 10, 'DF'),
        ('Renato Veiga', '韦加', 11, 'DF'),
        ('Ruben Dias', '鲁本·迪亚斯', 12, 'DF'),
        ('Tomas Araujo', '托马斯·阿劳霍', 13, 'DF'),
        ('Ruben Neves', '鲁本·内维斯', 14, 'MF'),
        ('Samuel Costa', '萨穆·科斯塔', 15, 'MF'),
        ('Joao Neves', '若昂·内维斯', 16, 'MF'),
        ('Vitinha', '维蒂尼亚', 17, 'MF'),
        ('Bruno Fernandes', '布鲁诺·费尔南德斯', 18, 'MF'),
        ('Bernardo Silva', '贝尔纳多·席尔瓦', 19, 'MF'),
        ('Joao Felix', '菲利克斯', 20, 'FW'),
        ('Francisco Trincao', '特林康', 21, 'FW'),
        ('Francisco Conceicao', '孔塞桑', 22, 'FW'),
        ('Pedro Neto', '内托', 23, 'FW'),
        ('Rafael Leao', '莱奥', 24, 'FW'),
        ('Goncalo Guedes', '格德斯', 25, 'FW'),
        ('Goncalo Ramos', '拉莫斯', 26, 'FW'),
        ('Cristiano Ronaldo', 'C罗', 27, 'FW'),
    ],
    '乌兹别克斯坦': [
        ('Utkir Yusupov', '乌特基尔·尤苏波夫', 1, 'GK'),
        ('Abduvohid Nematov', '阿卜杜沃希德·内马托夫', 2, 'GK'),
        ('Botirali Ergashev', '博蒂拉利·埃尔加舍夫', 3, 'GK'),
        ('Rustam Ashurmatov', '鲁斯塔姆·阿舒尔马托夫', 4, 'DF'),
        ('Farrukh Sayfiev', '法鲁赫·赛菲耶夫', 5, 'DF'),
        ('Khojiakbar Alijonov', '霍吉亚克巴尔·阿利约诺夫', 6, 'DF'),
        ('Sherzod Nasrullaev', '舍尔佐德·纳斯鲁拉耶夫', 7, 'DF'),
        ('Umar Eshmurodov', '乌马尔·埃什穆罗多夫', 8, 'DF'),
        ('Abdukodir Khusanov', '阿卜杜科迪尔·胡萨诺夫', 9, 'DF'),
        ('Abdulla Abdullaev', '阿卜杜拉·阿卜杜拉耶夫', 10, 'DF'),
        ('Bekhruz Karimov', '贝赫鲁兹·卡里莫夫', 11, 'DF'),
        ('Jakhongir Urozov', '贾洪吉尔·乌罗佐夫', 12, 'DF'),
        ('Avazbek Ulmasaliev', '阿瓦兹别克·乌尔马萨利耶夫', 13, 'DF'),
        ('Otabek Shukurov', '奥塔别克·舒库罗夫', 14, 'MF'),
        ('Jaloliddin Masharipov', '贾洛利丁·马沙里波夫', 15, 'MF'),
        ('Odiljon Hamrobekov', '奥迪尔容·哈姆罗别科夫', 16, 'MF'),
        ('Oston Urunov', '奥斯通·乌鲁诺夫', 17, 'MF'),
        ('Jamshid Iskanderov', '贾姆希德·伊斯坎德罗夫', 18, 'MF'),
        ('Dostonbek Khamdamov', '多斯顿别克·哈姆达莫夫', 19, 'MF'),
        ('Abbosbek Fayzullaev', '阿博斯别克·法伊祖拉耶夫', 20, 'MF'),
        ('Akmal Mozgovoy', '阿克马尔·莫兹戈沃伊', 21, 'MF'),
        ('Azizjon Ganiev', '阿齐兹容·加尼耶夫', 22, 'MF'),
        ('Sherzod Esanov', '舍尔佐德·埃萨诺夫', 23, 'MF'),
        ('Eldor Shomurodov', '埃尔多尔·肖穆罗多夫', 24, 'FW'),
        ('Igor Sergeev', '伊戈尔·谢尔盖耶夫', 25, 'FW'),
        ('Azizbek Amonov', '阿齐兹别克·阿莫诺夫', 26, 'FW'),
    ],
    '克罗地亚': [
        ('Dominik Livakovic', '多米尼克·利瓦科维奇', 1, 'GK'),
        ('Dominik Kotarski', '多米尼克·科塔尔斯基', 2, 'GK'),
        ('Ivor Pandur', '伊沃·潘杜尔', 3, 'GK'),
        ('Josko Gvardiol', '约什科·格瓦迪奥尔', 4, 'DF'),
        ('Duje Caleta-Car', '杜耶·查莱塔-察尔', 5, 'DF'),
        ('Josip Sutalo', '约瑟普·舒塔洛', 6, 'DF'),
        ('Josip Stanisic', '约瑟普·斯塔尼西奇', 7, 'DF'),
        ('Marin Pongracic', '马林·蓬格拉契奇', 8, 'DF'),
        ('Martin Erlic', '马丁·埃尔利奇', 9, 'DF'),
        ('Luka Vuskovic', '卢卡·武什科维奇', 10, 'DF'),
        ('Luka Modric', '卢卡·莫德里奇', 11, 'MF'),
        ('Mateo Kovacic', '马特奥·科瓦契奇', 12, 'MF'),
        ('Mario Pasalic', '马里奥·帕萨利奇', 13, 'MF'),
        ('Nikola Vlasic', '尼古拉·弗拉希奇', 14, 'MF'),
        ('Luka Sucic', '卢卡·苏契奇', 15, 'MF'),
        ('Martin Baturina', '马丁·巴图里纳', 16, 'MF'),
        ('Kristijan Jakic', '克里斯蒂安·亚基奇', 17, 'MF'),
        ('Petar Sucic', '佩塔尔·苏契奇', 18, 'MF'),
        ('Nikola Moro', '尼古拉·莫罗', 19, 'MF'),
        ('Toni Fruk', '托尼·弗鲁克', 20, 'MF'),
        ('Ivan Perisic', '伊万·佩里西奇', 21, 'FW'),
        ('Andrej Kramaric', '安德雷·克拉马里奇', 22, 'FW'),
        ('Ante Budimir', '安特·布迪米尔', 23, 'FW'),
        ('Marco Pasalic', '马尔科·帕萨利奇', 24, 'FW'),
        ('Petar Musa', '佩塔尔·穆萨', 25, 'FW'),
        ('Igor Matanovic', '伊戈尔·马塔诺维奇', 26, 'FW'),
    ],
    '英格兰': [
        ('Jordan Pickford', '乔丹·皮克福德', 1, 'GK'),
        ('Dean Henderson', '迪恩·亨德森', 2, 'GK'),
        ('James Trafford', '詹姆斯·特拉福德', 3, 'GK'),
        ('Reece James', '里斯·詹姆斯', 4, 'DF'),
        ('Ezri Konsa', '埃兹里·孔萨', 5, 'DF'),
        ('Jarell Quansah', '贾雷尔·宽萨', 6, 'DF'),
        ('John Stones', '约翰·斯通斯', 7, 'DF'),
        ('Marc Guehi', '马克·格伊', 8, 'DF'),
        ('Dan Burn', '丹·伯恩', 9, 'DF'),
        ('Nico O\'Reilly', '尼科·奥赖利', 10, 'DF'),
        ('Djed Spence', '杰德·斯彭斯', 11, 'DF'),
        ('Tino Livramento', '蒂诺·利夫拉门托', 12, 'DF'),
        ('Declan Rice', '德克兰·赖斯', 13, 'MF'),
        ('Elliot Anderson', '埃利奥特·安德森', 14, 'MF'),
        ('Kobbie Mainoo', '科比·梅努', 15, 'MF'),
        ('Jordan Henderson', '乔丹·亨德森', 16, 'MF'),
        ('Morgan Rogers', '摩根·罗杰斯', 17, 'MF'),
        ('Jude Bellingham', '裘德·贝林厄姆', 18, 'MF'),
        ('Eberechi Eze', '埃贝雷奇·埃泽', 19, 'MF'),
        ('Harry Kane', '哈里·凯恩', 20, 'FW'),
        ('Ivan Toney', '伊万·托尼', 21, 'FW'),
        ('Ollie Watkins', '奥利·沃特金斯', 22, 'FW'),
        ('Bukayo Saka', '布卡约·萨卡', 23, 'FW'),
        ('Marcus Rashford', '马库斯·拉什福德', 24, 'FW'),
        ('Anthony Gordon', '安东尼·戈登', 25, 'FW'),
        ('Noni Madueke', '诺尼·马杜埃凯', 26, 'FW'),
    ],
    '加纳': [
        ('Benjamin Asare', '本杰明·阿萨雷', 1, 'GK'),
        ('Lawrence Ati-Zigi', '劳伦斯·阿蒂-齐吉', 2, 'GK'),
        ('Joseph Anang', '约瑟夫·阿南', 3, 'GK'),
        ('Baba Abdul Rahman', '巴巴·阿卜杜勒·拉赫曼', 4, 'DF'),
        ('Gideon Mensah', '吉迪恩·门萨', 5, 'DF'),
        ('Marvin Senaya', '马尔文·塞纳亚', 6, 'DF'),
        ('Alidu Seidu', '阿利杜·塞杜', 7, 'DF'),
        ('Abdul Mumin', '阿卜杜勒·穆明', 8, 'DF'),
        ('Jerome Opoku', '杰罗姆·奥波库', 9, 'DF'),
        ('Jonas Adjetey', '约纳斯·阿杰泰', 10, 'DF'),
        ('Kojo Oppong Peprah', '科乔·奥蓬·佩普拉', 11, 'DF'),
        ('Elisha Owusu', '埃利沙·奥乌苏', 12, 'DF'),
        ('Derrick Luckassen', '德里克·卢卡森', 13, 'DF'),
        ('Thomas Partey', '托马斯·帕尔特伊', 14, 'MF'),
        ('Kwasi Sibo', '夸西·西博', 15, 'MF'),
        ('Augustine Boakye', '奥古斯丁·博阿基耶', 16, 'MF'),
        ('Caleb Yirenkyi', '卡莱布·伊伦基', 17, 'MF'),
        ('Abdul Fatawu Issahaku', '阿卜杜勒·法塔武·伊萨哈库', 18, 'MF'),
        ('Kamaldeen Sulemana', '卡马勒丁·苏莱曼纳', 19, 'FW'),
        ('Christopher Bonsu Baah', '克里斯托弗·邦苏·巴', 20, 'FW'),
        ('Ernest Nuamah', '欧内斯特·努瓦马', 21, 'FW'),
        ('Antoine Semenyo', '安托万·塞梅尼奥', 22, 'FW'),
        ('Brandon Thomas-Asante', '布兰登·托马斯-阿桑特', 23, 'FW'),
        ('Prince Kwabena Adu', '普林斯·夸贝纳·阿杜', 24, 'FW'),
        ('Inaki Williams', '伊尼亚基·威廉姆斯', 25, 'FW'),
        ('Jordan Ayew', '乔丹·阿尤', 26, 'FW'),
    ],
    '巴拿马': [
        ('Luis Mejia', '路易斯·梅吉亚', 1, 'GK'),
        ('Orlando Mosquera', '奥兰多·莫斯奎拉', 2, 'GK'),
        ('Cesar Samudio', '塞萨尔·萨穆迪奥', 3, 'GK'),
        ('Eric Davis', '埃里克·戴维斯', 4, 'DF'),
        ('Fidel Escobar', '菲德尔·埃斯科瓦尔', 5, 'DF'),
        ('Michael Amir Murillo', '迈克尔·穆里略', 6, 'DF'),
        ('Roderick Miller', '罗德里克·米勒', 7, 'DF'),
        ('Andres Andrade', '安德烈亚斯·安德雷德', 8, 'DF'),
        ('Cesar Blackman', '塞萨尔·布莱克曼', 9, 'DF'),
        ('Jose Cordoba', '何塞·科尔多瓦', 10, 'DF'),
        ('Jiovany Ramos', '吉奥瓦尼·拉莫斯', 11, 'DF'),
        ('Jorge Gutierrez', '豪尔赫·古铁雷斯', 12, 'DF'),
        ('Edgardo Farina', '埃德加多·法里尼亚', 13, 'DF'),
        ('Anibal Godoy', '戈多伊', 14, 'MF'),
        ('Alberto Quintero', '阿尔伯特·金特罗', 15, 'MF'),
        ('Yoel Barcenas', '巴塞纳斯', 16, 'MF'),
        ('Adalberto Carrasquilla', '卡拉斯基利亚', 17, 'MF'),
        ('Jose Luis Rodriguez', '罗德里格斯', 18, 'MF'),
        ('Cristian Martinez', '克里斯蒂安·马丁内斯', 19, 'MF'),
        ('Cesar Yanis', '亚尼斯', 20, 'MF'),
        ('Carlos Harvey', '卡洛斯·哈维', 21, 'MF'),
        ('Azarias Londono', '阿扎里亚斯·伦多尼奥', 22, 'MF'),
        ('Jose Fajardo', '法贾尔多', 23, 'FW'),
        ('Ismael Diaz', '伊斯梅尔·迪亚斯', 24, 'FW'),
        ('Cecilio Waterman', '塞西·沃特曼', 25, 'FW'),
        ('Tomas Rodriguez', '托马斯·罗德里格斯', 26, 'FW'),
    ],
}



def seed_database():
    init_db()
    db = get_db()
    cur = db.cursor()

    # Insert teams
    team_ids = {}
    for i, (name, group, flag) in enumerate(TEAMS, 1):
        cur.execute('INSERT INTO teams (name, group_name, flag_emoji) VALUES (?, ?, ?)', (name, group, flag))
        team_ids[i] = cur.lastrowid

    # Insert players (26 per team from real WC squads)
    player_count = 0
    for team_idx in range(1, 49):
        team_id = team_ids[team_idx]
        cn_name = TEAMS[team_idx - 1][0]
        squad = PLAYERS_DATA.get(cn_name, [])
        for p in squad:
            name, name_cn, jersey_number, position = p
            cur.execute('INSERT INTO players (name, name_cn, jersey_number, team_id, position) VALUES (?, ?, ?, ?, ?)', (name, name_cn, jersey_number, team_id, position))
            player_count += 1

    # Insert participants
    participants = [
        ('耗子', 1),
        ('庆爷', 2),
        ('李总', 3),
        ('老闫', 4),
        ('老王', 5),
    ]
    for name, order in participants:
        cur.execute('INSERT INTO participants (name, draft_order) VALUES (?, ?)', (name, order))

    db.commit()
    db.close()
    print(f'Seeded: {len(TEAMS)} teams, {player_count} players, {len(participants)} participants')


if __name__ == '__main__':
    seed_database()