"""ESPN soccer team ids for FIFA World Cup 2026 (from espn.com/soccer/teams/_/league/fifa.world)."""

ESPN_TEAMS = {
    'Mexico': (203, 'mexico'),
    'South Africa': (467, 'south-africa'),
    'Korea Republic': (451, 'south-korea'),
    'Czech Republic': (450, 'czechia'),
    'Canada': (206, 'canada'),
    'Bosnia-Herzegovina': (452, 'bosnia-herzegovina'),
    'Qatar': (4398, 'qatar'),
    'Switzerland': (475, 'switzerland'),
    'Brazil': (205, 'brazil'),
    'Morocco': (2869, 'morocco'),
    'Haiti': (2654, 'haiti'),
    'Scotland': (580, 'scotland'),
    'United States': (660, 'united-states'),
    'Paraguay': (210, 'paraguay'),
    'Australia': (628, 'australia'),
    'Turkey': (465, 'turkiye'),
    'Germany': (481, 'germany'),
    'Curacao': (11678, 'curacao'),
    'Ivory Coast': (4789, 'ivory-coast'),
    'Ecuador': (209, 'ecuador'),
    'Netherlands': (449, 'netherlands'),
    'Japan': (627, 'japan'),
    'Sweden': (466, 'sweden'),
    'Tunisia': (659, 'tunisia'),
    'Belgium': (459, 'belgium'),
    'Egypt': (2620, 'egypt'),
    'Iran': (469, 'iran'),
    'New Zealand': (2666, 'new-zealand'),
    'Spain': (164, 'spain'),
    'Cape Verde': (2597, 'cape-verde'),
    'Saudi Arabia': (655, 'saudi-arabia'),
    'Uruguay': (212, 'uruguay'),
    'France': (478, 'france'),
    'Senegal': (654, 'senegal'),
    'Iraq': (4375, 'iraq'),
    'Norway': (464, 'norway'),
    'Argentina': (202, 'argentina'),
    'Algeria': (624, 'algeria'),
    'Austria': (474, 'austria'),
    'Jordan': (2917, 'jordan'),
    'Portugal': (482, 'portugal'),
    'DR Congo': (2850, 'congo-dr'),
    'Uzbekistan': (2570, 'uzbekistan'),
    'Colombia': (208, 'colombia'),
    'England': (448, 'england'),
    'Croatia': (477, 'croatia'),
    'Ghana': (4469, 'ghana'),
    'Panama': (2659, 'panama'),
}

ESPN_TEAM_CN = {
    'Mexico': '墨西哥',
    'South Africa': '南非',
    'Korea Republic': '韩国',
    'Czech Republic': '捷克',
    'Canada': '加拿大',
    'Bosnia-Herzegovina': '波黑',
    'Qatar': '卡塔尔',
    'Switzerland': '瑞士',
    'Brazil': '巴西',
    'Morocco': '摩洛哥',
    'Haiti': '海地',
    'Scotland': '苏格兰',
    'United States': '美国',
    'Paraguay': '巴拉圭',
    'Australia': '澳大利亚',
    'Turkey': '土耳其',
    'Germany': '德国',
    'Curacao': '库拉索',
    'Ivory Coast': '科特迪瓦',
    'Ecuador': '厄瓜多尔',
    'Netherlands': '荷兰',
    'Japan': '日本',
    'Sweden': '瑞典',
    'Tunisia': '突尼斯',
    'Belgium': '比利时',
    'Egypt': '埃及',
    'Iran': '伊朗',
    'New Zealand': '新西兰',
    'Spain': '西班牙',
    'Cape Verde': '佛得角',
    'Saudi Arabia': '沙特',
    'Uruguay': '乌拉圭',
    'France': '法国',
    'Senegal': '塞内加尔',
    'Iraq': '伊拉克',
    'Norway': '挪威',
    'Argentina': '阿根廷',
    'Algeria': '阿尔及利亚',
    'Austria': '奥地利',
    'Jordan': '约旦',
    'Portugal': '葡萄牙',
    'DR Congo': '刚果（金）',
    'Uzbekistan': '乌兹别克斯坦',
    'Colombia': '哥伦比亚',
    'England': '英格兰',
    'Croatia': '克罗地亚',
    'Ghana': '加纳',
    'Panama': '巴拿马',
}
