"""Patch seed_data.py with Chinese player names from Xinhua articles.
For teams without verified data, name_cn stays empty (falls back to English)."""
import re

# Verified Chinese names from Xinhua articles: {English_name: Chinese_name}
CN_NAMES = {
    # ========== Germany (新华网 20260522) ==========
    'Oliver Baumann': '奥利弗·鲍曼',
    'Manuel Neuer': '曼努埃尔·诺伊尔',
    'Alexander Nubel': '亚历山大·努贝尔',
    'Waldemar Anton': '瓦尔德马·安东',
    'Nathaniel Brown': '纳撒尼尔·布朗',
    'David Raum': '大卫·劳姆',
    'Antonio Rudiger': '安东尼奥·吕迪格',
    'Nico Schlotterbeck': '尼科·施洛特贝克',
    'Jonathan Tah': '约纳坦·塔',
    'Malick Thiaw': '马利克·蒂亚夫',
    'Pascal Gross': '帕斯卡尔·格罗斯',
    'Joshua Kimmich': '约书亚·基米希',
    'Felix Nmecha': '费利克斯·恩梅查',
    'Aleksandar Pavlovic': '亚历山大·帕夫洛维奇',
    'Angelo Stiller': '安杰洛·施蒂勒',
    'Leon Goretzka': '莱昂·格雷茨卡',
    'Florian Wirtz': '弗洛里安·维尔茨',
    'Jamie Leweling': '杰米·勒韦林',
    'Maximilian Beier': '马克西米利安·拜尔',
    'Kai Havertz': '凯·哈弗茨',
    'Lennart Karl': '伦纳特·卡尔',
    'Jamal Musiala': '贾马尔·穆西亚拉',
    'Leroy Sane': '勒鲁瓦·萨内',
    'Deniz Undav': '德尼兹·翁达夫',
    'Nick Woltemade': '尼克·沃尔特马德',
    # Note: Xinhua has: 纳迪姆·阿米里, 约书亚·基米希 (MF), not matching seed data
    
    # ========== Spain (新华网 20260525) ==========
    'Unai Simon': '乌奈·西蒙',
    'David Raya': '拉亚',
    'Joan Garcia': '霍安·加西亚',
    'Aymeric Laporte': '拉波尔特',
    'Marc Cucurella': '库库雷利亚',
    'Marcos Llorente': '马科斯·略伦特',
    'Eric Garcia': '埃里克·加西亚',
    'Pedro Porro': '波罗',
    'Alex Grimaldo': '格里马尔多',
    'Pau Cubarsi': '库巴西',
    'Marc Pubill': '普维尔',
    'Rodri': '罗德里',
    'Fabian Ruiz': '法比安·鲁伊斯',
    'Mikel Merino': '梅里诺',
    'Pedri': '佩德里',
    'Gavi': '加维',
    'Martin Zubimendi': '苏比门迪',
    'Alex Baena': '巴埃纳',
    'Ferran Torres': '费兰·托雷斯',
    'Mikel Oyarzabal': '奥亚萨瓦尔',
    'Dani Olmo': '达尼·奥尔莫',
    'Nico Williams': '尼科·威廉姆斯',
    'Lamine Yamal': '亚马尔',
    'Yeremy Pino': '皮诺',
    'Borja Iglesias': '伊格莱西亚斯',
    'Victor Munoz': '穆尼奥斯',
    
    # ========== Brazil (新华网 20260519) ==========
    'Alisson': '阿利松',
    'Ederson': '埃德森',
    'Weverton': '维弗顿',
    'Marquinhos': '马尔基尼奥斯',
    'Gabriel': '加布里埃尔·马加良斯',
    'Bremer': '布雷默',
    'Ibanez': '伊巴涅斯',
    'Leo Pereira': '莱奥·佩雷拉',
    'Wesley': '韦斯利',
    'Alex Sandro': '亚历克斯·桑德罗',
    'Douglas Santos': '道格拉斯·桑托斯',
    'Danilo': '达尼洛',
    'Casemiro': '卡塞米罗',
    'Bruno Guimaraes': '布鲁诺·吉马良斯',
    'Fabinho': '法比尼奥',
    'Lucas Paqueta': '卢卡斯·帕克塔',
    'Vinicius Junior': '维尼修斯',
    'Raphinha': '拉菲尼亚',
    'Matheus Cunha': '马特乌斯·库尼亚',
    'Luiz Henrique': '路易斯·恩里克',
    'Igor Thiago': '伊戈尔·蒂亚戈',
    'Endrick': '恩德里克',
    'Gabriel Martinelli': '马丁内利',
    'Rayan': '拉扬',
    'Neymar': '内马尔',
    
    # ========== France (新华网 20260515) ==========
    'Mike Maignan': '迈尼昂',
    'Robin Risser': '里塞',
    'Brice Samba': '桑巴',
    'Lucas Digne': '迪涅',
    'Malo Gusto': '古斯托',
    'Lucas Hernandez': '卢卡斯·埃尔南德斯',
    'Theo Hernandez': '特奥',
    'Ibrahima Konate': '科纳特',
    'Jules Kounde': '孔德',
    'Maxence Lacroix': '拉克鲁瓦',
    'William Saliba': '萨利巴',
    'Dayot Upamecano': '于帕梅卡诺',
    'N\'Golo Kante': '坎特',
    'Manu Kone': '科内',
    'Adrien Rabiot': '拉比奥',
    'Aurelien Tchouameni': '琼阿梅尼',
    'Warren Zaire-Emery': '扎伊尔·埃梅里',
    'Maghnes Akliouche': '阿克利乌舍',
    'Bradley Barcola': '巴尔科拉',
    'Rayan Cherki': '谢尔基',
    'Ousmane Dembele': '登贝莱',
    'Desire Doue': '杜埃',
    'Jean-Philippe Mateta': '马特塔',
    'Kylian Mbappe': '姆巴佩',
    'Michael Olise': '奥利塞',
    'Marcus Thuram': '图拉姆',
    
    # ========== England (新华网 20260522) ==========
    'Jordan Pickford': '乔丹·皮克福德',
    'Dean Henderson': '迪恩·亨德森',
    'James Trafford': '詹姆斯·特拉福德',
    'Reece James': '里斯·詹姆斯',
    'Ezri Konsa': '埃兹里·孔萨',
    'Jarell Quansah': '贾雷尔·宽萨',
    'John Stones': '约翰·斯通斯',
    'Marc Guehi': '马克·格伊',
    'Dan Burn': '丹·伯恩',
    'Nico O\'Reilly': '尼科·奥赖利',
    'Djed Spence': '杰德·斯彭斯',
    'Tino Livramento': '蒂诺·利夫拉门托',
    'Declan Rice': '德克兰·赖斯',
    'Elliot Anderson': '埃利奥特·安德森',
    'Kobbie Mainoo': '科比·梅努',
    'Jordan Henderson': '乔丹·亨德森',
    'Morgan Rogers': '摩根·罗杰斯',
    'Jude Bellingham': '裘德·贝林厄姆',
    'Eberechi Eze': '埃贝雷奇·埃泽',
    'Harry Kane': '哈里·凯恩',
    'Ivan Toney': '伊万·托尼',
    'Ollie Watkins': '奥利·沃特金斯',
    'Bukayo Saka': '布卡约·萨卡',
    'Marcus Rashford': '马库斯·拉什福德',
    'Anthony Gordon': '安东尼·戈登',
    'Noni Madueke': '诺尼·马杜埃凯',
    
    # ========== USA (新华网 20260526) ==========
    'Chris Brady': '克里斯·布雷迪',
    'Matt Freese': '马特·弗里兹',
    'Matt Turner': '马特·特纳',
    'Max Arfsten': '马克斯·阿夫斯滕',
    'Sergino Dest': '塞吉诺·德斯特',
    'Alex Freeman': '亚历克斯·弗里曼',
    'Mark McKenzie': '马克·麦肯齐',
    'Tim Ream': '蒂姆·里姆',
    'Chris Richards': '克里斯·理查兹',
    'Antonee Robinson': '安东尼·罗宾逊',
    'Miles Robinson': '米尔斯·罗宾森',
    'Joe Scally': '乔·斯卡利',
    'Auston Trusty': '奥斯顿·托斯蒂',
    'Tyler Adams': '泰勒·亚当斯',
    'Sebastian Berhalter': '塞巴斯蒂安·贝哈尔特',
    'Weston McKennie': '韦斯顿·麦肯尼',
    'Gio Reyna': '乔·雷纳',
    'Cristian Roldan': '克里斯蒂安·罗尔丹',
    'Malik Tillman': '马利克·蒂尔曼',
    'Brenden Aaronson': '布伦登·阿隆森',
    'Folarin Balogun': '福拉林·巴洛贡',
    'Ricardo Pepi': '里卡多·佩皮',
    'Christian Pulisic': '克里斯蒂安·普利西奇',
    'Tim Weah': '蒂莫西·维亚',
    'Haji Wright': '哈吉·赖特',
    'Alejandro Zendejas': '亚历杭德罗·赞德哈斯',
    
    # ========== Argentina (新华网 20260528) ==========
    'Emiliano Martinez': '埃米利亚诺·马丁内斯',
    'Juan Musso': '胡安·穆索',
    'Geronimo Rulli': '赫罗尼莫·鲁利',
    'Leonardo Balerdi': '莱昂纳多·巴莱尔迪',
    'Lisandro Martinez': '利桑德罗·马丁内斯',
    'Facundo Medina': '法昆多·梅迪纳',
    'Nahuel Molina': '纳韦尔·莫利纳',
    'Gonzalo Montiel': '冈萨洛·蒙铁尔',
    'Nicolas Otamendi': '尼古拉斯·奥塔门迪',
    'Cristian Romero': '克里斯蒂安·罗梅罗',
    'Nicolas Tagliafico': '尼古拉斯·塔利亚菲科',
    'Valentin Barco': '巴伦廷·巴尔科',
    'Rodrigo De Paul': '罗德里戈·德保罗',
    'Enzo Fernandez': '恩佐·费尔南德斯',
    'Giovani Lo Celso': '乔瓦尼·洛塞尔索',
    'Alexis Mac Allister': '亚历克西斯·麦卡利斯特',
    'Exequiel Palacios': '埃塞基耶尔·帕拉西奥斯',
    'Leandro Paredes': '莱安德罗·帕雷德斯',
    'Thiago Almada': '蒂亚戈·阿尔马达',
    'Julian Alvarez': '胡利安·阿尔瓦雷斯',
    'Nicolas Gonzalez': '尼古拉斯·冈萨雷斯',
    'Jose Manuel Lopez': '何塞·曼努埃尔·洛佩斯',
    'Lautaro Martinez': '劳塔罗·马丁内斯',
    'Lionel Messi': '利昂内尔·梅西',
    'Nicolas Paz': '尼科·帕斯',
    'Giuliano Simeone': '朱利亚诺·西蒙尼',
    
    # ========== Portugal (新华网 20260519) ==========
    'Diogo Costa': '迪奥戈·科斯塔',
    'Jose Sa': '若泽·萨',
    'Rui Silva': '鲁伊·席尔瓦',
    'Ricardo Velho': '里卡多·韦略',
    'Diogo Dalot': '达洛特',
    'Matheus Nunes': '努内斯',
    'Nelson Semedo': '塞梅多',
    'Joao Cancelo': '坎塞洛',
    'Nuno Mendes': '门德斯',
    'Goncalo Inacio': '伊纳西奥',
    'Renato Veiga': '韦加',
    'Ruben Dias': '鲁本·迪亚斯',
    'Tomas Araujo': '托马斯·阿劳霍',
    'Ruben Neves': '鲁本·内维斯',
    'Samuel Costa': '萨穆·科斯塔',
    'Joao Neves': '若昂·内维斯',
    'Vitinha': '维蒂尼亚',
    'Bruno Fernandes': '布鲁诺·费尔南德斯',
    'Bernardo Silva': '贝尔纳多·席尔瓦',
    'Joao Felix': '菲利克斯',
    'Francisco Trincao': '特林康',
    'Francisco Conceicao': '孔塞桑',
    'Pedro Neto': '内托',
    'Rafael Leao': '莱奥',
    'Goncalo Guedes': '格德斯',
    'Goncalo Ramos': '拉莫斯',
    'Cristiano Ronaldo': 'C罗',
    
    # ========== Mexico (新华网 20260531) ==========
    'Carlos Acevedo': '卡洛斯·阿塞韦多',
    'Guillermo Ochoa': '吉列尔莫·奥乔亚',
    'Raul Rangel': '劳尔·兰赫尔',
    'Edson Alvarez': '埃德松·阿尔瓦雷斯',
    'Israel Reyes': '伊斯雷尔·雷耶斯',
    'Jesus Gallardo': '赫苏斯·加利亚多',
    'Johan Vasquez': '约翰·巴斯克斯',
    'Jorge Sanchez': '豪尔赫·桑切斯',
    'Mateo Chavez': '马特奥·查韦斯',
    'Alvaro Fidalgo': '阿尔瓦罗·菲达尔戈',
    'Brian Gutierrez': '布里安·古铁雷斯',
    'Erik Lira': '埃里克·利拉',
    'Gilberto Mora': '希尔韦托·莫拉',
    'Luis Romo': '路易斯·罗莫',
    'Obed Vargas': '奥贝德·巴尔加斯',
    'Orbelin Pineda': '奥韦林·皮内达',
    'Alexis Vega': '亚历克西斯·贝加',
    'Armando Gonzalez': '阿曼多·冈萨雷斯',
    'Cesar Huerta': '塞萨尔·韦尔塔',
    'Guillermo Martinez': '吉列尔莫·马丁内斯',
    'Julian Quinones': '胡利安·基尼奥内斯',
    'Raul Jimenez': '劳尔·希门尼斯',
    'Santiago Gimenez': '圣地亚哥·希门尼斯',
}

def patch_seed_data():
    with open('d:\\AI\\WorldCupGame\\seed_data.py', 'r', encoding='utf-8') as f:
        content = f.read()
    
    count = 0
    # Match player entries: ('EnglishName', '', Number, 'POS')
    # Replace the '' with the Chinese name
    for eng_name, cn_name in CN_NAMES.items():
        # Escape special regex chars in name
        escaped = re.escape(eng_name)
        pattern = rf"(\({escaped}),\s*''\s*," 
        replacement = rf"(\1, '{cn_name}',"
        new_content = re.sub(pattern, replacement, content)
        if new_content != content:
            count += 1
            content = new_content
    
    with open('d:\\AI\\WorldCupGame\\seed_data.py', 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Patched {count} Chinese names into seed_data.py")
    print(f"Total verified names in dictionary: {len(CN_NAMES)}")

if __name__ == '__main__':
    patch_seed_data()
