"""Patch seed_data.py with Chinese player names - direct replacement approach."""
import re

# Verified Chinese names from Xinhua articles
CN_NAMES = {
    # Germany
    'Oliver Baumann': '奥利弗·鲍曼',
    'Manuel Neuer': '曼努埃尔·诺伊尔',
    'Alexander Nubel': '亚历山大·努贝尔',
    'Waldemar Anton': '瓦尔德马·安东',
    'Nathaniel Brown': '纳撒尼尔·布朗',
    'David Raum': '大卫·劳姆',
    'Antonio Rudiger': '安东尼奥·吕迪格',
    'Nico Schlotterbeck': '尼科·施洛特贝克',
    'Jonathan Tah': '约纳坦·塔',
    'Malick Thiaw': '马利克·蒂亚夫',
    'Pascal Gross': '帕斯卡尔·格罗斯',
    'Joshua Kimmich': '约书亚·基米希',
    'Felix Nmecha': '费利克斯·恩梅查',
    'Aleksandar Pavlovic': '亚历山大·帕夫洛维奇',
    'Angelo Stiller': '安杰洛·施蒂勒',
    'Leon Goretzka': '莱昂·格雷茨卡',
    'Florian Wirtz': '弗洛里安·维尔茨',
    'Jamie Leweling': '杰米·勒韦林',
    'Maximilian Beier': '马克西米利安·拜尔',
    'Kai Havertz': '凯·哈弗茨',
    'Lennart Karl': '伦纳特·卡尔',
    'Jamal Musiala': '贾马尔·穆西亚拉',
    'Leroy Sane': '勒鲁瓦·萨内',
    'Deniz Undav': '德尼兹·翁达夫',
    'Nick Woltemade': '尼克·沃尔特马德',
    # Spain
    'Unai Simon': '乌奈·西蒙',
    'David Raya': '拉亚',
    'Joan Garcia': '霍安·加西亚',
    'Aymeric Laporte': '拉波尔特',
    'Marc Cucurella': '库库雷利亚',
    'Marcos Llorente': '马科斯·略伦特',
    'Eric Garcia': '埃里克·加西亚',
    'Pedro Porro': '波罗',
    'Alex Grimaldo': '格里马尔多',
    'Pau Cubarsi': '库巴西',
    'Marc Pubill': '普维尔',
    'Rodri': '罗德里',
    'Fabian Ruiz': '法比安·鲁伊斯',
    'Mikel Merino': '梅里诺',
    'Pedri': '佩德里',
    'Gavi': '加维',
    'Martin Zubimendi': '苏比门迪',
    'Alex Baena': '巴埃纳',
    'Ferran Torres': '费兰·托雷斯',
    'Mikel Oyarzabal': '奥亚萨瓦尔',
    'Dani Olmo': '达尼·奥尔莫',
    'Nico Williams': '尼科·威廉姆斯',
    'Lamine Yamal': '亚马尔',
    'Yeremy Pino': '皮诺',
    'Borja Iglesias': '伊格莱西亚斯',
    'Victor Munoz': '穆尼奥斯',
    # Brazil
    'Alisson': '阿利松',
    'Ederson': '埃德森',
    'Weverton': '维弗顿',
    'Marquinhos': '马尔基尼奥斯',
    'Gabriel': '加布里埃尔',
    'Bremer': '布雷默',
    'Ibanez': '伊巴涅斯',
    'Leo Pereira': '莱奥·佩雷拉',
    'Wesley': '韦斯利',
    'Alex Sandro': '亚历克斯·桑德罗',
    'Douglas Santos': '道格拉斯·桑托斯',
    'Danilo': '达尼洛',
    'Casemiro': '卡塞米罗',
    'Bruno Guimaraes': '布鲁诺·吉马良斯',
    'Fabinho': '法比尼奥',
    'Lucas Paqueta': '卢卡斯·帕克塔',
    'Vinicius Junior': '维尼修斯',
    'Raphinha': '拉菲尼亚',
    'Matheus Cunha': '马特乌斯·库尼亚',
    'Luiz Henrique': '路易斯·恩里克',
    'Igor Thiago': '伊戈尔·蒂亚戈',
    'Endrick': '恩德里克',
    'Gabriel Martinelli': '马丁内利',
    'Rayan': '拉扬',
    'Neymar': '内马尔',
    # France
    'Mike Maignan': '迈尼昂',
    'Robin Risser': '里塞',
    'Brice Samba': '桑巴',
    'Lucas Digne': '迪涅',
    'Malo Gusto': '古斯托',
    'Lucas Hernandez': '卢卡斯·埃尔南德斯',
    'Theo Hernandez': '特奥',
    'Ibrahima Konate': '科纳特',
    'Jules Kounde': '孔德',
    'Maxence Lacroix': '拉克鲁瓦',
    'William Saliba': '萨利巴',
    'Dayot Upamecano': '于帕梅卡诺',
    "N'Golo Kante": '坎特',
    'Manu Kone': '科内',
    'Adrien Rabiot': '拉比奥',
    'Aurelien Tchouameni': '琼阿梅尼',
    'Warren Zaire-Emery': '扎伊尔·埃梅里',
    'Maghnes Akliouche': '阿克利乌舍',
    'Bradley Barcola': '巴尔科拉',
    'Rayan Cherki': '谢尔基',
    'Ousmane Dembele': '登贝莱',
    'Desire Doue': '杜埃',
    'Jean-Philippe Mateta': '马特塔',
    'Kylian Mbappe': '姆巴佩',
    'Michael Olise': '奥利塞',
    'Marcus Thuram': '图拉姆',
    # England
    'Jordan Pickford': '乔丹·皮克福德',
    'Dean Henderson': '迪恩·亨德森',
    'James Trafford': '詹姆斯·特拉福德',
    'Reece James': '里斯·詹姆斯',
    'Ezri Konsa': '埃兹里·孔萨',
    'Jarell Quansah': '贾雷尔·宽萨',
    'John Stones': '约翰·斯通斯',
    'Marc Guehi': '马克·格伊',
    'Dan Burn': '丹·伯恩',
    "Nico O'Reilly": '尼科·奥赖利',
    'Djed Spence': '杰德·斯彭斯',
    'Tino Livramento': '蒂诺·利夫拉门托',
    'Declan Rice': '德克兰·赖斯',
    'Elliot Anderson': '埃利奥特·安德森',
    'Kobbie Mainoo': '科比·梅努',
    'Jordan Henderson': '乔丹·亨德森',
    'Morgan Rogers': '摩根·罗杰斯',
    'Jude Bellingham': '裘德·贝林厄姆',
    'Eberechi Eze': '埃贝雷奇·埃泽',
    'Harry Kane': '哈里·凯恩',
    'Ivan Toney': '伊万·托尼',
    'Ollie Watkins': '奥利·沃特金斯',
    'Bukayo Saka': '布卡约·萨卡',
    'Marcus Rashford': '马库斯·拉什福德',
    'Anthony Gordon': '安东尼·戈登',
    'Noni Madueke': '诺尼·马杜埃凯',
    # USA
    'Chris Brady': '克里斯·布雷迪',
    'Matt Freese': '马特·弗里兹',
    'Matt Turner': '马特·特纳',
    'Max Arfsten': '马克斯·阿夫斯滕',
    'Sergino Dest': '塞吉诺·德斯特',
    'Alex Freeman': '亚历克斯·弗里曼',
    'Mark McKenzie': '马克·麦肯齐',
    'Tim Ream': '蒂姆·里姆',
    'Chris Richards': '克里斯·理查兹',
    'Antonee Robinson': '安东尼·罗宾逊',
    'Miles Robinson': '米尔斯·罗宾森',
    'Joe Scally': '乔·斯卡利',
    'Auston Trusty': '奥斯顿·托斯蒂',
    'Tyler Adams': '泰勒·亚当斯',
    'Sebastian Berhalter': '塞巴斯蒂安·贝哈尔特',
    'Weston McKennie': '韦斯顿·麦肯尼',
    'Gio Reyna': '乔·雷纳',
    'Cristian Roldan': '克里斯蒂安·罗尔丹',
    'Malik Tillman': '马利克·蒂尔曼',
    'Brenden Aaronson': '布伦登·阿隆森',
    'Folarin Balogun': '福拉林·巴洛贡',
    'Ricardo Pepi': '里卡多·佩皮',
    'Christian Pulisic': '克里斯蒂安·普利西奇',
    'Tim Weah': '蒂莫西·维亚',
    'Haji Wright': '哈吉·赖特',
    'Alejandro Zendejas': '亚历杭德罗·赞德哈斯',
    # Argentina
    'Emiliano Martinez': '埃米利亚诺·马丁内斯',
    'Juan Musso': '胡安·穆索',
    'Geronimo Rulli': '赫罗尼莫·鲁利',
    'Leonardo Balerdi': '莱昂纳多·巴莱尔迪',
    'Lisandro Martinez': '利桑德罗·马丁内斯',
    'Facundo Medina': '法昆多·梅迪纳',
    'Nahuel Molina': '纳韦尔·莫利纳',
    'Gonzalo Montiel': '冈萨洛·蒙铁尔',
    'Nicolas Otamendi': '尼古拉斯·奥塔门迪',
    'Cristian Romero': '克里斯蒂安·罗梅罗',
    'Nicolas Tagliafico': '尼古拉斯·塔利亚菲科',
    'Valentin Barco': '巴伦廷·巴尔科',
    'Rodrigo De Paul': '罗德里戈·德保罗',
    'Enzo Fernandez': '恩佐·费尔南德斯',
    'Giovani Lo Celso': '乔瓦尼·洛塞尔索',
    'Alexis Mac Allister': '亚历克西斯·麦卡利斯特',
    'Exequiel Palacios': '埃塞基耶尔·帕拉西奥斯',
    'Leandro Paredes': '莱安德罗·帕雷德斯',
    'Thiago Almada': '蒂亚戈·阿尔马达',
    'Julian Alvarez': '胡利安·阿尔瓦雷斯',
    'Nicolas Gonzalez': '尼古拉斯·冈萨雷斯',
    'Jose Manuel Lopez': '何塞·曼努埃尔·洛佩斯',
    'Lautaro Martinez': '劳塔罗·马丁内斯',
    'Lionel Messi': '利昂内尔·梅西',
    'Nicolas Paz': '尼科·帕斯',
    'Giuliano Simeone': '朱利亚诺·西蒙尼',
    # Portugal
    'Diogo Costa': '迪奥戈·科斯塔',
    'Jose Sa': '若泽·萨',
    'Rui Silva': '鲁伊·席尔瓦',
    'Ricardo Velho': '里卡多·韦略',
    'Diogo Dalot': '达洛特',
    'Matheus Nunes': '努内斯',
    'Nelson Semedo': '塞梅多',
    'Joao Cancelo': '坎塞洛',
    'Nuno Mendes': '门德斯',
    'Goncalo Inacio': '伊纳西奥',
    'Renato Veiga': '韦加',
    'Ruben Dias': '鲁本·迪亚斯',
    'Tomas Araujo': '托马斯·阿劳霍',
    'Ruben Neves': '鲁本·内维斯',
    'Samuel Costa': '萨穆·科斯塔',
    'Joao Neves': '若昂·内维斯',
    'Vitinha': '维蒂尼亚',
    'Bruno Fernandes': '布鲁诺·费尔南德斯',
    'Bernardo Silva': '贝尔纳多·席尔瓦',
    'Joao Felix': '菲利克斯',
    'Francisco Trincao': '特林康',
    'Francisco Conceicao': '孔塞桑',
    'Pedro Neto': '内托',
    'Rafael Leao': '莱奥',
    'Goncalo Guedes': '格德斯',
    'Goncalo Ramos': '拉莫斯',
    'Cristiano Ronaldo': 'C罗',
    # Mexico
    'Carlos Acevedo': '卡洛斯·阿塞韦多',
    'Guillermo Ochoa': '吉列尔莫·奥乔亚',
    'Raul Rangel': '劳尔·兰赫尔',
    'Edson Alvarez': '埃德松·阿尔瓦雷斯',
    'Israel Reyes': '伊斯雷尔·雷耶斯',
    'Jesus Gallardo': '赫苏斯·加利亚多',
    'Johan Vasquez': '约翰·巴斯克斯',
    'Jorge Sanchez': '豪尔赫·桑切斯',
    'Mateo Chavez': '马特奥·查韦斯',
    'Alvaro Fidalgo': '阿尔瓦罗·菲达尔戈',
    'Brian Gutierrez': '布里安·古铁雷斯',
    'Erik Lira': '埃里克·利拉',
    'Gilberto Mora': '希尔韦托·莫拉',
    'Luis Romo': '路易斯·罗莫',
    'Obed Vargas': '奥贝德·巴尔加斯',
    'Orbelin Pineda': '奥韦林·皮内达',
    'Alexis Vega': '亚历克西斯·贝加',
    'Armando Gonzalez': '阿曼多·冈萨雷斯',
    'Cesar Huerta': '塞萨尔·韦尔塔',
    'Guillermo Martinez': '吉列尔莫·马丁内斯',
    'Julian Quinones': '胡利安·基尼奥内斯',
    'Raul Jimenez': '劳尔·希门尼斯',
    'Santiago Gimenez': '圣地亚哥·希门尼斯',
}

# Additional well-known player Chinese names
WELL_KNOWN = {
    # Netherlands
    'Virgil van Dijk': '菲尔吉尔·范戴克',
    'Frenkie de Jong': '弗朗基·德容',
    'Cody Gakpo': '科迪·加克波',
    'Memphis Depay': '孟菲斯·德佩',
    'Nathan Ake': '内森·阿克',
    'Denzel Dumfries': '丹泽尔·邓弗里斯',
    'Matthijs de Ligt': '马泰斯·德利赫特',
    'Teun Koopmeiners': '特恩·库普梅纳斯',
    'Donyell Malen': '唐耶尔·马伦',
    'Wout Weghorst': '沃特·韦格霍斯特',
    # Belgium
    'Kevin De Bruyne': '凯文·德布劳内',
    'Romelu Lukaku': '罗梅卢·卢卡库',
    'Thibaut Courtois': '蒂博·库尔图瓦',
    'Jeremy Doku': '杰雷米·多库',
    'Youri Tielemans': '尤里·蒂勒曼斯',
    'Leandro Trossard': '莱安德罗·特罗萨德',
    'Amadou Onana': '阿马杜·奥纳纳',
    # Croatia
    'Luka Modric': '卢卡·莫德里奇',
    'Ivan Perisic': '伊万·佩里西奇',
    'Josko Gvardiol': '约什科·格瓦迪奥尔',
    'Mateo Kovacic': '马特奥·科瓦契奇',
    'Andrej Kramaric': '安德雷·克拉马里奇',
    'Dominik Livakovic': '多米尼克·利瓦科维奇',
    # Norway
    'Erling Haaland': '埃尔林·哈兰德',
    'Martin Odegaard': '马丁·厄德高',
    'Alexander Sorloth': '亚历山大·瑟尔洛特',
    # Uruguay
    'Federico Valverde': '费德里科·巴尔韦德',
    'Ronald Araujo': '罗纳德·阿劳霍',
    'Darwin Nunez': '达尔文·努涅斯',
    # Colombia
    'James Rodriguez': '哈梅斯·罗德里格斯',
    'Luis Diaz': '路易斯·迪亚斯',
    # Japan
    'Takefusa Kubo': '久保建英',
    'Wataru Endo': '远藤航',
    'Daichi Kamada': '镰田大地',
    'Ritsu Doan': '堂安律',
    'Takehiro Tomiyasu': '富安健洋',
    'Ayase Ueda': '上田绮世',
    'Kaoru Mitoma': '三笘薰',
    'Yuto Nagatomo': '长友佑都',
    'Ko Itakura': '板仓滉',
    'Hiroki Ito': '伊藤洋辉',
    'Daizen Maeda': '前田大然',
    'Kyogo Furuhashi': '古桥亨梧',
    # South Korea
    'Heung-Min Son': '孙兴慜',
    'Min-Jae Kim': '金玟哉',
    'Kang-In Lee': '李刚仁',
    'In-Beom Hwang': '黄仁范',
    'Hee-Chan Hwang': '黄喜灿',
    # Egypt
    'Mohamed Salah': '穆罕默德·萨拉赫',
    'Omar Marmoush': '奥马尔·马尔穆什',
    # Canada
    'Alphonso Davies': '阿方索·戴维斯',
    'Jonathan David': '乔纳森·戴维',
    # Others - famous players
    'Harry Kane': '哈里·凯恩',
    'Sadio Mane': '萨迪奥·马内',
    'Nicolas Jackson': '尼古拉斯·杰克逊',
    'Mohamed Kudus': '穆罕默德·库杜斯',
    'Thomas Partey': '托马斯·帕尔特伊',
    'Inaki Williams': '伊尼亚基·威廉姆斯',
    'Jordan Ayew': '乔丹·阿尤',
    'Antoine Semenyo': '安托万·塞梅尼奥',
    'Edin Dzeko': '埃丁·哲科',
    'Sead Kolasinac': '塞亚德·科拉希纳茨',
    'Ermedin Demirovic': '埃尔梅丁·德米罗维奇',
    'Miguel Almiron': '米格尔·阿尔米隆',
    'Julio Enciso': '胡利奥·恩西索',
    'Antonio Sanabria': '安东尼奥·萨纳夫里亚',
    'Arda Guler': '阿尔达·居莱尔',
    'Hakan Calhanoglu': '哈坎·恰尔汗奥卢',
    'Kenan Yildiz': '凯南·伊尔迪兹',
    'Christian Pulisic': '克里斯蒂安·普利西奇',
    'Weston McKennie': '韦斯顿·麦肯尼',
    'Folarin Balogun': '福拉林·巴洛贡',
    'Ricardo Pepi': '里卡多·佩皮',
    'Pervis Estupinan': '佩维斯·埃斯图皮南',
    'Moises Caicedo': '莫伊塞斯·凯塞多',
    'Enner Valencia': '恩纳·瓦伦西亚',
    'Piero Hincapie': '皮耶罗·因卡皮耶',
    'Willian Pacho': '威廉·帕乔',
    'Achraf Hakimi': '阿什拉夫·哈基米',
    'Noussair Mazraoui': '努赛尔·马兹拉维',
    'Brahim Diaz': '卜拉欣·迪亚斯',
    'Sofyan Amrabat': '索菲扬·阿姆拉巴特',
    'Yassine Bounou': '亚辛·布努',
    'Nayef Aguerd': '纳耶夫·阿格尔德',
    'Hakim Ziyech': '哈基姆·齐耶赫',
    'Romain Saiss': '罗曼·赛斯',
    'Manuel Akanji': '曼努埃尔·阿坎吉',
    'Granit Xhaka': '格拉尼特·扎卡',
    'Denis Zakaria': '德尼斯·扎卡里亚',
    'Gregor Kobel': '格雷戈尔·科贝尔',
    'Breel Embolo': '布里尔·恩博洛',
    'Noah Okafor': '诺亚·奥卡福',
    'Ricardo Rodriguez': '里卡多·罗德里格斯',
    'Georges Mikautadze': '乔治斯·米卡乌塔泽',
    'Kalidou Koulibaly': '卡利杜·库利巴利',
    'Edouard Mendy': '爱德华·门迪',
    'Idrissa Gana Gueye': '伊德里萨·盖耶',
    'Pape Matar Sarr': '帕普·马塔尔·萨尔',
    'Ismaila Sarr': '伊斯梅拉·萨尔',
    'Iliman Ndiaye': '伊利曼·恩迪亚耶',
    'Assane Diao': '阿桑·迪奥',
    'Son Heung-min': '孙兴慜',
    'Mehdi Taremi': '迈赫迪·塔雷米',
    'Alireza Jahanbakhsh': '阿里雷扎·贾汉巴赫什',
    'Saman Ghoddos': '萨曼·戈多斯',
    'Saeid Ezatolahi': '赛义德·埃扎托拉希',
    'Ramin Rezaeian': '拉明·雷扎伊安',
    'Ehsan Hajsafi': '埃赫桑·哈吉萨菲',
    'Viktor Gyokeres': '维克托·约克雷斯',
    'Alexander Isak': '亚历山大·伊萨克',
    'Anthony Elanga': '安东尼·埃兰加',
    'Dejan Kulusevski': '德扬·库卢塞夫斯基',
    'Emiliano Martinez': '埃米利亚诺·马丁内斯',
    'Cristian Romero': '克里斯蒂安·罗梅罗',
    'Nicolas Otamendi': '尼古拉斯·奥塔门迪',
    'Lisandro Martinez': '利桑德罗·马丁内斯',
    'Nahuel Molina': '纳韦尔·莫利纳',
    'Gonzalo Montiel': '冈萨洛·蒙铁尔',
    'Rodrigo De Paul': '罗德里戈·德保罗',
    'Enzo Fernandez': '恩佐·费尔南德斯',
    'Alexis Mac Allister': '亚历克西斯·麦卡利斯特',
    'Leandro Paredes': '莱安德罗·帕雷德斯',
    'Lautaro Martinez': '劳塔罗·马丁内斯',
    'Julian Alvarez': '胡利安·阿尔瓦雷斯',
    'Lionel Messi': '利昂内尔·梅西',
    'Angel Di Maria': '安赫尔·迪马利亚',
    'Paulo Dybala': '保罗·迪巴拉',
    'Chris Wood': '克里斯·伍德',
    'Riyad Mahrez': '里亚德·马赫雷斯',
    'Houssem Aouar': '侯塞姆·奥瓦尔',
    'Ramy Bensebaini': '拉米·本塞拜尼',
    'Aissa Mandi': '艾萨·曼迪',
    'Islam Slimani': '伊斯兰·斯利马尼',
    'Ivan Rakitic': '伊万·拉基蒂奇',
    'Mario Pasalic': '马里奥·帕萨利奇',
    'Ante Budimir': '安特·布迪米尔',
    'Bruno Petkovic': '布鲁诺·佩特科维奇',
    'Luka Sucic': '卢卡·苏契奇',
    'Martin Baturina': '马丁·巴图里纳',
    'Dominik Livakovic': '多米尼克·利瓦科维奇',
    'Josip Sutalo': '约瑟普·舒塔洛',
    'Josip Stanisic': '约瑟普·斯塔尼西奇',
    'Borna Sosa': '博尔纳·索萨',
    'Marcelo Brozovic': '马塞洛·布罗佐维奇',
    'Mateo Kovacic': '马特奥·科瓦契奇',
    'Lovro Majer': '洛夫罗·马耶尔',
    'Andrej Kramaric': '安德雷·克拉马里奇',
    'Bruno Petkovic': '布鲁诺·佩特科维奇',
    'Mislav Orsic': '米斯拉夫·奥尔西奇',
    'Josko Gvardiol': '约什科·格瓦迪奥尔',
    'Marko Livaja': '马尔科·利瓦亚',

    # ===== New teams: Australia, Bosnia, Qatar, Switzerland, Haiti, Japan =====

    # Australia (from zhibo8)
    'Ryan': '瑞安',
    'Izzo': '保罗·伊佐',
    'Beach': '帕特里克·比奇',
    'Behich': '阿齐兹·贝希奇',
    'Bos': '乔丹·博斯',
    'Burgess': '卡梅隆·伯吉斯',
    'Circati': '亚历山德罗·西卡蒂',
    'Degenek': '米洛斯·迪基尼克',
    'Geria': '杰森·杰里亚',
    'Herrington': '卢卡斯·赫林顿',
    'Italiano': '伊塔利亚诺',
    'Souttar': '哈利·苏塔尔',
    'Trewin': '凯·特里温',
    'Devlin': '卡梅隆·德夫林',
    'Hrustic': '阿伊丁·赫鲁斯蒂奇',
    'Irvine': '杰克逊·欧文',
    'Metcalfe': '康纳·梅特卡夫',
    "Okon-Englster": '保罗·奥康-恩斯特勒',
    "O'Neill": '奥尼尔',
    'Irankunda': '伊兰昆达',
    'Leckie': '马修·莱基',
    'Mabil': '奥尔·马比尔',
    'Toure': '穆罕默德·图雷',
    'Velupilly': '尼山·韦卢皮莱',
    'Volpato': '克里斯蒂安·沃尔帕托',
    'Tete Yengi': '特特·延吉',

    # Bosnia (from sohu)
    'Nikola Vasilj': '尼古拉·瓦西里',
    'Martin Zlomislic': '马丁·兹洛米斯利奇',
    'Osman Hadzikic': '奥斯曼·哈季基奇',
    'Amar Dedic': '阿马尔·德蒂奇',
    'Nihad Mujakic': '尼哈德·穆亚基奇',
    'Nikola Katic': '尼克拉·卡蒂奇',
    'Tarik Muharemovic': '塔里克·穆哈雷莫维奇',
    'Stjepan Radeljic': '斯捷潘·拉德里季奇',
    'Dennis Hadzikadunic': '丹尼斯·哈迪卡杜尼克',
    'Nidal Celik': '尼达尔·切利克',
    'Amir Hadziahmetovic': '阿米尔·哈吉艾哈迈托维奇',
    'Ivan Sunjic': '伊万·舒尼奇',
    'Ivan Basic': '伊万·巴希奇',
    'Dzenis Burnic': '泽尼斯·布尔尼奇',
    'Ermin Mahmic': '埃尔明·马赫米奇',
    'Benjamin Tahirovic': '本亚明·塔希罗维奇',
    'Amar Memic': '阿马尔·梅米奇',
    'Armin Gigovic': '阿尔明·吉戈维奇',
    'Kerim Alajbegovic': '克里姆·阿拉伊贝戈维奇',
    'Esmir Bajraktarevic': '埃斯米尔·巴里亚克塔雷维奇',
    'Jovo Lukic': '约沃·卢基奇',
    'Samed Bazdar': '萨梅德·巴日达尔',
    'Haris Tabakovic': '哈里斯·塔巴科维奇',

    # Qatar (from zhibo8)
    'Salah Zakaria': '萨拉赫·扎卡里亚',
    'Mahmoud Abunada': '马穆德·阿布纳德',
    'Meshaal Barsham': '梅萨尔·巴沙姆',
    'Hashmi Hussein': '阿尔·哈希米·阿尔·侯赛因',
    'Ayoub Alawi': '阿尤布·阿莱维',
    'Boualem Khoukhi': '布阿莱姆·胡希',
    'Pedro Miguel': '佩德罗·米格尔',
    'Issa Laaye': '伊萨·拉耶',
    'Lucas Mendes': '卢卡斯·门德斯',
    'Sultan Al-Brake': '苏丹·布雷克',
    'Homam Al-Amin': '霍曼·艾哈迈德',
    'Mohammed Al-Manai': '穆罕默德·马奈',
    'Jassem Jaber': '贾西姆·阿卜杜勒萨拉姆',
    'Karim Boudiaf': '卡里姆·布迪亚夫',
    'Ahmed Fathi': '艾哈迈德·法特希',
    'Abdulaziz Hatem': '阿卜杜勒阿齐兹·哈特姆',
    'Assim Madibo': '阿西姆·马迪博',
    'Tahseen Mohammed': '塔辛·穆罕默德·贾姆希德',
    'Edmilson Junior': '埃迪米森',
    'Almoez Ali': '埃莫兹·阿里',
    'Akram Afif': '阿克拉姆·阿菲夫',
    'Mohammed Muntari': '穆罕默德·蒙塔里',
    'Youssef Abdulrazzaq': '优素福·阿卜杜里萨格',
    'Ahmed Alaa': '艾哈迈德·阿拉丁',
    'Hassan Al-Haydos': '哈桑·艾尔·海多斯',
    'Ahmed Al-Janahi': '艾哈迈德·贾内希',

    # Switzerland (from zhibo8)
    'Marvin Keller': '凯勒',
    'Yvon Mvogo': '姆沃戈',
    'Nico Elvedi': '埃尔维迪',
    'Miro Muheim': '穆海姆',
    'Silvan Widmer': '威德默',
    'Luca Jaquez': '雅克',
    'Aurele Amenda': '阿曼达',
    'Eray Comert': '科默特',
    'Johan Manzambi': '曼赞比',
    'Remo Freuler': '弗鲁勒',
    'Ardon Jashari': '亚沙里',
    'Djibril Sow': '索乌',
    'Michel Aebischer': '埃比舍尔',
    'Fabian Rieder': '法比安·里德',
    'Ruben Vargas': '鲁本·巴尔加斯',
    'Dan Ndoye': '恩多耶',
    'Zeki Amdouni': '阿姆杜尼',
    'Cedric Itten': '塞德里克·埃滕',
    'Christian Fassnacht': '法斯纳赫特',

    # Haiti (from zhibo8)
    'Johnny Placide': '普拉西德',
    'Alexandre Pierre': '亚历山大·皮埃尔',
    'Josue Duverger': '杜弗格',
    'Carlens Arcus': '阿库斯',
    'Wilguens Pauguain': '波甘',
    'Duke Lacroix': '杜克·拉克鲁瓦',
    'Martin Experience': '埃克斯派瑞斯',
    'Jean-Kevin Duverne': '杜维内',
    'Ricardo Ade': '里卡多·阿德',
    'Hannes Delcroix': '德克鲁瓦',
    'Keeto Thermoncy': '泰尔蒙西',
    'Leverton Pierre': '莱弗顿·皮埃尔',
    'Carl-Fred Sainthe': '桑泰',
    'Jean-Jacques Danley': '丹利',
    'Jean-Ricner Bellegarde': '贝莱加德',
    'Pierre Woodenski': '伍登斯基',
    'Dominique Simon': '多米尼克·西蒙',
    'Louicius Deedson': '迪德森',
    'Ruben Providence': '普罗维登斯',
    'Josue Casimir': '卡西米尔',
    'Derrick Etienne': '艾蒂安',
    'Wilson Isidor': '伊西多',
    'Duckens Nazon': '纳宗',
    'Frantzdy Pierrot': '皮埃罗',
    'Yassin Fortune': '福尔蒂内',
    'Lenny Joseph': '约瑟夫',

    # Japan - remaining players (from zhibo8)
    'Tomoki Hayakawa': '早川友基',
    'Keisuke Osako': '大迫敬介',
    'Zion Suzuki': '铃木彩艳',
    'Shogo Taniguchi': '谷口彰悟',
    'Tsuyoshi Watanabe': '渡边刚',
    'Ayumu Seko': '濑古步梦',
    'Yukinari Sugawara': '菅原由势',
    'Junosuke Suzuki': '铃木淳之介',
    'Junya Ito': '伊东纯也',
    'Koki Ogawa': '小川航基',
    'Ao Tanaka': '田中碧',
    'Kaishu Sano': '佐野海舟',
    'Keito Nakamura': '中村敬斗',
    'Ito Suzuki': '铃木唯人',
    'Kento Shiode': '盐贝健人',
    'Keisuke Goto': '后藤启介',

    # Morocco (from zhibo8)
    'Munir Mohamedi': '穆尼尔·穆罕默德',
    'Ahmed Tagnaouti': '塔格诺提',
    'Anass Salah-Eddine': '萨拉赫·埃丁',
    'Youssef Belammari': '贝拉马里',
    'Chadi Riad': '里亚德',
    'Issa Diop': '迪奥普',
    'Redouane Halhal': '哈尔哈尔',
    'Zakaria El Ouahdi': '埃尔瓦赫迪',
    'Samir El Mourabet': '穆拉贝特',
    'Ayyoub Bouaddi': '布阿迪',
    'Neil El Aynaoui': '艾纳维',
    'Azzedine Ounahi': '奥纳西',
    'Bilal El Khannouss': '埃尔哈努斯',
    'Ismael Saibari': '塞巴里',
    'Abdessamad Ezzalzouli': '埃扎卢利',
    'Chemsdine Talbi': '塔尔比',
    'Soufiane Rahimi': '拉希米',
    'Ayoub El Kaabi': '卡埃比',
    'Yassine Gessime': '亚辛',
    'Ayoub Amaimouni-Echghouyabe': '阿迈穆尼-埃奇古亚布',

    # ===== Scotland (from zhibo8) =====
    'Craig Gordon': '克雷格·戈登',
    'Angus Gunn': '安格斯·冈恩',
    'Liam Kelly': '利亚姆·凯利',
    'Grant Hanley': '格兰特·汉利',
    'Jack Hendry': '杰克·亨德利',
    'Aaron Hickey': '亚伦·希基',
    'Dom Hyam': '多米尼克·海厄姆',
    'Scott McKenna': '斯科特·麦肯纳',
    'Nathan Patterson': '内森·帕特森',
    'Anthony Ralston': '安东尼·拉尔斯顿',
    'Andy Robertson': '安迪·罗伯逊',
    'John Souttar': '约翰·苏塔尔',
    'Kieran Tierney': '基兰·蒂尔尼',
    'Ryan Christie': '瑞安·克里斯蒂',
    'Findlay Curtis': '芬德利·库蒂斯',
    'Lewis Ferguson': '刘易斯·弗格森',
    'Ben Gannon-Doak': '本·多克',
    'Tyler Fletcher': '泰勒·弗莱彻',
    'John McGinn': '约翰·麦金',
    'Kenny McLean': '肯尼·麦克莱恩',
    'Scott McTominay': '斯科特·麦克托米奈',
    'Che Adams': '切·亚当斯',
    'Lyndon Dykes': '林顿·戴克斯',
    'George Hirst': '乔治·赫斯特',
    'Lawrence Shankland': '劳伦斯·尚克兰',
    'Ross Stewart': '罗斯·斯图尔特',

    # ===== Paraguay (from zhibo8) =====
    'Roberto Junior Fernandez': '加蒂托·费尔南德斯',
    'Orlando Gill': '奥兰多·吉尔',
    'Gaston Olveira': '加斯东·奥利韦拉',
    'Omar Alderete': '奥马尔·阿尔德雷特',
    'Junior Alonso': '儒尼奥尔·阿隆索',
    'Fabian Balbuena': '法比安·巴尔武埃纳',
    'Juan Jose Caceres': '胡安·卡塞雷斯',
    'Jose Canale': '何塞·卡纳莱',
    'Gustavo Gomez': '古斯塔沃·戈麦斯',
    'Alexandro Maidana': '亚历杭德罗·迈达纳',
    'Gustavo Velazquez': '古斯塔沃·贝拉斯克斯',
    'Damian Bobadilla': '达米安·博瓦迪利亚',
    'Gustavo Caballero': '古斯塔沃·卡瓦列罗',
    'Andres Cubas': '安德烈斯·库巴斯',
    'Matias Galarza': '马蒂亚斯·加拉尔萨',
    'Diego Gomez': '迭戈·戈麦斯',
    'Mauricio Magalhaes': '毛里西奥',
    'Briaian Ojeda': '布拉扬·奥赫达',
    'Alejandro Romero': '亚历杭德罗·罗梅罗·加马拉',
    'Gabriel Avalos': '加夫列尔·阿瓦洛斯',
    'Alex Arce': '亚历克斯·阿尔塞',
    'Isidro Pitta': '伊西德罗·皮塔',
    'Ramon Sosa': '拉蒙·索萨',

    # ===== Turkey (from zhibo8) =====
    'Ugurcan Cakir': '乌古尔坎·恰基尔',
    'Altay Bayindir': '阿勒泰·巴延德尔',
    'Mert Gunok': '默特·古诺克',
    'Ferdi Kadioglu': '卡迪奥卢',
    'Merih Demiral': '德米拉尔',
    'Zeki Celik': '泽基·切利克',
    'Ozan Kabak': '卡巴克',
    'Mert Muldur': '默特·穆尔杜',
    'Abdulkerim Bardakci': '阿卜杜勒克里姆·巴尔达克彻',
    'Eren Elmali': '埃伦·埃尔马利',
    'Caglar Soyuncu': '瑟云聚',
    'Samet Akaydin': '萨梅特·阿卡丁',
    'Can Uzun': '乌尊',
    'Orkun Kokcu': '奥尔奎·科克库',
    'Ismail Yuksek': '伊斯梅尔·尤克塞克',
    'Kaan Ayhan': '卡安·艾汗',
    'Salih Ozcan': '厄兹詹',
    'Baris Alper Yilmaz': '巴勒什·阿尔佩尔·伊尔马兹',
    'Kerem Akturkoglu': '阿克蒂尔克奥卢',
    'Yunus Akgun': '尤努斯·阿克金',
    'Oguz Aydin': '奥古兹·艾丁',
    'Deniz Gul': '德尼兹·居尔',
    'Irfan Can Kahveci': '卡维奇',

    # ===== Curacao (from zhibo8) =====
    'Tyrick Bodak': '泰里克·波达克',
    'Trevor Doornbusch': '特雷弗·杜恩布什',
    'Eloy Room': '埃洛伊·罗姆',
    'Riechedly Bazoer': '里奇德利·巴佐尔',
    'Joshua Brenet': '乔舒亚·布勒内',
    'Roshon van Eijma': '罗申·范艾玛',
    'Sherel Floranus': '谢雷尔·弗洛拉努斯',
    'Deveron Fonville': '德韦伦·丰维尔',
    'Jurien Gaari': '朱利安·加里',
    'Armando Obispo': '阿曼多·奥比斯波',
    'Shurandy Sambo': '舒兰迪·桑博',
    'Juninho Bacuna': '儒尼尼奥·巴库纳',
    'Leandro Bacuna': '莱安多·巴库纳',
    'Livano Comenencia': '利瓦诺·科梅内西亚',
    'Kevin Felida': '凯文·费利达',
    'Ar\'Jany Martha': '阿亚尼·马尔塔',
    'Tyrese Noslin': '泰瑞斯·诺斯林',
    'Godfried Roemeratoe': '戈德弗里德·罗默拉托',
    'Jeremy Antonisse': '杰里米·安东尼斯',
    'Tahith Chong': '陈达毅',
    'Kenji Gorre': '肯吉·戈雷',
    'Sontje Hansen': '松切·汉森',
    'Gervane Kastaneer': '赫尔瓦内·卡斯塔内尔',
    'Brandley Kuwas': '库沃斯',
    'Jurgen Locadia': '于尔根·洛卡迪亚',
    'Jearl Margaritha': '马格里沙',

    # ===== Ecuador (from zhibo8/TBD) =====
    'Hernan Galindez': '埃尔南·加林德斯',
    'Moises Ramirez': '莫伊塞斯·拉米雷斯',
    'Gonzalo Valle': '贡萨洛·巴列',
    'Felix Torres': '费利克斯·托雷斯',
    'Joel Ordonez': '霍埃尔·奥多涅斯',
    'Jackson Porozo': '杰克逊·波罗佐',
    'Angelo Preciado': '安赫洛·普雷西亚多',
    'Alan Franco': '阿兰·弗兰科',
    'Kendry Paez': '肯德里·派斯',
    'Pedro Vite': '佩德罗·维特',
    'Jordy Alcivar': '霍尔迪·阿尔西瓦尔',
    'Denil Castillo': '德尼尔·卡斯蒂略',
    'Yaimar Medina': '亚伊马尔·梅迪纳',
    'Kevin Rodriguez': '凯文·罗德里格斯',
    'Jordy Caicedo': '霍尔迪·凯塞多',
    'Nilson Angulo': '尼尔森·安古洛',
    'Anthony Valencia': '安东尼·巴伦西亚',
    'Jeremy Arevalo': '赫雷米·阿雷瓦洛',

    # ===== Ivory Coast (from zhibo8) =====
    'Yahia Fofana': '叶海亚·福法纳',
    'Mohamed Kone': '穆罕默德·科内',
    'Alban Lafont': '阿尔邦·拉丰',
    'Emmanuel Agbadou': '埃马纽埃尔·阿格巴杜',
    'Clement Akpa': '奥佩里',
    'Ousmane Diomande': '奥斯曼·迪奥曼德',
    'Guela Doue': '盖拉·杜埃',
    'Ghislain Konan': '吉兰·科南',
    'Odilon Kossounou': '奥迪隆·科索努',
    'Evan Ndicka': '埃万·恩迪卡',
    'Wilfried Singo': '威尔弗里德·辛戈',
    'Seko Fofana': '塞科·福法纳',
    'Parfait Guiagon': '帕尔费',
    'Christ Inao Oulai': '克里斯特·乌拉伊',
    'Franck Kessie': '凯西',
    'Ibrahim Sangare': '易卜拉欣·桑加雷',
    'Jean-Michael Seri': '塞里',
    'Simon Adingra': '西蒙·阿丁格拉',
    'Ange-Yoan Bonny': '博尼',
    'Amad Diallo': '阿玛德·迪亚洛',
    'Oumar Diakite': '奥马尔·迪亚基特',
    'Yan Diomande': '扬·迪奥曼德',
    'Evann Guessand': '埃万·盖桑',
    'Nicolas Pepe': '尼古拉·佩佩',
    'Bazoumana Toure': '巴祖马纳·图雷',
    'Elye Wahi': '瓦希',

    # ===== Netherlands (from zhibo8) =====
    'Bart Verbruggen': '费布吕亨',
    'Mark Flekken': '弗莱肯',
    'Robin Roefs': '鲁夫斯',
    'Jan Paul van Hecke': '范赫克',
    'Micky van de Ven': '范德芬',
    'Jorrel Hato': '哈托',
    'Jurrien Timber': '朱利安·廷伯',
    'Quinten Timber': '昆滕·廷伯',
    'Tijjani Reijnders': '赖因德斯',
    'Justin Kluivert': '克鲁伊维特',
    'Ryan Gravenberch': '赫拉芬贝赫',
    'Marten de Roon': '德罗恩',
    'Guus Til': '蒂尔',
    'Mats Weiffer': '马茨·维费尔',
    'Brian Brobbey': '布罗比',
    'Noa Lang': '诺阿·朗',
    'Crysencio Summerville': '萨默维尔',

    # ===== Sweden (from zhibo8) =====
    'Viktor Johansson': '维克多·约翰松',
    'Kristoffer Nordfeldt': '克里斯托弗·诺德菲尔特',
    'Jacob Widell Zetterstrom': '雅各布·维德尔·泽特斯特伦',
    'Hjalmar Ekdal': '埃克达尔',
    'Gabriel Gudmundsson': '加布里埃尔·古德蒙德森',
    'Isak Hien': '伊萨克·希恩',
    'Emil Holm': '赫尔曼·约翰松',
    'Gustaf Lagerbielke': '古斯塔夫·拉格比尔克',
    'Victor Lindelof': '林德洛夫',
    'Erik Smith': '埃里克·史密斯',
    'Carl Starfelt': '卡尔·斯塔费尔特',
    'Elliot Stroud': '埃利奥特·斯特劳德',
    'Daniel Svensson': '丹尼尔·斯文松',
    'Taha Ali': '塔哈·阿里',
    'Yasin Ayari': '亚辛·阿亚里',
    'Lucas Bergvall': '贝里瓦尔',
    'Jesper Karlstrom': '加斯佩·卡尔斯特罗姆',
    'Ken Sema': '肯·塞马',
    'Mattias Svanberg': '马蒂亚斯·斯万贝里',
    'Besfort Zeneli': '贝斯福特·泽内利',
    'Alexander Bernhardsson': '亚历山大·伯恩哈德森',
    'Gustaf Nilsson': '古斯塔夫·尼尔松',
    'Benjamin Nygren': '本杰明·尼格伦',

    # ===== Tunisia (from zhibo8) =====
    'Sabri Ben Hessen': '本·黑森',
    'Abdelmouhib Chamakh': '查马克',
    'Amenallah Memmiche': '达门',
    'Montassar Talbi': '塔尔比',
    'Dylan Bronn': '迪兰·布隆',
    'Mootez Zaddem': '雷基克',
    'Rayan Arroussi': '阿鲁斯',
    'Wajdi Kechrida': '齐卡维',
    'Youssef Valery': '优素福·瓦莱里',
    'Nader Neffati': '内法蒂',
    'Ali Abdi': '阿布迪',
    'Hamza Mathlouthi': '哈米达',
    'Ellyes Skhiri': '斯希里',
    'Mootez Zaddem': '马穆德',
    'Rani Khedira': '拉尼·赫迪拉',
    'Hannibal Mejbri': '汉尼拔·梅布里',
    'Wajdi Sahli': '斯里曼尼',
    'Moez Ouannes': '乌安奈斯',
    'Nader Ghandri': '哈尔比',
    'Elyes Achouri': '阿亚里',
    'Sayfallah Ltaief': '图内克提',
    'Elias Achouri': '阿乔里',
    'Firas Chaouat': '查瓦',
    'Hamza Masouri': '马斯图里',
    'Firas Ben Saad': '萨德',
    'Nizar Eloumi': '埃卢米',

    # ===== Belgium (from zhibo8) =====
    'Maarten Vandevoordt': '拉门斯',
    'Matz Sels': '塞伊斯',
    'Tibaut Courtois': '库尔图瓦',
    'Timothy Castagne': '卡斯塔涅',
    'Zeno Debast': '德巴斯特',
    'Maxim De Cuyper': '德屈佩',
    'Koni De Winter': '德温特',
    'Brandon Mechele': '梅赫莱',
    'Thomas Meunier': '穆尼耶',
    'Jorthy Mokio': '恩戈伊',
    'Joordje Petris': '泰特',
    'Hans Vanaken': '瓦纳肯',
    'Axel Witsel': '维特塞尔',
    'Nicolas Raskin': '拉斯坎',
    'Charles De Ketelaere': '德凯特拉雷',
    'Matias Fernandez-Pardo': '马蒂亚斯·费尔南德斯-帕尔多',
    'Dodi Lukebakio': '卢克巴基奥',
    'Diego Moreira': '迭戈·莫雷拉',
    'Alexis Saelemaekers': '萨勒马科尔斯',

    # ===== Egypt (from zhibo8) =====
    'Mohamed El Shenawy': '穆罕默德·谢纳维',
    'Mostafa Shoeib': '肖贝尔',
    'Mohamed Sobhi': '索利曼',
    'Mohamed Abdelfattah': '穆罕默德·阿拉',
    'Mohamed Hany': '穆罕默德·哈尼',
    'Tarek Alaa': '塔里克·阿拉',
    'Hamdy Fathy': '哈姆迪·法蒂',
    'Ramy Rabia': '拉米·拉比亚',
    'Mahmoud Ibrahim': '易卜拉欣',
    'Mohamed Abdelmaguid': '阿卜杜勒马吉德',
    'Mohamed Abdelmonem': '阿卜杜勒穆奈姆',
    'Ahmed Fatouh': '法图赫',
    'Mohamed Hafez': '哈菲兹',
    'Marwan Attia': '阿提亚',
    'Mohannad Lashin': '穆罕纳德·拉辛',
    'Nabil Emad': '纳比勒·伊马德',
    'Mahmoud Saber': '萨比尔',
    'Zizo': '齐佐',
    'Mahmoud Trezeguet': '特雷泽盖',
    'Emam Ashour': '阿舒尔',
    'Mostafa Ziko': '穆斯塔法·济科',
    'Osama Adel': '阿德尔',
    'Haitham Hassan': '海瑟姆·哈桑',
    'Omar Marmoush': '马尔穆什',
    'Abdelrahman Abdelkarim': '阿卜杜勒卡里姆',

    # ===== Iran (from zhibo8) =====
    'Alireza Beiranvand': '阿里雷萨·贝兰万德',
    'Hossein Hosseini': '侯赛因·侯赛尼',
    'Payam Niazmand': '帕亚姆·尼亚曼德',
    'Danyal Eri': '达尼亚尔·埃里',
    'Saman Ghoddos': '萨曼·戈多斯',
    'Saleh Hardani': '萨利赫·哈达尼',
    'Hossein Kanaanizadegan': '侯赛因·卡纳尼',
    'Shoja Khalilzadeh': '舒贾·哈利勒扎德',
    'Milad Mohammadi': '米拉德·穆罕默迪',
    'Ali Nemati': '阿里·内马蒂',
    'Roozbeh Cheshmi': '鲁兹贝·切什米',
    'Saeid Ezatolahi': '赛义德·埃扎托拉希',
    'Mehdi Ghayedi': '迈赫迪·加耶迪',
    'Mohammad Ghorbani': '穆罕默德·戈尔巴尼',
    'Mohammad Mohebi': '穆罕默德·莫赫比',
    'Amirmohammad Razaghnia': '阿米尔穆罕默德·拉扎格尼亚',
    'Mehdi Torabi': '梅迪·托拉比',
    'Ali Alipour': '阿里·阿利普尔',
    'Dennis Eckert': '丹尼斯·埃克特',
    'Amirhossein Hosseinzadeh': '阿米尔侯赛因·侯赛因扎德',
    'Shahriyar Moghanlou': '沙赫里亚尔·莫汉卢',

    # ===== New Zealand (from zhibo8) =====
    'Max Crocombe': '马克斯·克罗科姆',
    'Alex Paulsen': '亚历克斯·保尔森',
    'Michael Woud': '迈克尔·沃德',
    'Tim Payne': '蒂姆·佩恩',
    'Francis De Vries': '弗朗西斯·德弗里斯',
    'Bindon Taylor': '宾登·泰勒',
    'Mitchell Boxall': '米切尔·伯克萨尔',
    'Dalmeny Kambayashi': '卡卡塞',
    'Nando Pijnaker': '南多·派纳克',
    'Finn Surman': '苏尔曼',
    'Ben Old': '本·奥尔德',
    'Karan Elliot': '卡兰·埃利奥特',
    'Tommy Smith': '汤米·史密斯',
    'Joe Bell': '乔·贝尔',
    'Matthew Garbett': '马修·加伯特',
    'Marko Stamenic': '马科·斯特梅克',
    'Sarpreet Singh': '萨普里特·辛格',
    'Alex Rufer': '鲁费',
    'Callum McCowatt': '卡勒姆·麦考瓦特',
    'Ryan Thomas': '瑞安·托马斯',
    'Lachlan Bayliss': '拉克兰·贝利斯',
    'Elijah Just': '伊利亚·贾斯特',
    'Alexander Babbalaouse': '巴巴洛塞斯',
    'Ben Waine': '本·韦恩',
    'Jesse Randall': '杰西·兰德尔',

    # ===== Cape Verde (from zhibo8) =====
    'Vozinha': '沃津哈',
    'Marcio Rosa': '马西奥·罗萨',
    'Carlos Dos Santos': '卡洛斯·多斯·桑托斯',
    'Steven Moreira': '史蒂芬·莫雷拉',
    'Wagner Pina': '瓦格纳·皮纳',
    'Joao Paulo Moreira': '若昂·保罗·莫雷拉·费尔南德斯',
    'Sidney Lopes Cabral': '西德尼·洛佩斯·卡布拉尔',
    'Logan Costa': '洛根·科斯塔',
    'Roberto Lopes': '罗拔图·洛佩兹',
    'Kelvin Pires': '凯尔文·皮雷斯',
    'Topira': '托皮拉',
    'Dine Borges': '迪内-博格斯',
    'Jamiro Monteiro': '杰米罗·蒙特罗',
    'Telmo Arcanjo': '特尔莫·阿尔坎若',
    'Yannick Semedo': '亚尼克·塞梅多',
    'Laros Duarte': '拉罗斯·杜亚特',
    'Dorrothe Duarte': '德罗伊·杜亚特',
    'Kevin Pina': '凯文·皮纳',
    'Ryan Mendes': '瑞安·门德斯',
    'Willy Semedo': '威利·塞梅多',
    'Garry Rodrigues': '加里·罗德里格斯',
    'Jovane Cabral': '久瓦尼·卡布拉尔',
    'Nuno Da Costa': '努诺·达科斯塔',
    'Dailon Livramento': '戴隆·利夫拉门托',
    'Gilson Benchimol': '吉尔森·本希莫尔',
    'Helio Varela': '海里奥·瓦雷拉',

    # ===== Saudi Arabia (from zhibo8) =====
    'Mohammed Al-Owais': '阿洛瓦伊斯',
    'Nawaf Al-Aqidi': '阿奇迪',
    'Ahmed Al-Kassar': '卡萨尔',
    'Saud Abdulhamid': '阿卜杜勒哈米德',
    'Awn Al-Salali': '塔克里',
    'Ali Al-Bulayhi': '阿姆里',
    'Hassan Tambakti': '坦巴克蒂',
    'Bander Al-Ahmari': '拉贾米',
    'Nawaf Al-Qadish': '卡迪什',
    'Mohammed Al-Breik': '哈尔比',
    'Eid Al-Muwallad': '马拉希',
    'Khalid Al-Shamrani': '阿布沙马特',
    'Mohammed Al-Johani': '阿尔乔汉尼',
    'Nasser Al-Dawsari': '纳赛尔·多萨里',
    'Mohamed Kanno': '卡努',
    'Abdullah Al-Khaibari': '哈巴利',
    'Faisal Al-Bishr': '布沙尔',
    'Abdullah Al-Hamdan': '哈姆丹',
    'Abdulaziz Al-Bishi': '加纳姆',
    'Firas Al-Buraikan': '布赖坎',
    'Saleh Al-Shehri': '谢赫里',
    'Talal Haji': '赫吉',
    'Ali Al-Juwayr': '朱瓦伊尔',
    'Fahad Al-Muwallad': '曼达什',
    'Ayman Yahya': '叶海亚',
    'Salem Al-Dawsari': '萨利姆·多萨里',

    # ===== Uruguay (from zhibo8) =====
    'Sergio Rochet': '塞尔吉奥·罗切特',
    'Fernando Muslera': '费尔南多·穆斯莱拉',
    'Santiago Mele': '圣地亚哥·梅莱',
    'Guillermo Varela': '吉列尔莫·瓦雷拉',
    'Jose Maria Gimenez': '何塞·马里亚·吉梅内斯',
    'Santiago Bueno': '圣地亚哥·布埃诺',
    'Sebastian Caceres': '塞巴斯蒂安·卡塞雷斯',
    'Matias Olivera': '马蒂亚斯·奥利维拉',
    'Joaquin Piquerez': '华金·皮克雷斯',
    'Matias Vina': '马蒂亚斯·比尼亚',
    'Manuel Ugarte': '曼努埃尔·乌加特',
    'Emiliano Martinez': '埃米里亚诺·马丁内斯',
    'Rodrigo Bentancur': '罗德里戈·本坦库尔',
    'Agustin Canobbio': '奥古斯汀·卡诺比奥',
    'Juan Sanabria': '胡安·萨纳布里亚',
    'Giorgian De Arrascaeta': '乔治亚·德·阿拉斯凯塔',
    'Nicolas De La Cruz': '尼古拉斯·德拉克鲁兹',
    'Rodrigo Salazar': '罗德里戈·萨拉萨尔',
    'Facundo Pellistri': '法昆多·佩利斯特里',
    'Maximiliano Araujo': '马克西米利亚诺·阿劳霍',
    'Brian Rodriguez': '布莱恩·罗德里格斯',
    'Luis Suarez': '路易斯·苏亚雷斯',
    'Cristian Olivera': '阿吉雷',
    'Matias Arezo': '比尼亚斯',

    # ===== Norway (from zhibo8) =====
    'Orjan Nyland': '伊恩·尼兰德',
    'Egil Selvik': '塞尔维克',
    'Magnus Tveit Sand': '唐维克·桑德',
    'Kristoffer Ajer': '克里斯托弗·阿耶尔',
    'Fredrik Bjorkan': '弗雷德里克·比约坎',
    'Henrik Falch': '亨里克·法尔切纳',
    'Sondre Langas': '桑德雷·朗格斯',
    'Torbjorn Heggem': '托比约恩·赫格姆',
    'Marcus Pedersen': '马库斯·霍姆格伦·佩德森',
    'Julian Ryerson': '朱利安·莱尔森',
    'David Wolfe': '戴维·沃尔费',
    'Leo Ostigard': '莱奥·厄斯蒂高',
    'Fredrik Aursnes': '奥瑟斯',
    'Patrick Berg': '帕特里克·伯格',
    'Sander Berge': '桑德·博格',
    'Oscar Bobb': '鲍勃',
    'Jens Petter Hauge': '海于格',
    'Antonio Nusa': '努萨',
    'Theo Hjulsager': '谢尔德鲁普',
    'Mathias Torset': '托尔斯比',
    'Kristian Thorstvedt': '克里斯蒂安·托斯特维特',
    'Jorgen Strand Larsen': '拉尔森',

    # ===== Senegal (from zhibo8) =====
    'Edouard Mendy': '爱德华·门迪',
    'Mory Diaw': '莫里·迪奥',
    'Yewann Diouf': '耶旺恩·迪乌夫',
    'Moussa Niakhate': '穆萨·尼亚卡泰',
    'Mamadou Sarr': '马马杜·萨尔',
    'Abdoulaye Seck': '阿卜杜拉耶·塞克',
    'Krepin Diatta': '克雷平·迪亚塔',
    'Antoine Mendy': '安托万·门迪',
    'El Hadji Malick Diouf': '埃尔·哈吉·马利克·迪乌夫',
    'Ismail Jakobs': '伊斯梅尔·雅各布斯',
    'Pape Gueye': '帕佩·盖耶',
    'Lamine Camara': '拉明·卡马拉',
    'Habib Diarra': '哈比卜·迪亚拉',
    'Pathé Ciss': '帕特·西斯',
    'Pape Sarr': '帕佩·萨尔',
    'Bara Sampoko Ndiaye': '巴拉·萨波科·恩迪亚耶',
    'Ismaila Sarr': '伊斯梅拉·萨尔',
    'Iliman Ndiaye': '伊利曼·恩迪亚耶',
    'Assane Diao': '阿萨尼·迪奥',
    'Ibrahima Mbaye': '易卜拉欣·姆巴耶',
    'Bamba Dieng': '班巴·迪昂',
    'Cherif Ndiaye': '谢里夫·恩迪亚耶',

    # ===== Iraq (from zhibo8) =====
    'Fahad Talib': '法哈德·塔利卜',
    'Ahmed Basil': '艾哈迈德·巴西勒',
    'Jalal Hassan': '贾拉尔·哈桑',
    'Hussein Ali': '侯赛因·阿里',
    'Manaf Younis': '马纳夫·尤尼斯',
    'Zaid Tahseen': '扎伊德·塔辛',
    'Rebin Sulaka': '雷宾·苏拉卡',
    'Akam Hashim': '阿卡姆·哈希姆',
    'Mehrgas Dosci': '梅赫加斯·多斯基',
    'Ahmed Yahya': '艾哈迈德·叶海亚',
    'Zaid Ismail': '扎伊德·伊斯梅尔',
    'Amir Al-Ammari': '阿米尔·阿玛里',
    'Kevin Yakob': '凯文·雅各布',
    'Zidane Iqbal': '齐达内·伊克巴尔',
    'Aimar Sher': '艾马尔·谢尔',
    'Frands Putros': '弗兰斯·普特罗斯',
    'Mustafa Saadoon': '穆斯塔法·萨登',
    'Yusuf Amin': '优素福·阿明',
    'Ibrahim Bayesh': '易卜拉欣·拜阿什',
    'Ahmed Kaseem': '艾哈迈德·卡塞姆',
    'Marko Farji': '马科·法吉',
    'Ali Jasim': '阿里·贾西姆',
    'Ali Al-Hamadi': '阿里·阿尔哈马迪',
    'Ali Yousif': '阿里·优素福',
    'Ayman Hussein': '埃曼·侯赛因',
    'Mohanad Ali': '莫哈纳德·阿里',

    # ===== Algeria (from zhibo8) =====
    'Luca Zidane': '卢卡·齐达内',
    'Oussama Benbot': '奥萨马·本布特',
    'Melvin Mastier': '梅尔文·马斯蒂尔',
    'Rafik Belgherbi': '拉菲克·贝尔加利',
    'Samir Chergui': '萨米尔·谢尔吉',
    'Rayan Ait-Nouri': '艾特-努里',
    'Gabin Haddad': '加温·哈达姆',
    'Aissa Mandi': '艾沙·曼迪',
    'Ramy Bensebaini': '拉米·本塞拜尼',
    'Zineddine Belaid': '齐丁·贝莱德',
    'Achraf Abada': '阿赫雷夫·阿巴达',
    'Amin Tougai': '阿明·图加伊',
    'Nabil Bentaleb': '纳比尔·本塔莱布',
    'Hicham Boudaoui': '希查姆·布达维',
    'Houssem Aouar': '侯瑟姆·奥亚尔',
    'Fares Chaibi': '法雷斯·沙伊比',
    'Ibrahim Maza': '易卜拉欣·马扎',
    'Yassine Titraoui': '亚辛·蒂特拉维',
    'Ramiz Zerrouki': '拉米兹·泽罗基',
    'Mohamed Amoura': '穆罕穆德·阿穆拉',
    'Ahmed Nadhir Benbouali': '艾哈迈德·纳迪尔·本布利',
    'Adil Boulbina': '阿迪尔·布尔比纳',
    'Fares Ghejemis': '法雷斯·盖杰米斯',
    'Amine Gouiri': '阿明·古伊里',
    'Anis Hadj Moussa': '安尼斯·哈迪·穆萨',
    'Riyad Mahrez': '里亚德·马赫雷斯',

    # ===== Austria (from zhibo8) =====
    'Alexander Schlager': '亚历山大·施拉格',
    'Florian Weigle': '弗洛里安·维格勒',
    'Patrick Penz': '帕特里克·彭茨',
    'David Affengruber': '大卫·阿芬格鲁伯',
    'Stefan Posch': '斯蒂芬·波施',
    'Philipp Lienhart': '菲利普·林哈特',
    'Philipp Mwene': '菲利普·姆维尼',
    'Alexander Prass': '亚历山大·普拉斯',
    'Marco Friedl': '马尔科·弗里德尔',
    'Xaver Schlager': '泽弗尔·施拉格',
    'Nicolas Seiwald': '尼古拉斯·塞沃尔德',
    'Florian Grillitsch': '弗洛里安·格里利奇',
    'Carney Chukwuemeka': '卡尔尼·丘库埃梅卡',
    'Romano Schmid': '罗马诺·施密德',
    'Christopher Baumgartner': '克里斯托弗·鲍姆加特纳',
    'Patrick Wimmer': '帕特里克·维默尔',
    'Paul Wanner': '保尔·万纳尔',
    'Michael Svoboda': '米夏埃尔·斯沃博达',
    'Alessandro Schopf': '阿里桑德罗·舍普夫',
    'Marko Arnautovic': '阿瑙托维奇',
    'Michael Gregoritsch': '米歇尔·格雷戈里施',
    'Sasa Kalajdzic': '萨萨·卡拉季奇',

    # ===== Jordan (from zhibo8) =====
    'Yazid Abu Layla': '亚奇德·阿布拉伊拉',
    'Noureddin Zaid': '努雷丁·扎伊德',
    'Abdullah Fahori': '阿卜杜拉·拉伊德·法霍里',
    'Mohammad Abu Hasheeh': '穆罕默德·阿布海塞',
    'Abdallah Nasib': '阿卜杜拉·纳西布',
    'Hussam Abu Dhahab': '胡萨姆·阿布·达哈布',
    'Yazan Al-Arab': '亚赞·阿拉伯',
    'Mohammad Abulnadi': '穆罕默德·阿卜拉纳迪',
    'Salim Obaid': '萨利姆·奥贝德',
    'Ehsan Haddad': '埃桑·哈达德',
    'Anas Bani Yaseen': '阿纳斯·巴达维',
    'Amer Jamous': '阿米尔·贾穆斯',
    'Noor Al-Rawabdeh': '努尔·阿尔·拉瓦德赫',
    'Rajaei Ayed': '拉杰伊·阿耶德',
    'Ibrahim Saad': '易卜拉欣·萨德',
    'Mohammad Abu Taha': '穆罕默德·阿布·塔哈',
    'Nizar Al-Rashdan': '尼扎尔·阿尔·拉什丹',
    'Mohammad Dawood': '穆罕默德·达伍德',
    'Mohammad Abu Zrayq': '穆罕默德·阿布·兹雷克',
    'Ali Olwan': '阿里·奥尔万',
    'Musa Al-Tamari': '穆萨·塔马里',
    'Audeh Fahori': '奥德·法胡里',
    'Mahmoud Al-Mardi': '马赫穆德·阿尔·马尔迪',
    'Ibrahim Sabra': '易卜拉欣·萨布拉',
    'Said Rosan': '萨伊德·罗桑',
    'Ali Al-Azaizeh': '阿里·阿扎伊泽',
}

def patch_seed_data():
    with open('d:\\AI\\WorldCupGame\\seed_data.py', 'r', encoding='utf-8') as f:
        content = f.read()
    
    count = 0
    # Combine both dictionaries (verified names take priority)
    all_names = dict(WELL_KNOWN)
    all_names.update(CN_NAMES)  # CN_NAMES overrides WELL_KNOWN
    
    for eng_name, cn_name in all_names.items():
        # Try different patterns to match: ('Name', '', Number, 'POS')
        # Pattern 1: ('Name', '', 
        search1 = f"('{eng_name}', '', "
        # Pattern 2: ("Name", '', 
        search2 = f'("{eng_name}", \'\', '
        
        if search1 in content:
            content = content.replace(search1, f"('{eng_name}', '{cn_name}', ")
            count += 1
        elif search2 in content:
            content = content.replace(search2, f'("{eng_name}", \'{cn_name}\', ')
            count += 1
    
    with open('d:\\AI\\WorldCupGame\\seed_data.py', 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Patched {count} Chinese names into seed_data.py")
    print(f"Total names in dictionary: {len(all_names)}")

if __name__ == '__main__':
    patch_seed_data()
