"""Generate HTML table from WCQ player stats JSON V2 (48 World Cup teams)"""
import json
import os

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
json_path = os.path.join(DATA_DIR, "wcq_player_stats.json")
html_path = os.path.join(DATA_DIR, "wcq_player_stats_table.html")
ranking_path = os.path.join(DATA_DIR, "player_ranking.json")

with open(json_path, "r", encoding="utf-8") as f:
    data = json.load(f)

# Load ranking data (generated by shooting_ranking.py)
ranking_data = {"deterministic": [], "monte_carlo": []}
if os.path.exists(ranking_path):
    with open(ranking_path, "r", encoding="utf-8") as f:
        ranking_data = json.load(f)

# Build rows
rows = []
for team, players in data.items():
    for p in players:
        rows.append({
            "team": team,
            "player": p["player"],
            "pos": p["pos"],
            "age": p["age"],
            "mp": p["mp"],
            "starts": p["starts"],
            "min": p["min"],
            "nineties": p["nineties"],
            "gls": p["gls"],
            "ast": p["ast"],
            "ga": p["ga"],
            "g_pk": p["g_pk"],
            "pk": p["pk"],
            "pkatt": p["pkatt"],
            "gls_per90": p["gls_per90"],
            "ast_per90": p["ast_per90"],
            "sh": p.get("sh", 0),
            "sot": p.get("sot", 0),
            "sot_pct": p.get("sot_pct", 0),
            "g_sh": p.get("g_sh", 0),
            "g_sot": p.get("g_sot", 0),
            "og": p.get("og", 0),
            "cry": p.get("cry", 0),
            "crr": p.get("crr", 0),
        })

# Sort by goals descending
rows.sort(key=lambda x: (-x["gls"], -x["ast"], -x["sh"]))

# Team colors (FIFA association colors)
TEAM_COLORS = {
    "Algeria": "#007229", "Andorra": "#001b4d", "Argentina": "#75aadb",
    "Australia": "#ffcc00", "Austria": "#ed2939", "Belgium": "#c8102e",
    "Bosnia-and-Herzegovina": "#002395", "Bolivia": "#007934", "Brazil": "#fcd116",
    "Canada": "#e01111", "Cape-Verde": "#003366", "Colombia": "#fcd116",
    "Congo-DR": "#007f4f", "Cote-dIvoire": "#ff9900", "Croatia": "#e11a22",
    "Curacao": "#003399", "Czechia": "#11457e", "Denmark": "#c8102e",
    "Ecuador": "#fcdd00", "Egypt": "#c8102e", "England": "#cf081f",
    "France": "#002395", "Gambia": "#0d1b7a", "Germany": "#000000",
    "Ghana": "#ce1126", "Haiti": "#00209f", "IR-Iran": "#00843d",
    "Iraq": "#007a3d", "Italy": "#008fd0", "Japan": "#01043a",
    "Jordan": "#c8102e", "Korea-Republic": "#e60000", "Kosovo": "#003366",
    "Mexico": "#126f1e", "Morocco": "#c1272d", "Netherlands": "#ff6600",
    "New-Zealand": "#000000", "Nicaragua": "#0068b4", "Nigeria": "#008751",
    "North-Macedonia": "#d10000", "Norway": "#c8102e", "Panama": "#002a7f",
    "Paraguay": "#d52b1e", "Poland": "#d4213d", "Portugal": "#006600",
    "Qatar": "#7a1f3d", "Saudi-Arabia": "#006c35", "Scotland": "#003876",
    "Senegal": "#fcd116", "South-Africa": "#007a4d", "Spain": "#c60b1e",
    "Sweden": "#005b99", "Switzerland": "#e11a22", "Tunisia": "#e7002a",
    "Turkiye": "#e30a17", "United-States": "#002868", "Uruguay": "#002fa7",
    "Uzbekistan": "#0099b5",
}

total_with_shots = sum(1 for r in rows if r["sh"] > 0)
teams_with_shots = sum(1 for t, pl in data.items() if any(p.get("sh", 0) > 0 for p in pl))

html = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>2026 WCQ Player Statistics</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f1923; color: #e0e0e0; padding: 20px; }
h1 { text-align: center; margin-bottom: 4px; font-size: 24px; color: #fff; }
.subtitle { text-align: center; color: #888; margin-bottom: 20px; font-size: 13px; }

/* Tabs */
.tabs { display: flex; justify-content: center; gap: 0; margin-bottom: 16px; }
.tab { padding: 10px 24px; background: #1a2632; border: 1px solid #2a3a4a; color: #888; cursor: pointer; font-size: 14px; border-radius: 6px 6px 0 0; transition: all 0.2s; }
.tab:hover { background: #243444; color: #ccc; }
.tab.active { background: #1a3a4a; color: #fff; border-color: #4fc3f7; border-bottom-color: #1a3a4a; font-weight: 600; }
.tab:first-child { border-radius: 6px 0 0 0; }
.tab:last-child { border-radius: 0 6px 0 0; }

.tab-content { display: none; }
.tab-content.active { display: block; }

.controls { display: flex; gap: 10px; justify-content: center; margin-bottom: 14px; flex-wrap: wrap; }
.controls select, .controls input, .controls button { padding: 7px 12px; border-radius: 6px; border: 1px solid #333; background: #1a2632; color: #fff; font-size: 13px; }
.controls input { width: 180px; }
.controls button { cursor: pointer; }
.controls button:hover { background: #243444; }
.controls button.active { background: #4fc3f7; color: #000; border-color: #4fc3f7; }
.controls label { color: #aaa; font-size: 13px; display: flex; align-items: center; gap: 6px; }
.controls input[type="checkbox"] { width: auto; accent-color: #4fc3f7; }
.table-wrapper { overflow-x: auto; }
table { width: 100%; border-collapse: collapse; font-size: 12px; min-width: 1200px; }
thead th { position: sticky; top: 0; background: #1a2632; padding: 8px 6px; text-align: left; cursor: pointer; border-bottom: 2px solid #2a3a4a; white-space: nowrap; user-select: none; z-index: 1; }
thead th:hover { background: #243444; }
thead th.sorted-asc::after { content: ' \\u25b2'; color: #4fc3f7; }
thead th.sorted-desc::after { content: ' \\u25bc'; color: #4fc3f7; }
thead th.group-header { background: #13212e; text-align: center; border-bottom: 2px solid #1a3a4a; color: #8ab4f8; font-size: 11px; }
tbody tr { border-bottom: 1px solid #1a2632; transition: background 0.15s; }
tbody tr:hover { background: #1a2632; }
td { padding: 6px; white-space: nowrap; line-height: 1.4; }
.team-badge { display: inline-block; width: 4px; height: 18px; border-radius: 2px; margin-right: 5px; vertical-align: middle; flex-shrink: 0; }
.player-name { font-weight: 600; color: #fff; }
.num { text-align: right; font-variant-numeric: tabular-nums; }
.highlight { color: #ffd54f; font-weight: 700; }
.stat-zero { color: #444; }
.stat-na { color: #333; font-style: italic; }
.pos-gk { color: #ff9800; } .pos-df { color: #4caf50; } .pos-mf { color: #2196f3; } .pos-fw { color: #f44336; }
.team-cell { display: flex; align-items: center; }
#count { text-align: center; color: #666; margin-top: 10px; font-size: 13px; }
.legend { text-align: center; color: #555; font-size: 11px; margin-bottom: 10px; }

/* Ranking specific */
.rank-badge { display: inline-flex; align-items: center; justify-content: center; width: 28px; height: 22px; border-radius: 4px; font-weight: 700; font-size: 11px; }
.rank-1 { background: #ffd700; color: #000; } .rank-2 { background: #c0c0c0; color: #000; } .rank-3 { background: #cd7f32; color: #fff; }
.rank-default { color: #888; }
.score-bar { display: inline-block; height: 14px; border-radius: 3px; background: linear-gradient(90deg, #4fc3f7, #1565c0); min-width: 4px; vertical-align: middle; margin-right: 4px; }
.mc-info { color: #666; font-size: 11px; cursor: help; border-bottom: 1px dotted #555; }
.volatile { color: #ff9800; }

/* Selected player */
tr.selected { background: rgba(76, 175, 80, 0.15) !important; }
tr.selected td { border-bottom-color: rgba(76, 175, 80, 0.3); }
tr.selected .player-name { color: #81c784; }
.selected-badge { display: inline-block; background: #4caf50; color: #fff; font-size: 10px; padding: 1px 6px; border-radius: 8px; margin-left: 6px; font-weight: 600; vertical-align: middle; }
</style>
</head>
<body>
<h1>2026 WCQ Player Statistics</h1>
<p class="subtitle">FBref — All 48 World Cup qualified teams ("""+str(len(rows))+""" players)</p>

<div class="tabs">
  <button class="tab active" data-tab="full">Complete Data</button>
  <button class="tab" data-tab="ranking">Shooter Ranking</button>
</div>

<!-- ===== TAB 1: Full Data ===== -->
<div id="tab-full" class="tab-content active">
<div class="legend">'0' = tracked but zero | '-' = no shot data for this confederation</div>
<div class="controls">
  <select id="teamFilter"><option value="">All Teams</option></select>
  <select id="posFilter"><option value="">All Positions</option><option value="GK">GK</option><option value="DF">DF</option><option value="MF">MF</option><option value="FW">FW</option></select>
  <input type="text" id="search" placeholder="Search player...">
  <select id="shotFilter"><option value="">All</option><option value="has">Has shot data</option><option value="no">No shot data</option></select>
</div>
<div class="table-wrapper">
<table>
<thead>
  <tr>
    <th colspan="3" class="group-header">Team</th>
    <th colspan="4" class="group-header">Player Info</th>
    <th colspan="3" class="group-header">Playing Time</th>
    <th colspan="7" class="group-header">Goals &amp; Assists</th>
    <th colspan="6" class="group-header">Shooting</th>
    <th colspan="3" class="group-header">Discipline</th>
  </tr>
  <tr>
    <th data-col="team">Team</th>
    <th data-col="player">Player</th>
    <th data-col="pos">Pos</th>
    <th data-col="age" class="num">Age</th>
    <th data-col="mp" class="num">MP</th>
    <th data-col="starts" class="num">Starts</th>
    <th data-col="min" class="num">Min</th>
    <th data-col="gls" class="num">Gls</th>
    <th data-col="ast" class="num">Ast</th>
    <th data-col="ga" class="num">G+A</th>
    <th data-col="g_pk" class="num">G-PK</th>
    <th data-col="pk" class="num">PK</th>
    <th data-col="pkatt" class="num">PKatt</th>
    <th data-col="gls_per90" class="num">G/90</th>
    <th data-col="ast_per90" class="num">A/90</th>
    <th data-col="sh" class="num">Sh</th>
    <th data-col="sot" class="num">SoT</th>
    <th data-col="sot_pct" class="num">SoT%</th>
    <th data-col="g_sh" class="num">G/Sh</th>
    <th data-col="g_sot" class="num">G/SoT</th>
    <th data-col="sh_per90" class="num">Sh/90</th>
    <th data-col="og" class="num">OG</th>
    <th data-col="cry" class="num">Yel</th>
    <th data-col="crr" class="num">Red</th>
  </tr>
</thead>
<tbody id="tbody"></tbody>
</table>
</div>
<p id="count"></p>
</div>

<!-- ===== TAB 2: Shooter Ranking ===== -->
<div id="tab-ranking" class="tab-content">
<div class="controls">
  <select id="rkTeamFilter"><option value="">All Teams</option></select>
  <select id="rkPosFilter"><option value="">All Positions</option><option value="GK">GK</option><option value="DF">DF</option><option value="MF">MF</option><option value="FW">FW</option></select>
  <input type="text" id="rkSearch" placeholder="Search player...">
  <label style="color:#aaa;font-size:13px"><input type="checkbox" id="mcToggle"> Monte Carlo (luck simulation)</label>
  <span id="mcInfo" class="mc-info" title="Each team's projected goals adjusted by random factor 0.85-1.15. Shows rank range across 1000 simulations.">\u24d8</span>
</div>
<div class="table-wrapper">
<table>
<thead>
  <tr id="rkHeader">
    <th data-col="rank" class="num">Rank</th>
    <th data-col="player">Player</th>
    <th data-col="team">Team</th>
    <th data-col="pos">Pos</th>
    <th data-col="team_share" class="num">Share%</th>
    <th data-col="final_projected_g" class="num">Total Score</th>
    <th data-col="pk_bonus" class="num">PK+</th>
    <th data-col="og" class="num">OG</th>
    <th data-col="gls_per90" class="num">G/90</th>
    <th data-col="sh" class="num">Sh</th>
    <th data-col="g_sh" class="num">G/Sh</th>
  </tr>
</thead>
<tbody id="rkTbody"></tbody>
</table>
</div>
<p id="rkCount"></p>
</div>

<script>
const DATA = """ + json.dumps(rows, ensure_ascii=False) + """;
const RANKING = """ + json.dumps(ranking_data["deterministic"], ensure_ascii=False) + """;
const MC = """ + json.dumps(ranking_data["monte_carlo"], ensure_ascii=False) + """;
const TEAM_COLORS = """ + json.dumps(TEAM_COLORS, ensure_ascii=False) + """;

// Build MC lookup: player|team -> mc stats
const mcMap = {};
MC.forEach(m => { mcMap[m.player+'|'+m.team] = m; });

// ========== Selection overlay (auto-poll) ==========
const norm = s => s.normalize('NFD').replace(/[\\u0300-\\u036f]/g, '').replace(/[-']/g, ' ').replace(/\\s+/g, ' ').trim().toLowerCase();
const reversed = s => { const p = s.split(' '); return p.length >= 2 ? p[p.length-1] + ' ' + p.slice(0,-1).join(' ') : s; };
let selectedNames = new Set();

function applySelection() {
  document.querySelectorAll('tbody tr[data-player]').forEach(row => {
    const rn = norm(row.getAttribute('data-player'));
    const nameCell = row.querySelector('.player-name');
    if (!nameCell) return;
    const badge = nameCell.querySelector('.selected-badge');
    if (selectedNames.has(rn) || selectedNames.has(reversed(rn))) {
      row.classList.add('selected');
      if (!badge) nameCell.insertAdjacentHTML('beforeend', '<span class="selected-badge">\u5df2\u9009</span>');
    } else {
      row.classList.remove('selected');
      if (badge) badge.remove();
    }
  });
}

function refreshSelections() {
  fetch('/api/teams')
    .then(r => r.json())
    .then(teams => {
      selectedNames = new Set();
      teams.forEach(t => {
        t.players.forEach(p => {
          if (p.selected) {
            const n = norm(p.name);
            selectedNames.add(n);
            selectedNames.add(reversed(n));
          }
        });
      });
      applySelection();
    })
    .catch(() => {});
}
refreshSelections();
setInterval(refreshSelections, 5000);

// ========== TAB SWITCHING ==========
document.querySelectorAll('.tab').forEach(tab => {
  tab.addEventListener('click', () => {
    document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
    document.querySelectorAll('.tab-content').forEach(tc => tc.classList.remove('active'));
    tab.classList.add('active');
    document.getElementById('tab-' + tab.dataset.tab).classList.add('active');
  });
});

// ========== TAB 1: Full Data ==========
const tbody = document.getElementById('tbody');
const countEl = document.getElementById('count');
const teamFilter = document.getElementById('teamFilter');
const posFilter = document.getElementById('posFilter');
const searchEl = document.getElementById('search');
const shotFilter = document.getElementById('shotFilter');

const teams = [...new Set(DATA.map(r => r.team))].sort();
teams.forEach(t => { const o = document.createElement('option'); o.value = t; o.textContent = t; teamFilter.appendChild(o); });

let sortCol = 'gls', sortDir = -1;

function posClass(pos) {
  if (pos.includes('GK')) return 'pos-gk';
  if (pos.includes('FW')) return 'pos-fw';
  if (pos.includes('MF')) return 'pos-mf';
  if (pos.includes('DF')) return 'pos-df';
  return '';
}

function numCell(v, decimals) {
  if (decimals !== undefined) {
    return v === 0 ? '<span class="stat-zero">0.00</span>' : v.toFixed(decimals);
  }
  return v === 0 ? '<span class="stat-zero">0</span>' : (v >= 5 ? '<span class="highlight">'+v+'</span>' : v);
}

function hasTeamShotData(team) {
  return DATA.some(r => r.team === team && r.sh > 0);
}

function shotCell(v) {
  if (v === 0) return '<span class="stat-zero">0</span>';
  return v;
}

function pctCell(v, hasData) {
  if (!hasData) return '<span class="stat-na">-</span>';
  if (v === 0) return '<span class="stat-zero">0.0</span>';
  return v.toFixed(1);
}

function renderFull() {
  const tf = teamFilter.value, pf = posFilter.value, q = searchEl.value.toLowerCase(), sf = shotFilter.value;
  let filtered = DATA.filter(r => {
    if (tf && r.team !== tf) return false;
    if (pf && !r.pos.includes(pf)) return false;
    if (q && !r.player.toLowerCase().includes(q)) return false;
    if (sf === 'has' && r.sh === 0) return false;
    if (sf === 'no' && r.sh > 0) return false;
    return true;
  });
  filtered.sort((a, b) => {
    let va = a[sortCol], vb = b[sortCol];
    if (typeof va === 'string') return sortDir * va.localeCompare(vb);
    return sortDir * (va - vb);
  });
  tbody.innerHTML = filtered.map(r => {
    const teamHasShots = hasTeamShotData(r.team);
    return '<tr data-player="'+r.player+'">'
      + '<td><div class="team-cell"><span class="team-badge" style="background:'+(TEAM_COLORS[r.team]||'#666')+'"></span>'+r.team.replace(/-/g,' ')+'</div></td>'
      + '<td class="player-name">'+r.player+'</td>'
      + '<td class="'+posClass(r.pos)+'">'+r.pos+'</td>'
      + '<td class="num">'+r.age+'</td>'
      + '<td class="num">'+numCell(r.mp)+'</td>'
      + '<td class="num">'+numCell(r.starts)+'</td>'
      + '<td class="num">'+numCell(r.min)+'</td>'
      + '<td class="num">'+numCell(r.gls)+'</td>'
      + '<td class="num">'+numCell(r.ast)+'</td>'
      + '<td class="num">'+numCell(r.ga)+'</td>'
      + '<td class="num">'+numCell(r.g_pk)+'</td>'
      + '<td class="num">'+numCell(r.pk)+'</td>'
      + '<td class="num">'+numCell(r.pkatt)+'</td>'
      + '<td class="num">'+(r.gls_per90 === 0 ? '<span class="stat-zero">0.00</span>' : r.gls_per90.toFixed(2))+'</td>'
      + '<td class="num">'+(r.ast_per90 === 0 ? '<span class="stat-zero">0.00</span>' : r.ast_per90.toFixed(2))+'</td>'
      + (teamHasShots ? '<td class="num">'+shotCell(r.sh)+'</td>' : '<td class="num"><span class="stat-na">-</span></td>')
      + (teamHasShots ? '<td class="num">'+shotCell(r.sot)+'</td>' : '<td class="num"><span class="stat-na">-</span></td>')
      + (teamHasShots ? '<td class="num">'+pctCell(r.sot_pct, r.sh > 0)+'</td>' : '<td class="num"><span class="stat-na">-</span></td>')
      + (teamHasShots ? '<td class="num">'+(r.g_sh === 0 && r.sh > 0 ? '<span class="stat-zero">0.00</span>' : (r.sh > 0 ? r.g_sh.toFixed(2) : '<span class="stat-zero">0.00</span>'))+'</td>' : '<td class="num"><span class="stat-na">-</span></td>')
      + (teamHasShots ? '<td class="num">'+(r.g_sot === 0 && r.sh > 0 ? '<span class="stat-zero">0.00</span>' : (r.sh > 0 ? r.g_sot.toFixed(2) : '<span class="stat-zero">0.00</span>'))+'</td>' : '<td class="num"><span class="stat-na">-</span></td>')
      + (teamHasShots ? '<td class="num">'+pctCell(r.sh/ (r.min/90 || 1) * (r.sh > 0 ? 1 : 0), teamHasShots && r.sh > 0)+'</td>' : '<td class="num"><span class="stat-na">-</span></td>')
      + '<td class="num">'+(r.og === 0 ? '<span class="stat-zero">0</span>' : '<span class="highlight">'+r.og+'</span>')+'</td>'
      + '<td class="num">'+numCell(r.cry)+'</td>'
      + '<td class="num">'+numCell(r.crr)+'</td>'
      + '</tr>';
  }).join('');
  countEl.textContent = 'Showing '+filtered.length+' / '+DATA.length+' players';
  applySelection();
  document.querySelectorAll('#tab-full thead th').forEach(th => {
    th.classList.remove('sorted-asc', 'sorted-desc');
    if (th.dataset.col === sortCol) th.classList.add(sortDir > 0 ? 'sorted-asc' : 'sorted-desc');
  });
}

document.querySelectorAll('#tab-full thead th').forEach(th => {
  th.addEventListener('click', () => {
    const col = th.dataset.col;
    if (!col) return;
    if (sortCol === col) sortDir *= -1; else { sortCol = col; sortDir = -1; }
    renderFull();
  });
});
teamFilter.addEventListener('change', renderFull);
posFilter.addEventListener('change', renderFull);
searchEl.addEventListener('input', renderFull);
shotFilter.addEventListener('change', renderFull);
renderFull();

// ========== TAB 2: Shooter Ranking ==========
const rkTbody = document.getElementById('rkTbody');
const rkCount = document.getElementById('rkCount');
const rkTeamFilter = document.getElementById('rkTeamFilter');
const rkPosFilter = document.getElementById('rkPosFilter');
const rkSearch = document.getElementById('rkSearch');
const mcToggle = document.getElementById('mcToggle');

// Populate team filter for ranking tab
teams.forEach(t => { const o = document.createElement('option'); o.value = t; o.textContent = t; rkTeamFilter.appendChild(o); });

let rkSortCol = 'final_projected_g', rkSortDir = -1;

function rankBadge(r) {
  if (r === 1) return '<span class="rank-badge rank-1">1</span>';
  if (r === 2) return '<span class="rank-badge rank-2">2</span>';
  if (r === 3) return '<span class="rank-badge rank-3">3</span>';
  return '<span class="rank-default">'+r+'</span>';
}

function scoreBar(score, maxScore) {
  const pct = Math.max(3, (score / maxScore) * 100);
  return '<span class="score-bar" style="width:'+pct.toFixed(0)+'px"></span>';
}

function renderRanking() {
  const useMC = mcToggle.checked;
  const tf = rkTeamFilter.value, pf = rkPosFilter.value, q = rkSearch.value.toLowerCase();
  
  let filtered = RANKING.filter(r => {
    if (tf && r.team !== tf) return false;
    if (pf && !r.pos.includes(pf)) return false;
    if (q && !r.player.toLowerCase().includes(q)) return false;
    return true;
  });
  
  filtered.sort((a, b) => {
    let va = a[rkSortCol], vb = b[rkSortCol];
    if (va === undefined) va = 0;
    if (vb === undefined) vb = 0;
    if (typeof va === 'string') return rkSortDir * va.localeCompare(vb);
    return rkSortDir * (va - vb);
  });
  
  const maxScore = RANKING[0] ? RANKING[0].final_projected_g : 10;

  rkTbody.innerHTML = filtered.map((r, i) => {
    const key = r.player + '|' + r.team;
    const mc = mcMap[key];
    let rankHtml;
    if (useMC && mc) {
      const range = mc.best_rank === mc.worst_rank
        ? mc.median_rank
        : mc.best_rank + '-' + mc.worst_rank;
      rankHtml = '<span title="MC median='+mc.median_rank+' / p10-p90='+mc.p10_rank+'-'+mc.p90_rank+'" style="cursor:help">'+range+'</span>';
    } else {
      rankHtml = rankBadge(r.rank);
    }
    
    const teamHasShots = hasTeamShotData(r.team);
    
    return '<tr data-player="'+r.player+'">'
      + '<td class="num">'+rankHtml+'</td>'
      + '<td class="player-name">'+r.player+'</td>'
      + '<td><div class="team-cell"><span class="team-badge" style="background:'+(TEAM_COLORS[r.team]||'#666')+'"></span>'+r.team.replace(/-/g,' ')+'</div></td>'
      + '<td class="'+posClass(r.pos)+'">'+r.pos+'</td>'
      + '<td class="num">'+r.team_share+'%</td>'
      + '<td class="num">'+scoreBar(r.final_projected_g, maxScore)+r.final_projected_g.toFixed(2)+'</td>'
      + '<td class="num">'+(r.pk_bonus > 0 ? '<span style="color:#4fc3f7">+'+r.pk_bonus.toFixed(2)+'</span>' : '<span class="stat-zero">0.00</span>')+'</td>'
      + '<td class="num">'+(r.og > 0 ? '<span style="color:#ff9800">'+r.og+'</span>' : '<span class="stat-zero">0</span>')+'</td>'
      + '<td class="num">'+r.gls_per90.toFixed(2)+'</td>'
      + (teamHasShots ? '<td class="num">'+r.sh+'</td>' : '<td class="num"><span class="stat-na">-</span></td>')
      + (teamHasShots && r.sh > 0 ? '<td class="num">'+(r.g_sh !== undefined ? r.g_sh.toFixed(2) : '0.00')+'</td>' : '<td class="num"><span class="stat-na">-</span></td>')
      + '</tr>';
  }).join('');
  
  rkCount.textContent = 'Showing '+filtered.length+' / '+RANKING.length+' players';
  applySelection();
  
  // Update header sort indicators
  document.querySelectorAll('#tab-ranking thead th').forEach(th => {
    th.classList.remove('sorted-asc', 'sorted-desc');
    if (th.dataset.col === rkSortCol) th.classList.add(rkSortDir > 0 ? 'sorted-asc' : 'sorted-desc');
  });
}

document.querySelectorAll('#tab-ranking thead th').forEach(th => {
  th.addEventListener('click', () => {
    const col = th.dataset.col;
    if (!col) return;
    if (rkSortCol === col) rkSortDir *= -1; else { rkSortCol = col; rkSortDir = -1; }
    renderRanking();
  });
});
rkTeamFilter.addEventListener('change', renderRanking);
rkPosFilter.addEventListener('change', renderRanking);
rkSearch.addEventListener('input', renderRanking);
mcToggle.addEventListener('change', renderRanking);
renderRanking();

</script>
</body></html>"""

with open(html_path, "w", encoding="utf-8") as f:
    f.write(html)

print(f"HTML generated: {html_path}")
print(f"Total: {len(rows)} players across {len(data)} teams")
print(f"Teams with shooting data: {teams_with_shots}/{len(data)} ({total_with_shots} players)")
